// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `account` table.

use sea_orm::entity::prelude::*;

/// One row of `account`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "account")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `username` column.
    #[sea_orm(column_type = "Text")]
    pub username: String,
    /// The `username_lower` column.
    #[sea_orm(column_type = "Text")]
    pub username_lower: String,
    /// The `email` column.
    #[sea_orm(column_type = "Text")]
    pub email: Option<String>,
    /// The `email_lower` column.
    #[sea_orm(column_type = "Text")]
    pub email_lower: Option<String>,
    /// The `phone` column.
    #[sea_orm(column_type = "Text")]
    pub phone: Option<String>,
    /// The `password_hash` column.
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    /// 0 active, 1 suspended, 2 deactivated, 3 deleted
    pub status: i16,
    /// The `country` column.
    #[sea_orm(column_type = "Char(Some(2))")]
    pub country: Option<String>,
    /// The `locale` column.
    #[sea_orm(column_type = "Text")]
    pub locale: String,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `updated_at` column.
    pub updated_at: TimeDateTimeWithTimeZone,
    /// The `last_login_at` column.
    pub last_login_at: Option<TimeDateTimeWithTimeZone>,
    /// The `suspended_until` column.
    pub suspended_until: Option<TimeDateTimeWithTimeZone>,
    /// The `deleted_at` column.
    pub deleted_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `account`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
