// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `audit_entry` table.
//!
//! Written in the same transaction as the action it records, so an action
//! without an audit row cannot exist.

use sea_orm::entity::prelude::*;

/// One row of `audit_entry`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "audit_entry")]
pub struct Model {
    /// The `audit_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_id: Uuid,
    /// The `actor_id` column.
    pub actor_id: Option<Uuid>,
    /// 0 user, 1 system, 2 bot, 3 operator
    pub actor_kind: i16,
    /// The `action` column.
    #[sea_orm(column_type = "Text")]
    pub action: String,
    /// The `target_kind` column.
    pub target_kind: i16,
    /// The `target_id` column.
    pub target_id: Option<Uuid>,
    /// A summary of what changed. Never message content.
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    /// The `reason` column.
    #[sea_orm(column_type = "Text")]
    pub reason: Option<String>,
    /// The `request_id` column.
    #[sea_orm(column_type = "Text")]
    pub request_id: Option<String>,
    /// The `ip_class` column.
    #[sea_orm(column_type = "Text")]
    pub ip_class: Option<String>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `audit_entry`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `actor_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ActorId",
        to = "super::account::Column::AccountId",
        on_delete = "SetNull"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
