// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `badge_award` table.

use sea_orm::entity::prelude::*;

/// One row of `badge_award`.
///
/// The primary key is (account_id, badge_code).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "badge_award")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `badge_code` column.
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub badge_code: String,
    /// The `awarded_at` column.
    pub awarded_at: TimeDateTimeWithTimeZone,
    /// The `ref_id` column.
    pub ref_id: Option<Uuid>,
}

/// Foreign keys leaving `badge_award`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
