// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `bot` table.

use sea_orm::entity::prelude::*;

/// One row of `bot`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bot")]
pub struct Model {
    /// The `bot_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub bot_id: Uuid,
    /// The `owner_id` column.
    pub owner_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// The `name` column.
    #[sea_orm(column_type = "Text")]
    pub name: String,
    /// Hash, not the token. A leaked database must not yield working bot tokens.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub token_hash: Vec<u8>,
    /// The `scopes` column.
    pub scopes: i64,
    /// The `webhook_url` column.
    #[sea_orm(column_type = "Text")]
    pub webhook_url: Option<String>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `disabled_at` column.
    pub disabled_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `bot`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `owner_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::OwnerId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Owner,
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl ActiveModelBehavior for ActiveModel {}
