// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `captcha_challenge` table.

use sea_orm::entity::prelude::*;

/// One row of `captcha_challenge`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "captcha_challenge")]
pub struct Model {
    /// The `challenge_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub challenge_id: Uuid,
    /// The MAC tag over (challenge_id || code). Never the code itself: an attacker
    /// who can read this table still cannot answer without the secret, and the
    /// application code is the only thing that knows it. The code is gone the
    /// moment the challenge is consumed or expires.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tag: Vec<u8>,
    /// Wall-clock instant the challenge stops being accepted. Half-open: a verify
    /// at exactly this instant returns false. The default TTL is 60 seconds; the
    /// service bumps that on hot paths and stores the bumped value here.
    pub expires_at: TimeDateTimeWithTimeZone,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `captcha_challenge`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
