// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `conversation_cursor` table.
//!
//! Unread counts are derived: last_seq − read_seq. A stored counter drifts, and
//! reconciling a drifted counter is worse than computing the difference.

use sea_orm::entity::prelude::*;

/// One row of `conversation_cursor`.
///
/// The primary key is (conversation_id, account_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation_cursor")]
pub struct Model {
    /// The `conversation_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub conversation_id: Uuid,
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `delivered_seq` column.
    pub delivered_seq: i64,
    /// The `read_seq` column.
    pub read_seq: i64,
    /// The `notified_seq` column.
    pub notified_seq: i64,
    /// The `updated_at` column.
    pub updated_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `conversation_cursor`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "Cascade"
    )]
    Conversation,
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
