// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `conversation` table.

use sea_orm::entity::prelude::*;

/// One row of `conversation`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversation")]
pub struct Model {
    /// The `conversation_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub conversation_id: Uuid,
    /// ConversationKind
    pub kind: i16,
    /// EncryptionMode
    pub encryption: i16,
    /// The `room_id` column.
    pub room_id: Option<Uuid>,
    /// The sequencer. `update ... returning` on this row is what makes seq
    /// assignment atomic without a global lock or a sequence per conversation.
    pub last_seq: i64,
    /// The `created_by` column.
    pub created_by: Uuid,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `last_message_at` column.
    pub last_message_at: Option<TimeDateTimeWithTimeZone>,
    /// The `archived_at` column.
    pub archived_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `conversation`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `created_by` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::CreatedBy",
        to = "super::account::Column::AccountId"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
