// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `device` table.

use sea_orm::entity::prelude::*;

/// One row of `device`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "device")]
pub struct Model {
    /// The `device_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// The `platform` column.
    pub platform: i16,
    /// The `display_name` column.
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    /// The `app_version` column.
    #[sea_orm(column_type = "Text")]
    pub app_version: String,
    /// The `os_version` column.
    #[sea_orm(column_type = "Text")]
    pub os_version: Option<String>,
    /// The `device_model` column.
    #[sea_orm(column_type = "Text")]
    pub device_model: Option<String>,
    /// Push tokens are credentials for a third-party service, and section 77 says
    /// they are stored hashed and never logged. A hash alone would be unusable --
    /// a one-way hash of a push token is a token nobody can ever push to -- so the
    /// credential is split across two columns with two different jobs.
    ///
    /// push_token holds the token sealed by migo-notify before it ever reaches the
    /// storage layer: nonce || ciphertext || tag, base64. No key for it exists in
    /// this process or in this database, so a dump of these columns is not a set of
    /// push credentials.
    ///
    /// push_token_hash is the handle. Every lookup, every deduplication, and every
    /// reference in a log line uses it, which is what makes "never log the token"
    /// a rule somebody can actually follow while still debugging delivery.
    #[sea_orm(column_type = "Text")]
    pub push_token: Option<String>,
    /// The `push_token_hash` column.
    #[sea_orm(column_type = "Text")]
    pub push_token_hash: Option<String>,
    /// The `push_provider` column.
    pub push_provider: Option<i16>,
    /// When the registration was last refreshed. FCM and APNs both expire tokens
    /// silently, and a send to a dead token is charged, rate-limited, and useless;
    /// this is what the sweeper reads to stop paying for devices that left.
    pub push_updated_at: Option<TimeDateTimeWithTimeZone>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `last_seen_at` column.
    pub last_seen_at: TimeDateTimeWithTimeZone,
    /// The `revoked_at` column.
    pub revoked_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `device`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
