// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `direct_conversation` table.
//!
//! A direct conversation is keyed by its ordered pair so "open a chat with Bob"
//! is idempotent under concurrency instead of racing into two conversations.

use sea_orm::entity::prelude::*;

/// One row of `direct_conversation`.
///
/// The primary key is (low_account_id, high_account_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "direct_conversation")]
pub struct Model {
    /// The `low_account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub low_account_id: Uuid,
    /// The `high_account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub high_account_id: Uuid,
    /// The `conversation_id` column.
    pub conversation_id: Uuid,
}

/// Foreign keys leaving `direct_conversation`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `low_account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::LowAccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    LowAccount,
    /// `high_account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::HighAccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    HighAccount,
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "Cascade"
    )]
    Conversation,
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
