// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `entitlement` table.
//!
//! What an account owns. Section 29 lists seven things currency buys -- avatar
//! items, stickers, profile frames, themes, cosmetics, event entry, and gifts --
//! and six of those seven are durable. Without this table, spending coins burns
//! them and yields nothing anybody can point at, which is not a currency.
//!
//! Deliberately the same shape as badge_award: a composite primary key over the
//! owner and a text code, no surrogate id. The primary key is what makes buying
//! the same theme twice impossible to represent rather than merely discouraged.

use sea_orm::entity::prelude::*;

/// One row of `entitlement`.
///
/// The primary key is (account_id, sku).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "entitlement")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// Catalogue code, e.g. 'theme.midnight'. Text for the same reason as
    /// gift_code: this list is content, and content grows.
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub sku: String,
    /// The `acquired_at` column.
    pub acquired_at: TimeDateTimeWithTimeZone,
    /// The purchase that granted it, absent for something granted by the system.
    /// Set null rather than restrict: an old transaction can be archived out from
    /// under an entitlement without taking away what somebody bought.
    pub tx_id: Option<Uuid>,
}

/// Foreign keys leaving `entitlement`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `tx_id` → `ledger_transaction (tx_id)`.
    #[sea_orm(
        belongs_to = "super::ledger_transaction::Entity",
        from = "Column::TxId",
        to = "super::ledger_transaction::Column::TxId",
        on_delete = "SetNull"
    )]
    LedgerTransaction,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::ledger_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
