// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `federation_outbox` table.
//!
//! Outbound federation events, delivered at least once with retries. A queue in
//! the database rather than in Redis: this one must survive a restart, and it is
//! written in the same transaction as the state change it announces.

use sea_orm::entity::prelude::*;

/// One row of `federation_outbox`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "federation_outbox")]
pub struct Model {
    /// The `event_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    /// The `target_node` column.
    #[sea_orm(column_type = "Text")]
    pub target_node: String,
    /// The `opcode` column.
    pub opcode: i32,
    /// The `payload` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub payload: Vec<u8>,
    /// The `attempts` column.
    pub attempts: i32,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `next_attempt_at` column.
    pub next_attempt_at: TimeDateTimeWithTimeZone,
    /// The `delivered_at` column.
    pub delivered_at: Option<TimeDateTimeWithTimeZone>,
    /// The `last_error` column.
    #[sea_orm(column_type = "Text")]
    pub last_error: Option<String>,
}

/// Foreign keys leaving `federation_outbox`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
