// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `game_session` table.

use sea_orm::entity::prelude::*;

/// One row of `game_session`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "game_session")]
pub struct Model {
    /// The `game_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub game_id: Uuid,
    /// The `kind` column.
    pub kind: i16,
    /// The `conversation_id` column.
    pub conversation_id: Uuid,
    /// Authoritative state lives on the server: a client that computes its own
    /// score is a client that will eventually report a very good one.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub state: Vec<u8>,
    /// The `turn_of` column.
    pub turn_of: Option<Uuid>,
    /// 0 open, 1 finished, 2 abandoned
    pub status: i16,
    /// The `stake_currency` column.
    pub stake_currency: Option<i16>,
    /// The `stake_amount` column.
    pub stake_amount: Option<i64>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `updated_at` column.
    pub updated_at: TimeDateTimeWithTimeZone,
    /// The `finished_at` column.
    pub finished_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `game_session`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "Cascade"
    )]
    Conversation,
    /// `turn_of` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::TurnOf",
        to = "super::account::Column::AccountId"
    )]
    Account,
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
