// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `gift_sent` table.
//!
//! Who gave what to whom. Section 28 says gifts appear in a profile and in chat,
//! and the ledger cannot answer that: a ledger transaction records that coins
//! moved, not that the thing they bought was a Dragon. This is the receipt.
//!
//! Written in the same transaction as the ledger post it names, which is what
//! makes "charge and deliver" one event rather than two. The unique index on
//! tx_id is the mechanism: the ledger's own idempotency key already collapses a
//! retried gift into one transaction, and one transaction can carry exactly one
//! receipt, so a retry cannot produce a second Dragon either.

use sea_orm::entity::prelude::*;

/// One row of `gift_sent`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "gift_sent")]
pub struct Model {
    /// The `gift_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub gift_id: Uuid,
    /// The `tx_id` column.
    pub tx_id: Uuid,
    /// The `sender_id` column.
    pub sender_id: Uuid,
    /// The `recipient_id` column.
    pub recipient_id: Uuid,
    /// Text and not a smallint, unlike every other discriminator in this schema,
    /// and section 28 is the reason: gifts can be limited and seasonal, so this
    /// catalogue grows every December while NotificationKind does not. A code
    /// somebody can read in a dump beats a number they have to look up, and it
    /// matches badge_award.badge_code, which is the same kind of list.
    #[sea_orm(column_type = "Text")]
    pub gift_code: String,
    /// Where it was shown, when it was shown anywhere. Null for a gift sent from a
    /// profile. Set null on delete: the gift stays received after the conversation
    /// it was sent in is gone.
    pub conversation_id: Option<Uuid>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `gift_sent`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `tx_id` → `ledger_transaction (tx_id)`.
    #[sea_orm(
        belongs_to = "super::ledger_transaction::Entity",
        from = "Column::TxId",
        to = "super::ledger_transaction::Column::TxId",
        on_delete = "Restrict"
    )]
    LedgerTransaction,
    /// `sender_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::SenderId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Sender,
    /// `recipient_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::RecipientId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Recipient,
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "SetNull"
    )]
    Conversation,
}

impl Related<super::ledger_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerTransaction.def()
    }
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
