// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `global_admin` table.
//!
//! One row per account that may moderate every public room. The primary key is
//! the account itself rather than a minted row id, because the row has no life
//! outside the account it names: a grant is the account's presence here, and a
//! revoke is its absence — there is no second grant to tell apart from the
//! first, so there is nothing for a row id to identify.

use sea_orm::entity::prelude::*;

/// One row of `global_admin`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "global_admin")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// Who appointed them. Always the Owner/CEO in this version — the column is
    /// the account that acted rather than a role, so the trail survives even if
    /// the owner designation itself ever moves. History lives in `audit_entry`
    /// (the grant and the revoke are both audited); this column answers the
    /// question a reader of the list asks next: "who put them there?".
    pub granted_by: Uuid,
    /// The `granted_at` column.
    pub granted_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `global_admin`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `granted_by` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::GrantedBy",
        to = "super::account::Column::AccountId"
    )]
    GrantedBy,
}

impl ActiveModelBehavior for ActiveModel {}
