// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `identity_keys` table.

use sea_orm::entity::prelude::*;

/// One row of `identity_keys`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "identity_keys")]
pub struct Model {
    /// The `key_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub key_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// Agility is a column, not a constant (brief section 182): "ML-DSA-65" is
    /// what the first row says, and the next algorithm is a new row with a new
    /// name, never a redefinition of this one.
    #[sea_orm(column_type = "Text")]
    pub algorithm: String,
    /// 1-based, unique per account. Rotation appends version N+1 and flips the
    /// previous row to ROTATED inside one transaction, so an account always has
    /// exactly one ACTIVE identity key, whatever crashed mid-way.
    pub key_version: i32,
    /// The public half only: 1952 bytes for ML-DSA-65. The seed that produced it
    /// never leaves the device (brief section 182, SERVER TIDAK MENYIMPAN).
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    /// 1 active, 2 rotated, 3 revoked.
    pub status: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `revoked_at` column.
    pub revoked_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `identity_keys`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
