// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `identity_key` table.

use sea_orm::entity::prelude::*;

/// One row of `identity_key`.
///
/// The primary key is (account_id, device_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "identity_key")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `device_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_id: Uuid,
    /// 64 bytes: Ed25519 signing key || X25519 exchange key.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `revoked_at` column.
    pub revoked_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `identity_key`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `device_id` → `device (device_id)`.
    #[sea_orm(
        belongs_to = "super::device::Entity",
        from = "Column::DeviceId",
        to = "super::device::Column::DeviceId",
        on_delete = "Cascade"
    )]
    Device,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Device.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
