// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `kick_vote_voter` table.

use sea_orm::entity::prelude::*;

/// One row of `kick_vote_voter`.
///
/// The primary key is (subject_id, voter_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "kick_vote_voter")]
pub struct Model {
    /// The `subject_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: Uuid,
    /// The `voter_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub voter_id: Uuid,
}

/// Foreign keys leaving `kick_vote_voter`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
