// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `kick_vote` table.

use sea_orm::entity::prelude::*;

/// One row of `kick_vote`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "kick_vote")]
pub struct Model {
    /// The `subject_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: Uuid,
    /// The `target_id` column.
    pub target_id: Uuid,
    /// The `opened_at` column.
    pub opened_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `kick_vote`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
