// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `ledger_account` table.

use sea_orm::entity::prelude::*;

/// One row of `ledger_account`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ledger_account")]
pub struct Model {
    /// The `ledger_account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub ledger_account_id: Uuid,
    /// The `owner_id` column.
    pub owner_id: Option<Uuid>,
    /// 0 user, 1 mint, 2 fee, 3 escrow
    pub kind: i16,
    /// 0 coins, 1 gems, 2 points
    pub currency: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `ledger_account`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `owner_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::OwnerId",
        to = "super::account::Column::AccountId",
        on_delete = "Restrict"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
