// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `ledger_transaction` table.

use sea_orm::entity::prelude::*;

/// One row of `ledger_transaction`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ledger_transaction")]
pub struct Model {
    /// The `tx_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub tx_id: Uuid,
    /// The `reason` column.
    pub reason: i16,
    /// The `ref_id` column.
    pub ref_id: Option<Uuid>,
    /// A retried gift must not double-charge. The key is unique, so the retry
    /// collides and the caller reads back the original transaction.
    #[sea_orm(column_type = "Text")]
    pub idempotency_key: String,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `created_by` column.
    pub created_by: Option<Uuid>,
}

/// Foreign keys leaving `ledger_transaction`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `created_by` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::CreatedBy",
        to = "super::account::Column::AccountId"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
