// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `ledger_entry` table.

use sea_orm::entity::prelude::*;

/// One row of `ledger_entry`.
///
/// The primary key is (tx_id, leg_index).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ledger_entry")]
pub struct Model {
    /// The `tx_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub tx_id: Uuid,
    /// Which leg of the transaction this is. Part of the key rather than a
    /// surrogate id, because nothing outside the ledger ever needs to name a
    /// single entry, and the legs have to read back in the order they were
    /// posted: a debit followed by a credit is a transfer, the other order is a
    /// refund, and the difference matters in a receipt.
    #[sea_orm(primary_key, auto_increment = false)]
    pub leg_index: i16,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// Signed minor units. Every transaction's entries must sum to zero; the
    /// application asserts it before insert and a nightly job re-asserts it over
    /// the whole table, because an invariant nobody checks is a wish.
    pub amount: i64,
    /// The `currency` column.
    pub currency: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `ledger_entry`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `tx_id` → `ledger_transaction (tx_id)`.
    #[sea_orm(
        belongs_to = "super::ledger_transaction::Entity",
        from = "Column::TxId",
        to = "super::ledger_transaction::Column::TxId",
        on_delete = "Restrict"
    )]
    LedgerTransaction,
    /// `account_id` → `ledger_account (ledger_account_id)`.
    #[sea_orm(
        belongs_to = "super::ledger_account::Entity",
        from = "Column::AccountId",
        to = "super::ledger_account::Column::LedgerAccountId",
        on_delete = "Restrict"
    )]
    LedgerAccount,
}

impl Related<super::ledger_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerTransaction.def()
    }
}

impl Related<super::ledger_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerAccount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
