// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `ledger_snapshot` table.
//!
//! Balances are the sum of entries. Snapshots exist only so that sum does not
//! have to start from the beginning of time; they are derived and rebuildable.

use sea_orm::entity::prelude::*;

/// One row of `ledger_snapshot`.
///
/// The primary key is (ledger_account_id, as_of).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ledger_snapshot")]
pub struct Model {
    /// The `ledger_account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub ledger_account_id: Uuid,
    /// The `as_of` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub as_of: TimeDateTimeWithTimeZone,
    /// The `balance` column.
    pub balance: i64,
    /// The `entry_count` column.
    pub entry_count: i64,
}

/// Foreign keys leaving `ledger_snapshot`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `ledger_account_id` → `ledger_account (ledger_account_id)`.
    #[sea_orm(
        belongs_to = "super::ledger_account::Entity",
        from = "Column::LedgerAccountId",
        to = "super::ledger_account::Column::LedgerAccountId",
        on_delete = "Cascade"
    )]
    LedgerAccount,
}

impl Related<super::ledger_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LedgerAccount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
