// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `login_challenge` table.

use sea_orm::entity::prelude::*;

/// One row of `login_challenge`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "login_challenge")]
pub struct Model {
    /// The `challenge_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub challenge_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// The challenge is bound to the device it was issued for. For purpose
    /// add-device that device row is created PENDING at issue time and activated
    /// only when the challenge is consumed, so an unconsumed challenge leaves no
    /// usable credential behind.
    pub device_id: Uuid,
    /// Mirrors the protocol's MlDsaPurpose: 1 login, 2 add-device, 3 rotate.
    /// A challenge signed for one purpose is never accepted for another.
    pub purpose: i16,
    /// The exact canonical MSE bytes the client must sign, stored as issued and
    /// never re-derived: verification signs over what the server sent, not over
    /// what the client claims it received.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub payload: Vec<u8>,
    /// Five minutes by policy. Expired rows are deleted by the same sweep that
    /// owns the captcha and recovery tables.
    pub expires_at: TimeDateTimeWithTimeZone,
    /// Stamped on first successful use; a second attempt sees the same error as
    /// an expired challenge, so replay tells the attacker nothing.
    pub consumed_at: Option<TimeDateTimeWithTimeZone>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `login_challenge`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `device_id` → `device (device_id)`.
    #[sea_orm(
        belongs_to = "super::device::Entity",
        from = "Column::DeviceId",
        to = "super::device::Column::DeviceId",
        on_delete = "Cascade"
    )]
    Device,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Device.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
