// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `media_object` table.

use sea_orm::entity::prelude::*;

/// One row of `media_object`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "media_object")]
pub struct Model {
    /// The `media_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub media_id: Uuid,
    /// The `owner_id` column.
    pub owner_id: Uuid,
    /// The `kind` column.
    pub kind: i16,
    /// The `mime` column.
    #[sea_orm(column_type = "Text")]
    pub mime: String,
    /// The `byte_size` column.
    pub byte_size: i64,
    /// The `width` column.
    pub width: Option<i32>,
    /// The `height` column.
    pub height: Option<i32>,
    /// The `duration_ms` column.
    pub duration_ms: Option<i32>,
    /// Object key in the bucket. The bytes never pass through the API process;
    /// clients upload and download with signed URLs.
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    /// Where the upload was destined, recorded when the client asks to begin so a
    /// later download can be authorised against membership rather than against
    /// knowledge of the id. Null for profile media such as an avatar, which every
    /// authenticated account may render. On delete set null rather than cascade:
    /// deleting a conversation must not silently delete the bytes people uploaded
    /// to it, because the sweeper is what removes bytes and it needs the row.
    pub conversation_id: Option<Uuid>,
    /// The `checksum` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub checksum: Option<Vec<u8>>,
    /// 0 pending, 1 clean, 2 rejected
    pub scan_status: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `deleted_at` column.
    pub deleted_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `media_object`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `owner_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::OwnerId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "SetNull"
    )]
    Conversation,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
