// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `message` table.
//!
//! The hottest table in the system, partitioned monthly by created_at.
//!
//! The partition key has to be in every unique constraint, which is why the
//! primary key is (created_at, message_id) rather than message_id alone. Dedup of
//! a client retry is by (conversation_id, message_id) inside a partition; retries
//! happen within seconds, so a retry landing in a different month is not a case
//! worth carrying complexity for.
//!
//! Partitioned by range. Queries address this parent; PostgreSQL routes the row.

use sea_orm::entity::prelude::*;

/// One row of `message`.
///
/// The primary key is (created_at, message_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "message")]
pub struct Model {
    /// The `message_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_id: Uuid,
    /// The `conversation_id` column.
    pub conversation_id: Uuid,
    /// The `seq` column.
    pub seq: i64,
    /// The `sender_id` column.
    pub sender_id: Uuid,
    /// The `sender_device` column.
    pub sender_device: Option<Uuid>,
    /// The `kind` column.
    pub kind: i16,
    /// Ciphertext for private conversations, MSE payload for public rooms. The
    /// database cannot read the former, and no server role can either.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub envelope: Vec<u8>,
    /// The `reply_to` column.
    pub reply_to: Option<Uuid>,
    /// The `expires_at` column.
    pub expires_at: Option<TimeDateTimeWithTimeZone>,
    /// The `created_at` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `edited_at` column.
    pub edited_at: Option<TimeDateTimeWithTimeZone>,
    /// The `deleted_at` column.
    pub deleted_at: Option<TimeDateTimeWithTimeZone>,
    /// The `deleted_by` column.
    pub deleted_by: Option<Uuid>,
}

/// Foreign keys leaving `message`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
