// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! SeaORM entities, one module per table in `server/migrations`.
//!
//! These are an implementation detail of the PostgreSQL backend and are not part of
//! this crate's public API. The traits in [`crate::traits`] speak the domain models in
//! [`crate::model`], so nothing above the store has to know that SeaORM exists — which
//! is the property that lets the ORM be replaced without touching a caller.
//!
//! 40 tables. Regenerate with `make entities` after changing a migration.

#![allow(dead_code)]

pub mod account;
pub mod audit_entry;
pub mod badge_award;
pub mod bot;
pub mod captcha_challenge;
pub mod conversation;
pub mod conversation_cursor;
pub mod conversation_member;
pub mod device;
pub mod direct_conversation;
pub mod entitlement;
pub mod federation_outbox;
pub mod game_session;
pub mod gift_sent;
pub mod global_admin;
pub mod identity_key;
pub mod identity_keys;
pub mod ledger_account;
pub mod ledger_entry;
pub mod ledger_snapshot;
pub mod ledger_transaction;
pub mod login_challenge;
pub mod media_object;
pub mod message;
pub mod node_peer;
pub mod notification;
pub mod one_time_prekey;
pub mod password_recovery;
pub mod profile;
pub mod progression;
pub mod relationship;
pub mod report;
pub mod room;
pub mod room_member;
pub mod room_moderation_action;
pub mod room_network_ban;
pub mod session;
pub mod signed_prekey;
pub mod wallet;
pub mod xp_award;
