// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `node_peer` table.

use sea_orm::entity::prelude::*;

/// One row of `node_peer`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "node_peer")]
pub struct Model {
    /// The `node_id` column.
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub node_id: String,
    /// The `public_key` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    /// The `base_url` column.
    #[sea_orm(column_type = "Text")]
    pub base_url: String,
    /// The `region` column.
    #[sea_orm(column_type = "Text")]
    pub region: String,
    /// 0 allowed, 1 paused, 2 blocked
    pub status: i16,
    /// The `added_at` column.
    pub added_at: TimeDateTimeWithTimeZone,
    /// The `last_seen_at` column.
    pub last_seen_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `node_peer`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
