// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `notification` table.
//!
//! The inbox behind the bell icon.
//!
//! Section 44 lists fourteen notification kinds. Six of them are not rows here,
//! and the discriminator is one question: does answering it make it go away by
//! itself?
//!
//! An unread message answers yes -- conversation_cursor already holds last_seq and
//! read_seq, and the comment above it rejects a stored counter because a stored
//! counter drifts. A row per message would be that counter kept in a second place,
//! disagreeing with the first by the end of the week. The same goes for a voice
//! note, a mention, and a reply, which are messages with an attachment or a name in
//! them. A pending friend request answers yes too: the relationship row *is* the
//! inbox item, and it disappears when the request is answered, where a notification
//! row would linger until a second write cleared it. An incoming call answers yes
//! by expiring -- a call nobody picked up becomes a missed call, which is a row.
//!
//! What is left answers no. A gift, a level up, a badge, an invitation to a room, a
//! room announcement, a scheduled event, a game challenge, a missed call: each one
//! happened, each one leaves a trace somewhere (a ledger transaction, a badge
//! award), and none of those traces records whether the person it happened to has
//! seen it. That is what this table is for, and it is all it is for.
//!
//! Hence the two absences. There is no conversation_id, so a future author in a
//! hurry cannot fill this table with messages. And there is no title and no body,
//! for the same reason section 145's NotificationEvent leaves both empty: the
//! sentence is written on the client in the reader's own language, and a server
//! that stored the sentence would be storing "Alice: see you at eight" in plaintext
//! next to the ciphertext of the message it was rendered from.

use sea_orm::entity::prelude::*;

/// One row of `notification`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    /// The `notification_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// NotificationKind: 5 gift, 6 level up, 7 achievement, 8 room invite, 9 room announcement, 10 event, 11 game challenge, 13 missed call
    pub kind: i16,
    /// The `room_id` column.
    pub room_id: Option<Uuid>,
    /// Who caused it, where somebody did. Null for a level up, which nobody caused.
    /// Set null rather than cascade on delete: a gift that was received stays
    /// received after the giver closes their account.
    pub actor_id: Option<Uuid>,
    /// What it points at: a transaction, a badge award, a call, a game session. No
    /// foreign key, because which table it points into depends on the kind, and a
    /// column that referenced one of them would quietly forbid the others.
    pub subject_id: Option<Uuid>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `read_at` column.
    pub read_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `notification`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `room_id` → `room (room_id)`.
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::RoomId",
        on_delete = "Cascade"
    )]
    Room,
    /// `actor_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ActorId",
        to = "super::account::Column::AccountId",
        on_delete = "SetNull"
    )]
    Actor,
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
