// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `passphrase_recovery` table.

use sea_orm::entity::prelude::*;

/// One row of `passphrase_recovery`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "passphrase_recovery")]
pub struct Model {
    /// The `token_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub token_id: Uuid,
    /// Owning account. Indexed below so a future "list my outstanding recovery
    /// tokens" view does not scan the whole table.
    pub account_id: Uuid,
    /// The MAC tag over (token_id || 'recovery'). 32 bytes, like every other
    /// server-side tag. Never the plaintext, so a database dump is not a
    /// bypass: confirming a token requires the same MacKey root every other
    /// short-lived server token uses, with the LABEL_RECOVERY derivation.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub tag: Vec<u8>,
    /// Wall-clock instant the token stops being accepted. The default is
    /// twenty minutes, derived from the captcha TTL plus a generous allowance
    /// for the email hop that does not exist yet.
    pub expires_at: TimeDateTimeWithTimeZone,
    /// Stamped when the token is exchanged for a new password. Distinct from
    /// the `expires_at` value so an operator can tell a deliberate use from a
    /// timeout without reading the audit log.
    pub consumed_at: Option<TimeDateTimeWithTimeZone>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `passphrase_recovery`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
