// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `profile` table.

use sea_orm::entity::prelude::*;

/// One row of `profile`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "profile")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `display_name` column.
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    /// The `bio` column.
    #[sea_orm(column_type = "Text")]
    pub bio: Option<String>,
    /// The `avatar_media_id` column.
    pub avatar_media_id: Option<Uuid>,
    /// The `birth_year` column.
    pub birth_year: Option<i16>,
    /// Presence and "last seen" are ephemeral (Redis), but the *policy* for who
    /// may see them is durable, so it lives here.
    /// 0 nobody, 1 friends, 2 everyone
    pub show_last_seen: i16,
    /// 0 nobody, 1 friends, 2 everyone
    pub who_can_message: i16,
    /// The `who_can_add` column.
    pub who_can_add: i16,
    /// The `searchable` column.
    pub searchable: bool,
    /// The `updated_at` column.
    pub updated_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `profile`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
