// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `relationship` table.

use sea_orm::entity::prelude::*;

/// One row of `relationship`.
///
/// The primary key is (account_id, other_id, kind).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "relationship")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `other_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub other_id: Uuid,
    /// RelationshipKind
    #[sea_orm(primary_key, auto_increment = false)]
    pub kind: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// Set on a friend request until the other side accepts. A pending row is
    /// how "requested" is represented; there is no separate request table.
    pub accepted_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `relationship`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `other_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::OtherId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Other,
}

impl ActiveModelBehavior for ActiveModel {}
