// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `report` table.

use sea_orm::entity::prelude::*;

/// One row of `report`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "report")]
pub struct Model {
    /// The `report_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub report_id: Uuid,
    /// The `reporter_id` column.
    pub reporter_id: Uuid,
    /// 0 user, 1 message, 2 room, 3 media, 4 bot
    pub subject_kind: i16,
    /// The `subject_id` column.
    pub subject_id: Uuid,
    /// The `room_id` column.
    pub room_id: Option<Uuid>,
    /// The `reason` column.
    pub reason: i16,
    /// The `note` column.
    #[sea_orm(column_type = "Text")]
    pub note: Option<String>,
    /// Evidence is a reference, never a copy of message content: copying private
    /// ciphertext into a moderation table would defeat the point of encrypting it.
    pub evidence_ref: Option<Uuid>,
    /// 0 open, 1 actioned, 2 dismissed
    pub status: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `resolved_at` column.
    pub resolved_at: Option<TimeDateTimeWithTimeZone>,
    /// The `resolved_by` column.
    pub resolved_by: Option<Uuid>,
    /// The `resolution` column.
    pub resolution: Option<i16>,
}

/// Foreign keys leaving `report`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `reporter_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ReporterId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Reporter,
    /// `room_id` → `room (room_id)`.
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::RoomId",
        on_delete = "SetNull"
    )]
    Room,
    /// `resolved_by` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ResolvedBy",
        to = "super::account::Column::AccountId"
    )]
    ResolvedBy,
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
