// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `room_member` table.

use sea_orm::entity::prelude::*;

/// One row of `room_member`.
///
/// The primary key is (room_id, account_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "room_member")]
pub struct Model {
    /// The `room_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: Uuid,
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// RoomRole
    pub role: i16,
    /// Effective permission = role_default | grant, then & ~deny. Deny wins:
    /// moderation must never be overridable by an inherited grant.
    pub permissions_grant: i64,
    /// The `permissions_deny` column.
    pub permissions_deny: i64,
    /// The `joined_at` column.
    pub joined_at: TimeDateTimeWithTimeZone,
    /// The `left_at` column.
    pub left_at: Option<TimeDateTimeWithTimeZone>,
    /// The `muted_until` column.
    pub muted_until: Option<TimeDateTimeWithTimeZone>,
    /// The `banned_until` column.
    pub banned_until: Option<TimeDateTimeWithTimeZone>,
    /// The `ban_reason` column.
    #[sea_orm(column_type = "Text")]
    pub ban_reason: Option<String>,
    /// The `invited_by` column.
    pub invited_by: Option<Uuid>,
}

/// Foreign keys leaving `room_member`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `room_id` → `room (room_id)`.
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::RoomId",
        on_delete = "Cascade"
    )]
    Room,
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
