// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `room_moderation_action` table.

use sea_orm::entity::prelude::*;

/// One row of `room_moderation_action`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "room_moderation_action")]
pub struct Model {
    /// The `action_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub action_id: Uuid,
    /// The `room_id` column.
    pub room_id: Uuid,
    /// The `actor_id` column.
    pub actor_id: Uuid,
    /// The `target_id` column.
    pub target_id: Option<Uuid>,
    /// The `action` column.
    pub action: i16,
    /// The `reason` column.
    #[sea_orm(column_type = "Text")]
    pub reason: Option<String>,
    /// The `expires_at` column.
    pub expires_at: Option<TimeDateTimeWithTimeZone>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `room_moderation_action`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `room_id` → `room (room_id)`.
    #[sea_orm(
        belongs_to = "super::room::Entity",
        from = "Column::RoomId",
        to = "super::room::Column::RoomId",
        on_delete = "Cascade"
    )]
    Room,
    /// `actor_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ActorId",
        to = "super::account::Column::AccountId"
    )]
    Actor,
    /// `target_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::TargetId",
        to = "super::account::Column::AccountId"
    )]
    Target,
}

impl Related<super::room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Room.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
