// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `room` table.

use sea_orm::entity::prelude::*;

/// One row of `room`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "room")]
pub struct Model {
    /// The `room_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: Uuid,
    /// The `conversation_id` column.
    pub conversation_id: Uuid,
    /// The `slug` column.
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    /// The `name` column.
    #[sea_orm(column_type = "Text")]
    pub name: String,
    /// The `topic` column.
    #[sea_orm(column_type = "Text")]
    pub topic: Option<String>,
    /// RoomKind: public | managed | private
    pub kind: i16,
    /// The `owner_id` column.
    pub owner_id: Uuid,
    /// The `home_region` column.
    #[sea_orm(column_type = "Text")]
    pub home_region: String,
    /// The `member_count` column.
    pub member_count: i32,
    /// The `max_members` column.
    pub max_members: i32,
    /// The `slow_mode_seconds` column.
    pub slow_mode_seconds: i32,
    /// 0 open, 1 request, 2 invite only
    pub join_policy: i16,
    /// Public and Managed rooms are transport-encrypted and server-readable, and
    /// the client is required to say so. Private rooms are end-to-end.
    pub encryption: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `updated_at` column.
    pub updated_at: TimeDateTimeWithTimeZone,
    /// The `archived_at` column.
    pub archived_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `room`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `conversation_id` → `conversation (conversation_id)`.
    #[sea_orm(
        belongs_to = "super::conversation::Entity",
        from = "Column::ConversationId",
        to = "super::conversation::Column::ConversationId",
        on_delete = "Cascade"
    )]
    Conversation,
    /// `owner_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::OwnerId",
        to = "super::account::Column::AccountId"
    )]
    Account,
}

impl Related<super::conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversation.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
