// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `room_network_ban` table.

use sea_orm::entity::prelude::*;

/// One row of `room_network_ban`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "room_network_ban")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `reason` column.
    #[sea_orm(column_type = "Text")]
    pub reason: Option<String>,
    /// The `until` column.
    pub until: Option<TimeDateTimeWithTimeZone>,
    /// The `by_actor` column.
    pub by_actor: Option<Uuid>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `room_network_ban`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `by_actor` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::ByActor",
        to = "super::account::Column::AccountId"
    )]
    ByActor,
}

impl ActiveModelBehavior for ActiveModel {}
