// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `session` table.

use sea_orm::entity::prelude::*;

/// One row of `session`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "session")]
pub struct Model {
    /// The `session_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub session_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// The `device_id` column.
    pub device_id: Uuid,
    /// All rotations of one login share a family. Detecting reuse of a retired
    /// refresh token means the family was stolen, and the whole family dies.
    pub family_id: Uuid,
    /// The `refresh_hash` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub refresh_hash: Vec<u8>,
    /// The `generation` column.
    pub generation: i32,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// When the human last proved presence by typing a password or passkey. Carried
    /// forward across rotations, because a refresh proves possession of a token and
    /// not the presence of a person. Sensitive operations compare against this
    /// (REAUTHENTICATION_REQUIRED, error 1108).
    pub authenticated_at: TimeDateTimeWithTimeZone,
    /// The `rotated_at` column.
    pub rotated_at: Option<TimeDateTimeWithTimeZone>,
    /// The `access_expires_at` column.
    pub access_expires_at: TimeDateTimeWithTimeZone,
    /// The `refresh_expires_at` column.
    pub refresh_expires_at: TimeDateTimeWithTimeZone,
    /// The `revoked_at` column.
    pub revoked_at: Option<TimeDateTimeWithTimeZone>,
    /// The `revoked_reason` column.
    pub revoked_reason: Option<i16>,
    /// Truncated to a /24 or /48 class before storage, kept 7 days (retention
    /// policy in docs/04-data-model.md §6). Never a full address.
    #[sea_orm(column_type = "Text")]
    pub ip_class: Option<String>,
    /// The `user_agent` column.
    #[sea_orm(column_type = "Text")]
    pub user_agent: Option<String>,
}

/// Foreign keys leaving `session`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
    /// `device_id` → `device (device_id)`.
    #[sea_orm(
        belongs_to = "super::device::Entity",
        from = "Column::DeviceId",
        to = "super::device::Column::DeviceId",
        on_delete = "Cascade"
    )]
    Device,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::device::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Device.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
