// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `signed_prekey` table.

use sea_orm::entity::prelude::*;

/// One row of `signed_prekey`.
///
/// The primary key is (account_id, device_id, key_id).
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "signed_prekey")]
pub struct Model {
    /// The `account_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    /// The `device_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_id: Uuid,
    /// The `key_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub key_id: i32,
    /// The `public_key` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    /// The `signature` column.
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub signature: Vec<u8>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `expires_at` column.
    pub expires_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `signed_prekey`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id, device_id` → `identity_key (account_id, device_id)`.
    #[sea_orm(
        belongs_to = "super::identity_key::Entity",
        from = "(Column::AccountId, Column::DeviceId)",
        to = "(super::identity_key::Column::AccountId, super::identity_key::Column::DeviceId)",
        on_delete = "Cascade"
    )]
    IdentityKey,
}

impl Related<super::identity_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityKey.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
