// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `wallet` table.

use sea_orm::entity::prelude::*;

/// One row of `wallet`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "wallet")]
pub struct Model {
    /// The `wallet_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub wallet_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// Lowercase hex, 40 characters, no 0x prefix: the canonical form, so the
    /// unique index below cannot be defeated by a checksum-cased duplicate. The
    /// EIP-55 form is display material the clients derive; the server never
    /// needs it. No on-chain balance, no broadcast, no RPC in this version.
    #[sea_orm(column_type = "Text")]
    pub address: String,
    /// "evm" today. A second chain is a new row with a new chain_type, not a
    /// schema change.
    #[sea_orm(column_type = "Text")]
    pub chain_type: String,
    /// Optional, user-chosen, display only.
    #[sea_orm(column_type = "Text")]
    pub label: Option<String>,
    /// The i in m/44'/60'/0'/0/i. Kept so a restore can re-register the same
    /// wallets in the same order without deriving a single key server-side.
    pub derivation_index: i32,
    /// 1 active, 2 archived.
    pub status: i16,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
    /// The `archived_at` column.
    pub archived_at: Option<TimeDateTimeWithTimeZone>,
}

/// Foreign keys leaving `wallet`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
