// @generated by tools/entity-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: server/migrations/*.sql.
// Regenerate with: make entities
//! The `xp_award` table.
//!
//! One row per XP award, which the running total above cannot replace.
//!
//! Two requirements need it and neither can be met by a counter. Section 32 ranks
//! weekly and monthly, and a weekly rank is the sum of what was earned inside the
//! week -- a lifetime total does not contain that number. Section 30 says "gunakan
//! anti-farming system", and the only honest way to cap what an account earns from
//! one source per day is to know what it has already earned from that source today.
//! Both are sums over a window, and a window needs events.
//!
//! The total in progression is kept alongside rather than derived from this table,
//! because every profile view and the all-time leaderboard read it, and summing a
//! lifetime of awards to render one number would be the most expensive read in the
//! product. Both rows are written in one transaction, so the two cannot disagree.
//!
//! No room_id column: the room leaderboard ranks a room's current members by what
//! they have earned anywhere, because five of section 30's seven sources have nothing
//! to do with a room. A column that only one source could ever fill would invite a
//! reader to believe the other six were losing data.

use sea_orm::entity::prelude::*;

/// One row of `xp_award`.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "xp_award")]
pub struct Model {
    /// The `award_id` column.
    #[sea_orm(primary_key, auto_increment = false)]
    pub award_id: Uuid,
    /// The `account_id` column.
    pub account_id: Uuid,
    /// The `source` column.
    pub source: i16,
    /// The `amount` column.
    pub amount: i64,
    /// The `ref_id` column.
    pub ref_id: Option<Uuid>,
    /// The `idempotency_key` column.
    #[sea_orm(column_type = "Text")]
    pub idempotency_key: Option<String>,
    /// The `created_at` column.
    pub created_at: TimeDateTimeWithTimeZone,
}

/// Foreign keys leaving `xp_award`.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// `account_id` → `account (account_id)`.
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::AccountId",
        on_delete = "Cascade"
    )]
    Account,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
