//! Writes the rust-reference conformance vectors for the account crate.
//!
//! Run with `make vectors` (or `cargo run -p migo-account --example
//! write_reference_vectors`) to (re)generate
//! `shared/protocol/vectors/crypto/account-mldsa.json` and
//! `account-container.json`.
//!
//! # Why these files are "rust-reference" and not "independent-python"
//!
//! The HKDF and BIP-32 vectors are generated by a Python implementation
//! written from their specifications, because those documents define every
//! step and a second implementation can be checked against their published
//! vectors. ML-DSA-65 and the `.migo` container are different:
//!
//! * ML-DSA-65 has no compact published vector set a script can re-derive
//!   from the FIPS document alone — the algorithm is the better part of a
//!   hundred pages of lattice arithmetic, and reimplementing it in Python
//!   would not be an *independent check*, it would be a second copy of the
//!   same hard-to-audit code. So this crate, pinned to the RustCrypto
//!   `ml-dsa` implementation of FIPS 204 final, is the reference, and the
//!   TypeScript and Kotlin ports are held to *it*, byte for byte.
//! * The container's expected bytes depend on Argon2id and
//!   XChaCha20-Poly1305 exactly as the Rust stack composes them; what the
//!   ports must reproduce is the composition, and the composition is defined
//!   here.
//!
//! The provenance field inside each case says so explicitly, and the vectors
//! README documents the policy. Honesty about what a vector proves is part of
//! what makes a vector worth committing.
//!
//! # Determinism
//!
//! Every input is a constant: roots, payloads, salt, nonce, Argon2id
//! parameters. Deterministic ML-DSA signing (FIPS 204 permits both variants)
//! means the signature bytes are a pure function of the seed and payload, so
//! the ports agree on the *signature*, not just on pass/fail.

use std::path::PathBuf;

use migo_account::container::seal_container_with;
use migo_account::identity::{DeviceCredential, IdentityKey, PUBLIC_KEY_LEN, SIGNATURE_LEN};
use migo_account::root::{MigoRoot, DOMAIN_IDENTITY};
use migo_account::{AccountFile, ContainerParams};
use serde::Serialize;

/// A 55-byte canonical challenge payload, as the login flow delivers it.
const PAYLOAD: &[u8] = b"migo-login-challenge-canonical-payload-0123456789abcdef";

/// The three fixed roots the account vectors share with the Python generator
/// (`account-domains.json`, `account-evm.json`): A, B, and the all-zero
/// degenerate case.
const ROOT_A_HEX: &str = "8f2a1c9d4e6b3a7f5d0c8e1b9a2f4d6c8e0a2b4d6f8c0e2a4b6d8f0a2c4e6d80";
const ROOT_B_HEX: &str = "1a3c5e7f9b1d3f5a7c9e1b3d5f7a9c1e3b5d7f9a1c3e5b7d9f1a3c5e7b9d1f3a";

/// A fixed device-credential seed: device credentials are random per device,
/// and this vector pins the seed → public key → signature relation, not any
/// (nonexistent, by design) derivation from the root.
const DEVICE_SEED_HEX: &str = "d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3";

/// The recovery credential for the container vectors.
const CREDENTIAL: &str = "recovery-credential-vector-1";

/// Argon2id parameters for the container vectors: the floor of the accepted
/// range, so the TypeScript and Kotlin ports can recompute the container
/// without paying the production 64 MiB per case.
const VECTOR_PARAMS: ContainerParams = ContainerParams {
    memory_kib: 8 * 1024,
    time_cost: 1,
    lanes: 1,
};

#[derive(Serialize)]
struct MlDsaCase {
    name: &'static str,
    /// The account root, hex — the input everything else is a function of.
    root: String,
    /// The seed of the key being exercised, hex (identity: the domain seed;
    /// device: the fixed seed above).
    seed: String,
    public_key: String,
    context: &'static str,
    payload: String,
    signature: String,
    provenance: &'static str,
}

#[derive(Serialize)]
struct ContainerCase {
    name: &'static str,
    root: String,
    credential: &'static str,
    salt: String,
    nonce: String,
    memory_kib: u32,
    time_cost: u32,
    lanes: u32,
    created_at: u64,
    /// The complete container file, hex: header and sealed body.
    container: String,
    provenance: &'static str,
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn root(hex_text: &str) -> MigoRoot {
    MigoRoot::from_bytes(&unhex(hex_text)).expect("a fixed root parses")
}

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../shared/protocol/vectors/crypto")
}

fn write(file: &str, value: &impl Serialize) {
    let path = vectors_dir().join(file);
    let json = serde_json::to_string_pretty(value).expect("serialize");
    std::fs::write(&path, json + "\n").unwrap_or_else(|e| panic!("write {path:?}: {e}"));
    println!("wrote {}", path.display());
}

fn mldsa_case(
    name: &'static str,
    root_hex: &'static str,
    seed: &[u8; 32],
    context: &'static str,
    payload: &[u8],
    sign: impl Fn(&[u8]) -> [u8; SIGNATURE_LEN],
    public_key: &[u8; PUBLIC_KEY_LEN],
) -> MlDsaCase {
    let signature = sign(payload);
    assert_eq!(
        signature.len(),
        SIGNATURE_LEN,
        "the vector must pin a full ML-DSA-65 signature"
    );
    MlDsaCase {
        name,
        root: root_hex.to_owned(),
        seed: hex(seed),
        public_key: hex(public_key),
        context,
        payload: hex(payload),
        signature: hex(&signature),
        provenance: "rust-reference",
    }
}

fn main() {
    let root_a = root(ROOT_A_HEX);
    let root_b = root(ROOT_B_HEX);
    let identity_a = IdentityKey::from_root(&root_a);
    let identity_b = IdentityKey::from_root(&root_b);
    let device = DeviceCredential::from_seed(&unhex(DEVICE_SEED_HEX)).expect("fixed seed parses");

    let cases = vec![
        mldsa_case(
            "identity_login_root_a",
            ROOT_A_HEX,
            &root_a.domain_seed(DOMAIN_IDENTITY),
            "migo-auth-login-v1",
            PAYLOAD,
            |p| identity_a.sign_login(p).expect("sign"),
            &identity_a.public_key(),
        ),
        mldsa_case(
            // Same key, same payload, the rotation context: pins the context
            // separation a port would break by signing with an empty context.
            "identity_rotate_root_a",
            ROOT_A_HEX,
            &root_a.domain_seed(DOMAIN_IDENTITY),
            "migo-auth-rotate-v1",
            PAYLOAD,
            |p| identity_a.sign_rotate(p).expect("sign"),
            &identity_a.public_key(),
        ),
        mldsa_case(
            "identity_login_root_b",
            ROOT_B_HEX,
            &root_b.domain_seed(DOMAIN_IDENTITY),
            "migo-auth-login-v1",
            PAYLOAD,
            |p| identity_b.sign_login(p).expect("sign"),
            &identity_b.public_key(),
        ),
        mldsa_case(
            // The device half of the login ceremony, under its own context.
            "device_credential_login",
            ROOT_A_HEX,
            &unhex(DEVICE_SEED_HEX)
                .try_into()
                .expect("fixed seed is 32 bytes"),
            "migo-auth-device-v1",
            PAYLOAD,
            |p| device.sign_login(p).expect("sign"),
            &device.public_key(),
        ),
    ];
    write(
        "account-mldsa.json",
        &serde_json::json!({
            "$comment": "ML-DSA-65 account identity and device credentials: root → domain seed → FIPS 204 key → public key and deterministic signature. The signature bytes are pinned, not just pass/fail, because the ports must produce identical bytes.",
            "provenance": "rust-reference: computed by server/crates/migo-account/examples/write_reference_vectors.rs against ml-dsa 0.1 (FIPS 204 final). ML-DSA has no script-reproducible published vector set; see the README's provenance policy.",
            "note": "`seed` is the ML-DSA seed (Algorithm 6 input): for identity cases the MIGO/IDENTITY/V1 domain seed, for the device case the fixed per-device seed. Deterministic signing, so signature is a pure function of seed, context and payload.",
            "cases": cases,
        }),
    );

    let container_cases = [
        (ROOT_A_HEX, 1_700_000_000u64),
        (ROOT_B_HEX, 1_710_000_000u64),
    ]
    .into_iter()
    .enumerate()
    .map(|(i, (root_hex, created_at))| {
        let root = root(root_hex);
        let file = AccountFile::new(&root, created_at);
        let salt = [(i as u8) + 1; 16];
        let mut nonce = [0u8; 24];
        nonce[0] = i as u8 + 1;
        let container = seal_container_with(CREDENTIAL, &file, VECTOR_PARAMS, &salt, &nonce)
            .expect("deterministic sealing");
        ContainerCase {
            name: if i == 0 {
                "container_root_a"
            } else {
                "container_root_b"
            },
            root: root_hex.to_owned(),
            credential: CREDENTIAL,
            salt: hex(&salt),
            nonce: hex(&nonce),
            memory_kib: VECTOR_PARAMS.memory_kib,
            time_cost: VECTOR_PARAMS.time_cost,
            lanes: VECTOR_PARAMS.lanes,
            created_at,
            container: hex(&container),
            provenance: "rust-reference",
        }
    })
    .collect::<Vec<_>>();
    write(
        "account-container.json",
        &serde_json::json!({
            "$comment": "The .migo container format: Argon2id (header parameters) → HKDF MIGO/BACKUP/V1 → XChaCha20-Poly1305, whole header as associated data. Each case is a complete container; a port recomputes it from the inputs and must match every byte.",
            "provenance": "rust-reference: computed by server/crates/migo-account/examples/write_reference_vectors.rs. The container's bytes are the composition of the house KDF, HKDF and AEAD exactly as the Rust stack builds it.",
            "note": "Argon2id parameters are the accepted floor so the ports can recompute quickly; production containers use 64 MiB / 3 passes, which rides in the header and is honored on open.",
            "cases": container_cases,
        }),
    );
}
