/**
 * The sealing module: content that is encrypted for storage, not for a session.
 *
 * The vector suite pins the AEAD underneath against externally generated bytes; this file pins
 * what {@link sealing} adds on top of it, and every rule here is one that would silently regress
 * under an innocent-looking change:
 *
 *   1. **A sealed object round-trips through its wire slots.** The whole design of a
 *      `MediaRefContent` is that the key and nonce travel beside the sealed bytes; if `open`
 *      ever disagreed with what `seal` put in those slots, the object uploads, the message
 *      sends, and the receiver sees a decryption failure — the worst possible place to learn
 *      about it, bytes already on the server.
 *   2. **Every seal mints fresh key material.** Two seals of one plaintext must differ in both
 *      key and nonce, or a caller somewhere is reusing an object's key for the next object.
 *   3. **The domain label is authenticated.** A blob sealed for media must not open as a voice
 *      note, and a signaling blob must not open under another call's id.
 *   4. **Spliced slots are refused.** A message whose key slot, nonce slot, and bytes did not
 *      all come from one seal must fail as one `DecryptionFailed`, indistinguishable from any
 *      other forgery.
 */

import assert from 'node:assert/strict';
import test from 'node:test';
import { inspect } from 'node:util';

import { CryptoError, sealing } from '../src/index.js';

const MEDIA_DOMAIN = new TextEncoder().encode('migo-media');
const VOICE_DOMAIN = new TextEncoder().encode('migo-voice');

/** Asserts that `fn` throws the one CryptoError kind `expected`, and nothing of the input. */
function throwsKind(expected: string, fn: () => unknown, why: string): void {
  let caught: unknown;
  try {
    fn();
  } catch (cause) {
    caught = cause;
  }
  assert.ok(caught instanceof CryptoError, `${why}: expected CryptoError, got ${String(caught)}`);
  assert.equal(caught.kind, expected, why);
}

test('a sealed object round-trips through exactly its wire slots', () => {
  const plaintext = new TextEncoder().encode('the bytes that will sit in object storage');
  const { key, nonce, sealed } = sealing.seal(plaintext, MEDIA_DOMAIN);

  assert.equal(key.length, 32, 'the key slot is 32 bytes');
  assert.equal(nonce.length, 24, 'the nonce slot is 24 bytes');
  assert.equal(
    sealed.length,
    plaintext.length + 24 + 16,
    'the stored bytes are nonce || ciphertext || tag',
  );

  const opened = sealing.open(key, nonce, MEDIA_DOMAIN, sealed);
  assert.deepEqual(opened, plaintext, 'the object opens from its slots alone');
});

test('every seal mints a fresh key and a fresh nonce', () => {
  const plaintext = new TextEncoder().encode('sealed twice, on purpose');
  const first = sealing.seal(plaintext, MEDIA_DOMAIN);
  const second = sealing.seal(plaintext, MEDIA_DOMAIN);
  assert.notDeepEqual(first.key, second.key, 'two objects must never share a key');
  assert.notDeepEqual(first.nonce, second.nonce, 'two objects must never share a nonce');
  assert.notDeepEqual(
    first.sealed,
    second.sealed,
    'two seals of one plaintext must differ, or the RNG is not being used',
  );
});

test('an empty plaintext still seals and opens', () => {
  // Real callers never upload zero bytes (the server refuses the size), but the module's
  // contract is not "except empty": the tag alone must authenticate the object.
  const { key, nonce, sealed } = sealing.seal(new Uint8Array(0), MEDIA_DOMAIN);
  assert.equal(sealed.length, 24 + 16, 'a sealed empty object is nonce and tag and nothing else');
  assert.deepEqual(sealing.open(key, nonce, MEDIA_DOMAIN, sealed), new Uint8Array(0));
});

test('the domain label is authenticated, not merely accepted', () => {
  const plaintext = new TextEncoder().encode('halo dunia');
  const { key, nonce, sealed } = sealing.seal(plaintext, MEDIA_DOMAIN);
  throwsKind(
    'DecryptionFailed',
    () => sealing.open(key, nonce, VOICE_DOMAIN, sealed),
    'a media blob must not open as a voice note',
  );
});

test('a wrong key, spliced slots, and edited bytes are one refusal', () => {
  const plaintext = new TextEncoder().encode('the one object this message references');
  const { key, nonce, sealed } = sealing.seal(plaintext, MEDIA_DOMAIN);

  const other = sealing.seal(plaintext, MEDIA_DOMAIN);
  throwsKind(
    'DecryptionFailed',
    () => sealing.open(other.key, nonce, MEDIA_DOMAIN, sealed),
    "another object's key must not open this object",
  );
  throwsKind(
    'DecryptionFailed',
    () => sealing.open(key, other.nonce, MEDIA_DOMAIN, sealed),
    "another object's nonce slot must not open this object's bytes",
  );

  const edited = sealed.slice();
  const last = edited.length - 1;
  edited[last] = (edited[last] ?? 0) ^ 0x01;
  throwsKind(
    'DecryptionFailed',
    () => sealing.open(key, nonce, MEDIA_DOMAIN, edited),
    'a flipped tag bit must not open',
  );
});

test('wrong-width slots are refused before any decryption is attempted', () => {
  const { key, nonce, sealed } = sealing.seal(new TextEncoder().encode('x'), MEDIA_DOMAIN);
  throwsKind(
    'BadLength',
    () => sealing.open(new Uint8Array(31), nonce, MEDIA_DOMAIN, sealed),
    'a 31-byte key',
  );
  throwsKind(
    'BadLength',
    () => sealing.open(key, new Uint8Array(12), MEDIA_DOMAIN, sealed),
    'a GCM-sized nonce',
  );
  throwsKind(
    'BadLength',
    () => sealing.open(key, nonce, MEDIA_DOMAIN, new Uint8Array(8)),
    'bytes shorter than their own nonce',
  );
});

test('no error carries the bytes or the key it was handed', () => {
  const secret = new TextEncoder().encode('plaintext that must not reach a log line');
  const { key, nonce, sealed } = sealing.seal(secret, MEDIA_DOMAIN);
  const refusals: unknown[] = [];
  try {
    sealing.open(key, nonce, VOICE_DOMAIN, sealed);
  } catch (cause) {
    refusals.push(cause);
  }
  try {
    sealing.open(new Uint8Array(31), nonce, MEDIA_DOMAIN, sealed);
  } catch (cause) {
    refusals.push(cause);
  }
  for (const refusal of refusals) {
    const text = `${String(refusal)} ${inspect(refusal)}`;
    assert.ok(!text.includes('plaintext that'), 'the refusal must not quote the plaintext');
    assert.ok(
      !text.includes(Buffer.from(key).toString('hex')),
      'the refusal must not quote the key',
    );
  }
});
