package com.migo.core.crypto

import com.goterl.lazysodium.LazySodiumJava
import com.goterl.lazysodium.SodiumJava
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.BeforeClass
import org.junit.Test

/**
 * The sealing module: content that is encrypted for storage, not for a session — a port of the
 * web suite (`packages/crypto/test/sealing.test.ts`), and several of these cases are not this
 * module's word against itself but this module's word against the *web build's*, because the
 * sealed layout and the slot widths are cross-client contracts: an object sealed here is opened
 * by a browser, and its key arrives in a `MediaRef` slot the web build wrote.
 *
 * The vector suite pins the AEAD underneath against externally generated bytes; this file pins
 * what [Sealing] adds on top of it, and every rule here is one that would silently regress under
 * an innocent-looking change:
 *
 *   1. **A sealed object round-trips through exactly its wire slots.** The whole design of a
 *      `MediaRef` is that the key and nonce travel beside the sealed bytes; if [Sealing.open]
 *      ever disagreed with what [Sealing.seal] put in those slots, the object uploads, the
 *      message sends, and the receiver sees a decryption failure — the worst possible place to
 *      learn about it, bytes already on the server.
 *   2. **Every seal mints fresh key material.** Two seals of one plaintext must differ in both
 *      key and nonce, or a caller somewhere is reusing an object's key for the next object.
 *   3. **The domain label is authenticated.** A blob sealed for media must not open as a voice
 *      note, and a signaling blob must not open under another call's id.
 *   4. **Spliced slots are refused.** A message whose key slot, nonce slot, and bytes did not
 *      all come from one seal must fail as one decryption failure, indistinguishable from any
 *      other forgery.
 *
 * The AEAD half needs real libsodium, and the Android artifact's native library only loads on a
 * device, so the suite injects the desktop handle through [Sodium.overrideForTesting] — the same
 * C code the device runs, loaded for the host JVM.
 */
class SealingTest {
    companion object {
        private val MEDIA_DOMAIN = "migo-media".toByteArray()
        private val VOICE_DOMAIN = "migo-voice".toByteArray()

        @BeforeClass
        @JvmStatic
        fun loadDesktopLibsodium() {
            Sodium.overrideForTesting(LazySodiumJava(SodiumJava()))
        }
    }

    /** Asserts that [body] throws the one [CryptoErrorKind] [expected], and nothing of the input. */
    private fun throwsKind(expected: CryptoErrorKind, body: () -> Unit, why: String) {
        try {
            body()
        } catch (caught: CryptoError) {
            assertEquals(why, expected, caught.kind)
            return
        }
        fail("$why: expected CryptoError, got none")
    }

    @Test
    fun `a sealed object round-trips through exactly its wire slots`() {
        val plaintext = "the bytes that will sit in object storage".toByteArray()
        val sealed = Sealing.seal(plaintext, MEDIA_DOMAIN)

        assertEquals(32, sealed.key.size)
        assertEquals(24, sealed.nonce.size)
        assertEquals(
            "the stored bytes are nonce, ciphertext, and tag",
            plaintext.size + AEAD_NONCE_LEN + AEAD_TAG_LEN,
            sealed.sealed.size,
        )

        val opened = Sealing.open(sealed.key, sealed.nonce, MEDIA_DOMAIN, sealed.sealed)
        assertArrayEquals("the object opens from its slots alone", plaintext, opened)
    }

    @Test
    fun `every seal mints a fresh key and a fresh nonce`() {
        val plaintext = "sealed twice, on purpose".toByteArray()
        val first = Sealing.seal(plaintext, MEDIA_DOMAIN)
        val second = Sealing.seal(plaintext, MEDIA_DOMAIN)
        assertTrue("two objects must never share a key", !first.key.contentEquals(second.key))
        assertTrue("two objects must never share a nonce", !first.nonce.contentEquals(second.nonce))
        assertTrue(
            "two seals of one plaintext must differ, or the RNG is not being used",
            !first.sealed.contentEquals(second.sealed),
        )
    }

    @Test
    fun `an empty plaintext still seals and opens`() {
        // Real callers never upload zero bytes (the server refuses the size), but the module's
        // contract is not "except empty": the tag alone must authenticate the object.
        val sealed = Sealing.seal(ByteArray(0), MEDIA_DOMAIN)
        assertEquals("a sealed empty object is nonce and tag and nothing else", AEAD_NONCE_LEN + AEAD_TAG_LEN, sealed.sealed.size)
        assertEquals(0, Sealing.open(sealed.key, sealed.nonce, MEDIA_DOMAIN, sealed.sealed).size)
    }

    @Test
    fun `the domain label is authenticated, not merely accepted`() {
        val plaintext = "halo dunia".toByteArray()
        val sealed = Sealing.seal(plaintext, MEDIA_DOMAIN)
        throwsKind(CryptoErrorKind.DecryptionFailed, {
            Sealing.open(sealed.key, sealed.nonce, VOICE_DOMAIN, sealed.sealed)
        }, "a media blob must not open as a voice note")
    }

    @Test
    fun `a wrong key, spliced slots, and edited bytes are one refusal`() {
        val plaintext = "the one object this message references".toByteArray()
        val sealed = Sealing.seal(plaintext, MEDIA_DOMAIN)
        val other = Sealing.seal(plaintext, MEDIA_DOMAIN)

        throwsKind(CryptoErrorKind.DecryptionFailed, {
            Sealing.open(other.key, sealed.nonce, MEDIA_DOMAIN, sealed.sealed)
        }, "another object's key must not open this object")
        throwsKind(CryptoErrorKind.DecryptionFailed, {
            Sealing.open(sealed.key, other.nonce, MEDIA_DOMAIN, sealed.sealed)
        }, "another object's nonce slot must not open this object's bytes")

        val edited = sealed.sealed.copyOf()
        val last = edited.size - 1
        edited[last] = (edited[last].toInt() xor 0x01).toByte()
        throwsKind(CryptoErrorKind.DecryptionFailed, {
            Sealing.open(sealed.key, sealed.nonce, MEDIA_DOMAIN, edited)
        }, "a flipped tag bit must not open")
    }

    @Test
    fun `wrong-width slots are refused before any decryption is attempted`() {
        val sealed = Sealing.seal("x".toByteArray(), MEDIA_DOMAIN)
        throwsKind(CryptoErrorKind.BadLength, {
            Sealing.open(ByteArray(AEAD_KEY_LEN - 1), sealed.nonce, MEDIA_DOMAIN, sealed.sealed)
        }, "a 31-byte key slot is a shape error, not a forgery")
        throwsKind(CryptoErrorKind.BadLength, {
            Sealing.open(sealed.key, ByteArray(AEAD_NONCE_LEN - 1), MEDIA_DOMAIN, sealed.sealed)
        }, "a 23-byte nonce slot is a shape error, not a forgery")
        throwsKind(CryptoErrorKind.BadLength, {
            Sealing.open(sealed.key, sealed.nonce, MEDIA_DOMAIN, ByteArray(AEAD_NONCE_LEN - 1))
        }, "stored bytes shorter than a nonce never carried a body at all")
    }
}
