//! Runs the account conformance vectors in `shared/protocol/vectors/crypto`.
//!
//! Four files are generated by an independent Python implementation
//! (`tools/vectors/generate_account_vectors.py`, written from the HKDF, BIP-32,
//! EIP-55, RLP and EIP-712 specifications with their own published vectors —
//! and one real Avalanche C-Chain transaction — as self-checks): a failure
//! there means this crate disagrees with the standard or the chain, not just
//! with a sibling port.
//!
//! Two are rust-reference (written by `examples/write_reference_vectors.rs`):
//! ML-DSA-65 has no script-reproducible published vector set, and the
//! container's bytes are the house composition. Those files do not prove the
//! crate right — the crate generated them — they prove the *ports* right, by
//! holding TypeScript and Kotlin to this implementation byte for byte. The
//! distinction is recorded in each file and re-asserted here, because a test
//! that silently trusts its own output as truth is worse than no test.

use std::path::PathBuf;

use migo_account::container::{open_container, seal_container_with, ContainerParams};
use migo_account::evm::EvmWallet;
use migo_account::identity::{
    verify_identity, DeviceCredential, IdentityKey, CONTEXT_LOGIN, CONTEXT_LOGIN_DEVICE,
    CONTEXT_ROTATE, PUBLIC_KEY_LEN, SIGNATURE_LEN,
};
use migo_account::root::{
    founding_device_e2ee_seeds, MigoRoot, DOMAIN_BACKUP, DOMAIN_E2EE, DOMAIN_EVM, DOMAIN_IDENTITY,
};
use migo_account::{
    eip712_digest, eip712_encode_type, eip712_hash_struct, eip712_type_hash, parse_address,
    recover_sender, rlp_decode, Eip1559Tx, Eip712Domain, Eip712Value, Rlp,
};
use serde_json::Value;

// --- loading ----------------------------------------------------------------

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../shared/protocol/vectors/crypto")
        .canonicalize()
        .expect("shared/protocol/vectors/crypto must exist; run make vectors")
}

fn load(file: &str) -> (Value, String) {
    let path = vectors_dir().join(file);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    let parsed = serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
    (parsed, path.display().to_string())
}

/// Returns a section as a non-empty array: a suite that runs zero cases
/// reports the strongest guarantee in the codebase and checks nothing.
fn cases<'a>(file: &'a Value, path: &str) -> &'a Vec<Value> {
    let array = file
        .get("cases")
        .unwrap_or_else(|| panic!("{path} has no `cases` section"))
        .as_array()
        .unwrap_or_else(|| panic!("{path} `cases` is not an array"));
    assert!(!array.is_empty(), "{path} `cases` is empty");
    array
}

fn unhex(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "hex strings in the vectors are even-length"
    );
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("valid hex in vectors"))
        .collect()
}

// --- the domains (independent-python) ---------------------------------------

#[test]
fn domain_seeds_match_the_independent_python_generator() {
    let (file, path) = load("account-domains.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let label = case["label"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} {name}: no label"));
        let expected = unhex(case["seed"].as_str().expect("seed hex"));
        let actual = root.domain_seed(label.as_bytes());
        assert_eq!(
            actual.as_slice(),
            expected.as_slice(),
            "{path} {name}: domain seed disagrees with the independent implementation"
        );
    }
}

#[test]
fn founding_device_e2ee_seeds_match_the_independent_python_generator() {
    let (file, path) = load("account-domains.json");
    let mut checked = 0;
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let Some(signing) = case["e2ee_signing_seed"].as_str() else {
            continue;
        };
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let exchange = case["e2ee_exchange_seed"]
            .as_str()
            .expect("exchange hex beside signing");
        let (actual_signing, actual_exchange) = founding_device_e2ee_seeds(&root);
        assert_eq!(hex(&actual_signing), signing, "{path} {name}: signing seed");
        assert_eq!(
            hex(&actual_exchange),
            exchange,
            "{path} {name}: exchange seed"
        );
        checked += 1;
    }
    assert!(checked > 0, "{path}: no e2ee sub-seed cases found");
}

#[test]
fn the_e2ee_domain_seed_is_covered_as_a_plain_domain() {
    // The E2EE domain seed itself is one HKDF expansion, so it appears in the
    // domain cases like any other label; this test just guards against a
    // future generator change that drops it silently.
    let (file, path) = load("account-domains.json");
    let labels: Vec<&str> = cases(&file, &path)
        .iter()
        .filter_map(|c| c["label"].as_str())
        .collect();
    for label in [DOMAIN_IDENTITY, DOMAIN_EVM, DOMAIN_E2EE, DOMAIN_BACKUP] {
        let label_string = String::from_utf8(label.to_vec()).expect("domain labels are ascii");
        assert!(
            labels.contains(&label_string.as_str()),
            "{path} is missing the {label:?} domain — every live domain must be pinned"
        );
    }
}

// --- the EVM wallets (independent-python) -----------------------------------

#[test]
fn evm_wallets_match_the_independent_python_generator() {
    let (file, path) = load("account-evm.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let index = case["index"].as_u64().expect("index") as u32;
        let wallet = EvmWallet::from_root(&root, index)
            .unwrap_or_else(|e| panic!("{path} {name}: derivation failed: {e:?}"));

        let expected_address = case["address"].as_str().expect("address hex");
        assert_eq!(
            hex(wallet.address()),
            expected_address.to_lowercase(),
            "{path} {name}: address disagrees with the independent implementation"
        );
        // The checksum is display material with its own failure mode (a
        // nibble-indexing bug upper-cases the wrong characters), so it is
        // pinned separately, in the EIP-55 canonical casing.
        let expected_checksum = case["address_checksummed"]
            .as_str()
            .expect("checksummed address");
        assert_eq!(
            wallet.address_checksummed(),
            expected_checksum,
            "{path} {name}: EIP-55 checksum disagrees"
        );
    }
}

// --- ML-DSA (rust-reference) -------------------------------------------------

#[test]
fn mldsa_keys_and_signatures_match_the_reference_vectors() {
    let (file, path) = load("account-mldsa.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        assert_eq!(
            case["provenance"].as_str(),
            Some("rust-reference"),
            "{path} {name}: unexpected provenance — this test consumes rust-reference files"
        );

        let seed = unhex(case["seed"].as_str().expect("seed hex"));
        let public_key = unhex(case["public_key"].as_str().expect("public key hex"));
        let payload = unhex(case["payload"].as_str().expect("payload hex"));
        let signature = unhex(case["signature"].as_str().expect("signature hex"));
        let context = case["context"].as_str().expect("context string");
        assert_eq!(
            public_key.len(),
            PUBLIC_KEY_LEN,
            "{path} {name}: public key length"
        );
        assert_eq!(
            signature.len(),
            SIGNATURE_LEN,
            "{path} {name}: signature length"
        );

        // The key under test is whichever kind its context says it is: the
        // context is the purpose, and the purpose picks both the key type and
        // the signing method. Signing the device case with the identity's
        // login context is exactly the cross-purpose confusion the contexts
        // exist to prevent, so the routing here is deliberately explicit.
        let context_bytes = context.as_bytes();
        let (derived_public, derived_signature) = if context_bytes == CONTEXT_LOGIN {
            let identity = IdentityKey::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = identity
                .sign_login(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (identity.public_key(), sig)
        } else if context_bytes == CONTEXT_ROTATE {
            let identity = IdentityKey::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = identity
                .sign_rotate(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (identity.public_key(), sig)
        } else if context_bytes == CONTEXT_LOGIN_DEVICE {
            let credential = DeviceCredential::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = credential
                .sign_login(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (credential.public_key(), sig)
        } else {
            panic!("{path} {name}: unknown context {context}")
        };

        // Byte-for-byte: deterministic signing is what makes this portable to
        // the ports, so the pinned bytes must reproduce exactly.
        assert_eq!(
            derived_public.as_slice(),
            public_key.as_slice(),
            "{path} {name}: public key does not reproduce"
        );
        assert_eq!(
            derived_signature.as_slice(),
            signature.as_slice(),
            "{path} {name}: signature bytes do not reproduce"
        );

        // And the pinned signature verifies against the pinned key under the
        // pinned context — which also proves the file is self-consistent.
        verify_identity(&public_key, &payload, context_bytes, &signature)
            .unwrap_or_else(|e| panic!("{path} {name}: the vector's own signature fails: {e:?}"));
    }
}

#[test]
fn a_device_credential_seed_reproduces_its_vector_public_key() {
    // Device credentials are reconstructed from their stored seed, never
    // derived; the vector pins that relation.
    let (file, path) = load("account-mldsa.json");
    let device_cases: Vec<&Value> = cases(&file, &path)
        .iter()
        .filter(|c| c["context"].as_str() == Some("migo-auth-device-v1"))
        .collect();
    assert!(
        !device_cases.is_empty(),
        "{path}: no device credential case"
    );
    for case in device_cases {
        let name = case["name"].as_str().expect("named case");
        let seed = unhex(case["seed"].as_str().expect("seed hex"));
        let credential = DeviceCredential::from_seed(&seed)
            .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
        assert_eq!(
            credential.public_key().as_slice(),
            unhex(case["public_key"].as_str().expect("public key hex")).as_slice(),
            "{path} {name}: device credential public key does not reproduce"
        );
    }
}

// --- the container (rust-reference) ------------------------------------------

#[test]
fn containers_reproduce_byte_for_byte_and_open() {
    let (file, path) = load("account-container.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        assert_eq!(
            case["provenance"].as_str(),
            Some("rust-reference"),
            "{path} {name}: unexpected provenance"
        );

        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let credential = case["credential"].as_str().expect("credential");
        let salt: [u8; 16] = unhex(case["salt"].as_str().expect("salt hex"))
            .try_into()
            .expect("salt is 16 bytes");
        let nonce: [u8; 24] = unhex(case["nonce"].as_str().expect("nonce hex"))
            .try_into()
            .expect("nonce is 24 bytes");
        let params = ContainerParams {
            memory_kib: case["memory_kib"].as_u64().expect("memory") as u32,
            time_cost: case["time_cost"].as_u64().expect("time") as u32,
            lanes: case["lanes"].as_u64().expect("lanes") as u32,
        };
        let created_at = case["created_at"].as_u64().expect("created_at");
        let expected = unhex(case["container"].as_str().expect("container hex"));

        // Reseating the same inputs must produce the same file: the format has
        // no hidden entropy beyond the salt and nonce, which are pinned here.
        let file_payload = migo_account::AccountFile::new(&root, created_at);
        let actual = seal_container_with(credential, &file_payload, params, &salt, &nonce)
            .unwrap_or_else(|e| panic!("{path} {name}: seal: {e:?}"));
        assert_eq!(
            actual, expected,
            "{path} {name}: container bytes do not reproduce"
        );

        // And the pinned file opens back to the same root with its credential.
        let opened = open_container(credential, &expected).unwrap_or_else(|e| {
            panic!("{path} {name}: the vector's own container fails to open: {e:?}")
        });
        assert_eq!(
            opened.root().expect("root"),
            root,
            "{path} {name}: opened root differs"
        );

        // A wrong credential is refused, identically to a tampered byte.
        assert!(open_container("wrong-credential-x", &expected).is_err());
        let mut tampered = expected.clone();
        let last = tampered.len() - 1;
        tampered[last] ^= 1;
        assert!(open_container(credential, &tampered).is_err());
    }
}

// --- the transactions (independent-python + chain-sourced) -------------------

#[test]
fn transaction_bodies_and_signing_hashes_match_the_independent_generator() {
    let (file, path) = load("account-tx.json");
    let mut signed_and_recovered = 0;
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        if case["provenance"].as_str() == Some("chain-sourced") {
            continue; // its raw is observed, not constructed; covered below
        }
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let index = case["index"].as_u64().expect("index") as u32;
        let wallet = EvmWallet::from_root(&root, index)
            .unwrap_or_else(|e| panic!("{path} {name}: derivation failed: {e:?}"));
        let tx = Eip1559Tx {
            chain_id: case["chain_id"].as_u64().expect("chain id"),
            nonce: case["nonce"].as_u64().expect("nonce"),
            max_priority_fee_per_gas: u128_field(case, "max_priority_fee_per_gas", &path, name),
            max_fee_per_gas: u128_field(case, "max_fee_per_gas", &path, name),
            gas_limit: case["gas_limit"].as_u64().expect("gas limit"),
            to: address_field(case, "recipient", &path, name),
            value: u128_field(case, "value_wei", &path, name),
            data: unhex(case["data"].as_str().expect("data hex")),
        };

        // The sender is pinned too: the wallet derived from the same root and
        // index must be the one the case names, or the derivation and the
        // transaction vectors disagree about whose transaction this is.
        let sender = case["sender"].as_str().expect("sender hex");
        assert_eq!(hex(wallet.address()), sender, "{path} {name}: sender");

        // Body and signing hash are the deterministic bytes: a port must
        // produce both before it signs, so both are pinned exactly.
        let expected_body = unhex(case["body_rlp"].as_str().expect("body rlp hex"));
        assert_eq!(tx.body_rlp(), expected_body, "{path} {name}: body RLP");
        let expected_hash = unhex(case["signing_hash"].as_str().expect("signing hash hex"));
        assert_eq!(
            tx.signing_hash().as_slice(),
            expected_hash.as_slice(),
            "{path} {name}: signing hash"
        );

        // Signature bytes are deliberately not pinned (the file says so), so
        // the proof of the signing path is round-trip: this crate signs with
        // its own nonce and the raw transaction must recover to the sender.
        let signed = tx
            .sign(&wallet)
            .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
        let recovered = recover_sender(signed.raw())
            .unwrap_or_else(|e| panic!("{path} {name}: recover own signature: {e:?}"));
        assert_eq!(
            hex(&recovered),
            sender,
            "{path} {name}: a self-made signature does not recover to the sender"
        );
        signed_and_recovered += 1;
    }
    assert!(
        signed_and_recovered > 0,
        "{path}: no constructed-transaction cases"
    );
}

#[test]
fn the_chain_sourced_transaction_recovers_to_its_observed_sender() {
    let (file, path) = load("account-tx.json");
    let case = cases(&file, &path)
        .iter()
        .find(|c| c["provenance"].as_str() == Some("chain-sourced"))
        .unwrap_or_else(|| panic!("{path}: no chain-sourced case"));
    let name = case["name"].as_str().expect("named case");
    let raw = unhex(case["raw"].as_str().expect("raw hex"));

    // The full observed pipeline: the raw must be a strict-decodable type-2
    // envelope whose signature recovers to the sender the chain attributes
    // the transaction to. A client that only agrees with itself — the nested
    // envelope mistake, or a signing hash over the wrong fields — fails here.
    let sender = recover_sender(&raw)
        .unwrap_or_else(|e| panic!("{path} {name}: real C-Chain tx failed to parse: {e:?}"));
    assert_eq!(
        hex(&sender),
        case["sender"].as_str().expect("sender hex"),
        "{path} {name}: sender recovery disagrees with the chain"
    );

    // And the decoded body must re-encode through this crate's builder: build
    // the transaction from the case's decoded fields and its body RLP must
    // equal the body as it appears inside the observed raw. This is the same
    // check a broadcast path performs in reverse.
    let items = match rlp_decode(&raw[1..]).expect("decodable envelope") {
        Rlp::List(items) => items,
        other => panic!("{path} {name}: envelope is not a list: {other:?}"),
    };
    assert_eq!(
        items.len(),
        12,
        "{path} {name}: not a 12-item type-2 envelope"
    );
    let observed_body = Rlp::List(items[..9].to_vec()).encode();
    let tx = Eip1559Tx {
        chain_id: case["chain_id"].as_u64().expect("chain id"),
        nonce: case["nonce"].as_u64().expect("nonce"),
        max_priority_fee_per_gas: u128_field(case, "max_priority_fee_per_gas", &path, name),
        max_fee_per_gas: u128_field(case, "max_fee_per_gas", &path, name),
        gas_limit: case["gas_limit"].as_u64().expect("gas limit"),
        to: address_field(case, "recipient", &path, name),
        value: u128_field(case, "value_wei", &path, name),
        data: unhex(case["data"].as_str().expect("data hex")),
    };
    assert_eq!(
        tx.body_rlp(),
        observed_body,
        "{path} {name}: this crate's body encoding disagrees with the chain's"
    );
}

// --- the typed data (independent-python, anchored on the EIP's own example) ---

/// One EIP-712 value from the recursive JSON model. A struct contributes its
/// own hashStruct — computed here with the child's type hash — as a bytes32,
/// exactly how the crate's model composes structs.
fn eip712_value(json: &Value) -> Eip712Value {
    if let Some(structure) = json.get("struct") {
        let primary = structure["primary_type"].as_str().expect("primary type");
        let referenced: Vec<&str> = structure["referenced_types"]
            .as_array()
            .expect("referenced_types array")
            .iter()
            .map(|r| r.as_str().expect("referenced declaration"))
            .collect();
        let values: Vec<Eip712Value> = structure["values"]
            .as_array()
            .expect("struct values array")
            .iter()
            .map(eip712_value)
            .collect();
        let type_hash = eip712_type_hash(primary, &referenced);
        return Eip712Value::Bytes32(eip712_hash_struct(&type_hash, &values));
    }
    let kind = json["type"].as_str().expect("value type");
    if kind == "array" {
        return Eip712Value::Array(
            json["values"]
                .as_array()
                .expect("array values")
                .iter()
                .map(eip712_value)
                .collect(),
        );
    }
    let raw = json["value"].as_str().expect("value hex or text");
    match kind {
        "address" => Eip712Value::Address(
            unhex(raw)
                .try_into()
                .unwrap_or_else(|v: Vec<u8>| panic!("address is 20 bytes, got {}", v.len())),
        ),
        "bytes32" => Eip712Value::Bytes32(
            unhex(raw)
                .try_into()
                .unwrap_or_else(|v: Vec<u8>| panic!("bytes32 is 32 bytes, got {}", v.len())),
        ),
        // JSON carries small integers as short hex; the encoding is 32 bytes.
        "uint256" => {
            let bytes = unhex(raw);
            assert!(bytes.len() <= 32, "uint256 exceeds 32 bytes");
            let mut out = [0u8; 32];
            out[32 - bytes.len()..].copy_from_slice(&bytes);
            Eip712Value::Uint256(out)
        }
        "string" => Eip712Value::String(raw.to_string()),
        "bytes" => Eip712Value::Bytes(unhex(raw)),
        other => panic!("unknown EIP-712 value type {other}"),
    }
}

/// The domain from a case, built from exactly the fields it carries — field
/// presence is part of the vector, because the separator is built from it.
fn eip712_domain(json: &Value) -> Eip712Domain {
    Eip712Domain {
        name: json.get("name").and_then(Value::as_str).map(str::to_string),
        version: json
            .get("version")
            .and_then(Value::as_str)
            .map(str::to_string),
        chain_id: json.get("chain_id").and_then(Value::as_u64),
        verifying_contract: json
            .get("verifying_contract")
            .and_then(Value::as_str)
            .map(|hex40| {
                unhex(hex40)
                    .try_into()
                    .expect("verifying_contract is 20 bytes")
            }),
        salt: json
            .get("salt")
            .and_then(Value::as_str)
            .map(|hex64| unhex(hex64).try_into().expect("salt is 32 bytes")),
    }
}

#[test]
fn eip712_digests_match_the_independent_generator() {
    let (file, path) = load("account-eip712.json");
    let mut saw_spec_example = false;
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let domain = eip712_domain(&case["domain"]);
        let message = &case["message"]["struct"];
        let primary = message["primary_type"].as_str().expect("primary type");
        let referenced: Vec<&str> = message["referenced_types"]
            .as_array()
            .expect("referenced_types array")
            .iter()
            .map(|r| r.as_str().expect("referenced declaration"))
            .collect();
        let values: Vec<Eip712Value> = message["values"]
            .as_array()
            .expect("values array")
            .iter()
            .map(eip712_value)
            .collect();

        // The encodeType string is pinned in the file for readability — it is
        // the rule most ports get wrong — so assert it, not just its hash.
        assert_eq!(
            eip712_encode_type(primary, &referenced),
            case["encode_type"].as_str().expect("encode_type"),
            "{path} {name}: encodeType"
        );

        let type_hash = eip712_type_hash(primary, &referenced);
        let struct_hash = eip712_hash_struct(&type_hash, &values);
        let separator = domain.separator();
        let digest = eip712_digest(&separator, &struct_hash);
        let expected = &case["expected"];
        assert_eq!(
            hex(&type_hash),
            expected["type_hash"].as_str().expect("type hash hex"),
            "{path} {name}: type hash"
        );
        assert_eq!(
            hex(&separator),
            expected["domain_separator"]
                .as_str()
                .expect("separator hex"),
            "{path} {name}: domain separator"
        );
        assert_eq!(
            hex(&struct_hash),
            expected["struct_hash"].as_str().expect("struct hash hex"),
            "{path} {name}: hashStruct"
        );
        assert_eq!(
            hex(&digest),
            expected["digest"].as_str().expect("digest hex"),
            "{path} {name}: digest"
        );
        if case["provenance"].as_str() == Some("eip712-spec-example") {
            // The spec-example case's expected values are the EIP's published
            // ones — matching them is matching the specification, not just
            // this repository's Python half.
            saw_spec_example = true;
        }
    }
    assert!(
        saw_spec_example,
        "{path}: the EIP-712 worked example is missing — the file's anchor to the specification"
    );
}

// --- helpers ------------------------------------------------------------------

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// A 20-byte address field from a case, via the same parser the send flow
/// uses — so the vectors also exercise recipient parsing, not just byte
/// comparison.
fn address_field(case: &Value, key: &str, path: &str, name: &str) -> [u8; 20] {
    let text = case[key]
        .as_str()
        .unwrap_or_else(|| panic!("{path} {name}: no {key} hex"));
    parse_address(text).unwrap_or_else(|e| panic!("{path} {name}: bad {key} {text}: {e:?}"))
}

/// A u128 field from a case. `serde_json::Value` has no `as_u128`, so fee and
/// value fields — which exceed u64 in wei terms — go through `Number`.
fn u128_field(case: &Value, key: &str, path: &str, name: &str) -> u128 {
    case[key]
        .as_number()
        .and_then(serde_json::Number::as_u128)
        .unwrap_or_else(|| panic!("{path} {name}: no u128 {key}"))
}
