//! Runs the account conformance vectors in `shared/protocol/vectors/crypto`.
//!
//! Two files are generated by an independent Python implementation
//! (`tools/vectors/generate_account_vectors.py`, written from the HKDF, BIP-32
//! and EIP-55 specifications with their own published vectors as self-checks):
//! a failure there means this crate disagrees with the standard, not just with
//! a sibling port.
//!
//! Two are rust-reference (written by `examples/write_reference_vectors.rs`):
//! ML-DSA-65 has no script-reproducible published vector set, and the
//! container's bytes are the house composition. Those files do not prove the
//! crate right — the crate generated them — they prove the *ports* right, by
//! holding TypeScript and Kotlin to this implementation byte for byte. The
//! distinction is recorded in each file and re-asserted here, because a test
//! that silently trusts its own output as truth is worse than no test.

use std::path::PathBuf;

use migo_account::container::{open_container, seal_container_with, ContainerParams};
use migo_account::evm::EvmWallet;
use migo_account::identity::{
    verify_identity, DeviceCredential, IdentityKey, CONTEXT_LOGIN, CONTEXT_LOGIN_DEVICE,
    CONTEXT_ROTATE, PUBLIC_KEY_LEN, SIGNATURE_LEN,
};
use migo_account::root::{
    founding_device_e2ee_seeds, MigoRoot, DOMAIN_BACKUP, DOMAIN_E2EE, DOMAIN_EVM, DOMAIN_IDENTITY,
};
use serde_json::Value;

// --- loading ----------------------------------------------------------------

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../shared/protocol/vectors/crypto")
        .canonicalize()
        .expect("shared/protocol/vectors/crypto must exist; run make vectors")
}

fn load(file: &str) -> (Value, String) {
    let path = vectors_dir().join(file);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    let parsed = serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
    (parsed, path.display().to_string())
}

/// Returns a section as a non-empty array: a suite that runs zero cases
/// reports the strongest guarantee in the codebase and checks nothing.
fn cases<'a>(file: &'a Value, path: &str) -> &'a Vec<Value> {
    let array = file
        .get("cases")
        .unwrap_or_else(|| panic!("{path} has no `cases` section"))
        .as_array()
        .unwrap_or_else(|| panic!("{path} `cases` is not an array"));
    assert!(!array.is_empty(), "{path} `cases` is empty");
    array
}

fn unhex(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "hex strings in the vectors are even-length"
    );
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).expect("valid hex in vectors"))
        .collect()
}

// --- the domains (independent-python) ---------------------------------------

#[test]
fn domain_seeds_match_the_independent_python_generator() {
    let (file, path) = load("account-domains.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let label = case["label"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} {name}: no label"));
        let expected = unhex(case["seed"].as_str().expect("seed hex"));
        let actual = root.domain_seed(label.as_bytes());
        assert_eq!(
            actual.as_slice(),
            expected.as_slice(),
            "{path} {name}: domain seed disagrees with the independent implementation"
        );
    }
}

#[test]
fn founding_device_e2ee_seeds_match_the_independent_python_generator() {
    let (file, path) = load("account-domains.json");
    let mut checked = 0;
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let Some(signing) = case["e2ee_signing_seed"].as_str() else {
            continue;
        };
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let exchange = case["e2ee_exchange_seed"]
            .as_str()
            .expect("exchange hex beside signing");
        let (actual_signing, actual_exchange) = founding_device_e2ee_seeds(&root);
        assert_eq!(hex(&actual_signing), signing, "{path} {name}: signing seed");
        assert_eq!(
            hex(&actual_exchange),
            exchange,
            "{path} {name}: exchange seed"
        );
        checked += 1;
    }
    assert!(checked > 0, "{path}: no e2ee sub-seed cases found");
}

#[test]
fn the_e2ee_domain_seed_is_covered_as_a_plain_domain() {
    // The E2EE domain seed itself is one HKDF expansion, so it appears in the
    // domain cases like any other label; this test just guards against a
    // future generator change that drops it silently.
    let (file, path) = load("account-domains.json");
    let labels: Vec<&str> = cases(&file, &path)
        .iter()
        .filter_map(|c| c["label"].as_str())
        .collect();
    for label in [DOMAIN_IDENTITY, DOMAIN_EVM, DOMAIN_E2EE, DOMAIN_BACKUP] {
        let label_string = String::from_utf8(label.to_vec()).expect("domain labels are ascii");
        assert!(
            labels.contains(&label_string.as_str()),
            "{path} is missing the {label:?} domain — every live domain must be pinned"
        );
    }
}

// --- the EVM wallets (independent-python) -----------------------------------

#[test]
fn evm_wallets_match_the_independent_python_generator() {
    let (file, path) = load("account-evm.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let index = case["index"].as_u64().expect("index") as u32;
        let wallet = EvmWallet::from_root(&root, index)
            .unwrap_or_else(|e| panic!("{path} {name}: derivation failed: {e:?}"));

        let expected_address = case["address"].as_str().expect("address hex");
        assert_eq!(
            hex(wallet.address()),
            expected_address.to_lowercase(),
            "{path} {name}: address disagrees with the independent implementation"
        );
        // The checksum is display material with its own failure mode (a
        // nibble-indexing bug upper-cases the wrong characters), so it is
        // pinned separately, in the EIP-55 canonical casing.
        let expected_checksum = case["address_checksummed"]
            .as_str()
            .expect("checksummed address");
        assert_eq!(
            wallet.address_checksummed(),
            expected_checksum,
            "{path} {name}: EIP-55 checksum disagrees"
        );
    }
}

// --- ML-DSA (rust-reference) -------------------------------------------------

#[test]
fn mldsa_keys_and_signatures_match_the_reference_vectors() {
    let (file, path) = load("account-mldsa.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        assert_eq!(
            case["provenance"].as_str(),
            Some("rust-reference"),
            "{path} {name}: unexpected provenance — this test consumes rust-reference files"
        );

        let seed = unhex(case["seed"].as_str().expect("seed hex"));
        let public_key = unhex(case["public_key"].as_str().expect("public key hex"));
        let payload = unhex(case["payload"].as_str().expect("payload hex"));
        let signature = unhex(case["signature"].as_str().expect("signature hex"));
        let context = case["context"].as_str().expect("context string");
        assert_eq!(
            public_key.len(),
            PUBLIC_KEY_LEN,
            "{path} {name}: public key length"
        );
        assert_eq!(
            signature.len(),
            SIGNATURE_LEN,
            "{path} {name}: signature length"
        );

        // The key under test is whichever kind its context says it is: the
        // context is the purpose, and the purpose picks both the key type and
        // the signing method. Signing the device case with the identity's
        // login context is exactly the cross-purpose confusion the contexts
        // exist to prevent, so the routing here is deliberately explicit.
        let context_bytes = context.as_bytes();
        let (derived_public, derived_signature) = if context_bytes == CONTEXT_LOGIN {
            let identity = IdentityKey::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = identity
                .sign_login(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (identity.public_key(), sig)
        } else if context_bytes == CONTEXT_ROTATE {
            let identity = IdentityKey::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = identity
                .sign_rotate(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (identity.public_key(), sig)
        } else if context_bytes == CONTEXT_LOGIN_DEVICE {
            let credential = DeviceCredential::from_seed(&seed)
                .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
            let sig = credential
                .sign_login(&payload)
                .unwrap_or_else(|e| panic!("{path} {name}: sign: {e:?}"));
            (credential.public_key(), sig)
        } else {
            panic!("{path} {name}: unknown context {context}")
        };

        // Byte-for-byte: deterministic signing is what makes this portable to
        // the ports, so the pinned bytes must reproduce exactly.
        assert_eq!(
            derived_public.as_slice(),
            public_key.as_slice(),
            "{path} {name}: public key does not reproduce"
        );
        assert_eq!(
            derived_signature.as_slice(),
            signature.as_slice(),
            "{path} {name}: signature bytes do not reproduce"
        );

        // And the pinned signature verifies against the pinned key under the
        // pinned context — which also proves the file is self-consistent.
        verify_identity(&public_key, &payload, context_bytes, &signature)
            .unwrap_or_else(|e| panic!("{path} {name}: the vector's own signature fails: {e:?}"));
    }
}

#[test]
fn a_device_credential_seed_reproduces_its_vector_public_key() {
    // Device credentials are reconstructed from their stored seed, never
    // derived; the vector pins that relation.
    let (file, path) = load("account-mldsa.json");
    let device_cases: Vec<&Value> = cases(&file, &path)
        .iter()
        .filter(|c| c["context"].as_str() == Some("migo-auth-device-v1"))
        .collect();
    assert!(
        !device_cases.is_empty(),
        "{path}: no device credential case"
    );
    for case in device_cases {
        let name = case["name"].as_str().expect("named case");
        let seed = unhex(case["seed"].as_str().expect("seed hex"));
        let credential = DeviceCredential::from_seed(&seed)
            .unwrap_or_else(|e| panic!("{path} {name}: bad seed: {e:?}"));
        assert_eq!(
            credential.public_key().as_slice(),
            unhex(case["public_key"].as_str().expect("public key hex")).as_slice(),
            "{path} {name}: device credential public key does not reproduce"
        );
    }
}

// --- the container (rust-reference) ------------------------------------------

#[test]
fn containers_reproduce_byte_for_byte_and_open() {
    let (file, path) = load("account-container.json");
    for case in cases(&file, &path) {
        let name = case["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{path} case without a name"));
        assert_eq!(
            case["provenance"].as_str(),
            Some("rust-reference"),
            "{path} {name}: unexpected provenance"
        );

        let root = MigoRoot::from_bytes(&unhex(case["root"].as_str().expect("root hex")))
            .unwrap_or_else(|e| panic!("{path} {name}: bad root: {e:?}"));
        let credential = case["credential"].as_str().expect("credential");
        let salt: [u8; 16] = unhex(case["salt"].as_str().expect("salt hex"))
            .try_into()
            .expect("salt is 16 bytes");
        let nonce: [u8; 24] = unhex(case["nonce"].as_str().expect("nonce hex"))
            .try_into()
            .expect("nonce is 24 bytes");
        let params = ContainerParams {
            memory_kib: case["memory_kib"].as_u64().expect("memory") as u32,
            time_cost: case["time_cost"].as_u64().expect("time") as u32,
            lanes: case["lanes"].as_u64().expect("lanes") as u32,
        };
        let created_at = case["created_at"].as_u64().expect("created_at");
        let expected = unhex(case["container"].as_str().expect("container hex"));

        // Reseating the same inputs must produce the same file: the format has
        // no hidden entropy beyond the salt and nonce, which are pinned here.
        let file_payload = migo_account::AccountFile::new(&root, created_at);
        let actual = seal_container_with(credential, &file_payload, params, &salt, &nonce)
            .unwrap_or_else(|e| panic!("{path} {name}: seal: {e:?}"));
        assert_eq!(
            actual, expected,
            "{path} {name}: container bytes do not reproduce"
        );

        // And the pinned file opens back to the same root with its credential.
        let opened = open_container(credential, &expected).unwrap_or_else(|e| {
            panic!("{path} {name}: the vector's own container fails to open: {e:?}")
        });
        assert_eq!(
            opened.root().expect("root"),
            root,
            "{path} {name}: opened root differs"
        );

        // A wrong credential is refused, identically to a tampered byte.
        assert!(open_container("wrong-credential-x", &expected).is_err());
        let mut tampered = expected.clone();
        let last = tampered.len() - 1;
        tampered[last] ^= 1;
        assert!(open_container(credential, &tampered).is_err());
    }
}

// --- helpers ------------------------------------------------------------------

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
