// @generated by tools/protocol-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: shared/protocol/schema (MWP/1).
// Regenerate with: make protocol
/* eslint-disable */
import type { Id } from '@migo/wire';
import { Reader, Writer } from '@migo/wire';

export const PROTOCOL_NAME = 'MWP' as const;
export const PROTOCOL_VERSION = 1 as const;
export const EPOCH_MS = 1704067200000 as const;

export const LIMITS = {
  MAX_FRAME_BYTES: 262144,
  MAX_STRING_BYTES: 65536,
  MAX_BYTES_LEN: 131072,
  MAX_LIST_ITEMS: 4096,
  MAX_MAP_ITEMS: 1024,
  MAX_NESTING_DEPTH: 16,
  MAX_BATCH_ITEMS: 256,
  MAX_VARINT_BYTES: 10,
  COMPRESS_MIN_BYTES: 512,
  COMPRESS_MIN_GAIN_PERCENT: 10,
  MAX_SUBSCRIPTIONS: 512,
  DEFAULT_HEARTBEAT_MS: 30000,
  SESSION_QUEUE_CAPACITY: 256,
  LAGGING_DEADLINE_MS: 5000,
  BATCH_LINGER_MS: 15,
  RESUME_BUFFER_FRAMES: 512,
  RESUME_WINDOW_MS: 120000,
} as const;

/** Frame flag bits. */
export const FLAG = {
  /** Payload is deflate-raw compressed */
  COMPRESSED: 1,
  /** 16-byte trace id + 8-byte span id precede the payload */
  TRACED: 2,
  /** Payload is varint count then count x (varint len, sub-frame) */
  BATCH: 4,
  /** Payload is Error instead of the opcode response type */
  ERROR: 8,
  /** Receiver must acknowledge by cumulative watermark */
  ACK_REQUIRED: 16,
  /** varint index, varint total follow; payload is a slice */
  FRAGMENT: 32,
  /** Must be zero in MWP/1 */
  RESERVED_6: 64,
  /** A second flags byte follows (reserved for MWP/2) */
  FLAGS_EXT: 128,
} as const;
export const RESERVED_FLAG_MASK = FLAG.RESERVED_6 | FLAG.FLAGS_EXT;

/** Negotiable feature bits (64-bit, hence bigint). */
export const FEATURE = {
  /** deflate-raw frame compression */
  COMPRESSION: 1n << 0n,
  /** BATCH frames */
  BATCHING: 1n << 1n,
  /** X3DH + Double Ratchet private messaging */
  E2E_V1: 1n << 2n,
  /** Sender-key group encryption */
  GROUP_E2E_V1: 1n << 3n,
  /** Presence events */
  PRESENCE: 1n << 4n,
  /** Typing indicators */
  TYPING: 1n << 5n,
  /** Public and Managed rooms */
  ROOMS: 1n << 6n,
  /** Signed-URL media upload */
  MEDIA_UPLOAD: 1n << 7n,
  /** Server-authoritative mini games */
  GAMES: 1n << 8n,
  /** Bot actors in rooms */
  BOTS: 1n << 9n,
  /** On-demand message translation */
  TRANSLATION: 1n << 10n,
  /** Voice message attachments */
  VOICE_MESSAGE: 1n << 11n,
  /** QUIC transport upgrade offer */
  QUIC: 1n << 12n,
  /** Accepts TRACED frames */
  TRACING: 1n << 13n,
  /** Session resume by frame watermark */
  RESUME: 1n << 14n,
  /** Gifts and currency events */
  ECONOMY: 1n << 15n,
} as const;
export const ALL_FEATURES = FEATURE.COMPRESSION | FEATURE.BATCHING | FEATURE.E2E_V1 | FEATURE.GROUP_E2E_V1 | FEATURE.PRESENCE | FEATURE.TYPING | FEATURE.ROOMS | FEATURE.MEDIA_UPLOAD | FEATURE.GAMES | FEATURE.BOTS | FEATURE.TRANSLATION | FEATURE.VOICE_MESSAGE | FEATURE.QUIC | FEATURE.TRACING | FEATURE.RESUME | FEATURE.ECONOMY;

/** Stable protocol error codes. */
export const CODE = {
  /** Frame version this server cannot speak */
  PROTOCOL_VERSION_UNSUPPORTED: 1000,
  MALFORMED_FRAME: 1001,
  UNKNOWN_OPCODE: 1002,
  /** Valid opcode, wrong session state */
  UNEXPECTED_OPCODE: 1003,
  FRAME_TOO_LARGE: 1004,
  UNSUPPORTED_FLAG: 1005,
  DECODE_FAILED: 1006,
  FEATURE_NOT_NEGOTIATED: 1007,
  /** Resume window expired; re-sync by cursor */
  RESUME_REQUIRED: 1008,
  /** Outbound queue stayed full past the deadline */
  SESSION_LAGGING: 1009,
  UNAUTHENTICATED: 1100,
  INVALID_CREDENTIALS: 1101,
  TOKEN_EXPIRED: 1102,
  TOKEN_INVALID: 1103,
  TOKEN_REVOKED: 1104,
  /** Session family revoked; treated as theft */
  REFRESH_REUSE_DETECTED: 1105,
  DEVICE_MISMATCH: 1106,
  MFA_REQUIRED: 1107,
  /** Sensitive operation */
  REAUTHENTICATION_REQUIRED: 1108,
  ACCOUNT_SUSPENDED: 1109,
  PERMISSION_DENIED: 1200,
  NOT_A_MEMBER: 1201,
  BANNED: 1202,
  MUTED: 1203,
  BLOCKED_BY_USER: 1204,
  PRIVACY_RESTRICTED: 1205,
  BOT_PERMISSION_MISSING: 1206,
  VALIDATION_FAILED: 1300,
  FIELD_REQUIRED: 1301,
  FIELD_TOO_LONG: 1302,
  INVALID_FORMAT: 1303,
  UNSUPPORTED_MEDIA_TYPE: 1304,
  INVALID_KEY_MATERIAL: 1305,
  USERNAME_TAKEN: 1306,
  USERNAME_RESERVED: 1307,
  WEAK_PASSWORD: 1308,
  RATE_LIMITED: 1400,
  QUOTA_EXCEEDED: 1401,
  SLOW_MODE_ACTIVE: 1402,
  TOO_MANY_SUBSCRIPTIONS: 1403,
  TOO_MANY_SESSIONS: 1404,
  UPLOAD_LIMIT_EXCEEDED: 1405,
  NOT_FOUND: 1500,
  ALREADY_EXISTS: 1501,
  CONFLICT: 1502,
  SEQUENCE_GAP: 1503,
  HISTORY_TRUNCATED: 1504,
  ROOM_FULL: 1505,
  ROOM_ARCHIVED: 1506,
  /** Peer must publish more one-time prekeys */
  PREKEYS_EXHAUSTED: 1507,
  GAME_NOT_YOUR_TURN: 1508,
  /** Same key, different payload */
  IDEMPOTENCY_MISMATCH: 1509,
  /** Not enough currency; refetch the balance */
  INSUFFICIENT_BALANCE: 1510,
  INTERNAL_ERROR: 1600,
  STORAGE_UNAVAILABLE: 1601,
  CACHE_UNAVAILABLE: 1602,
  MEDIA_UNAVAILABLE: 1603,
  OVERLOADED: 1604,
  SHUTTING_DOWN: 1605,
  /** Kill switch is engaged */
  FEATURE_DISABLED: 1606,
  TIMEOUT: 1607,
  PEER_UNREACHABLE: 1700,
  REGION_DEGRADED: 1701,
  /** Home region unreachable; no second sequencer allowed */
  ROOM_READ_ONLY_PARTITION: 1702,
  MESH_AUTH_FAILED: 1703,
  ROUTING_EPOCH_STALE: 1704,
} as const;
export type ErrorCode = (typeof CODE)[keyof typeof CODE];

export const ERROR_SYMBOLS: Record<number, string> = {
  1000: 'PROTOCOL_VERSION_UNSUPPORTED',
  1001: 'MALFORMED_FRAME',
  1002: 'UNKNOWN_OPCODE',
  1003: 'UNEXPECTED_OPCODE',
  1004: 'FRAME_TOO_LARGE',
  1005: 'UNSUPPORTED_FLAG',
  1006: 'DECODE_FAILED',
  1007: 'FEATURE_NOT_NEGOTIATED',
  1008: 'RESUME_REQUIRED',
  1009: 'SESSION_LAGGING',
  1100: 'UNAUTHENTICATED',
  1101: 'INVALID_CREDENTIALS',
  1102: 'TOKEN_EXPIRED',
  1103: 'TOKEN_INVALID',
  1104: 'TOKEN_REVOKED',
  1105: 'REFRESH_REUSE_DETECTED',
  1106: 'DEVICE_MISMATCH',
  1107: 'MFA_REQUIRED',
  1108: 'REAUTHENTICATION_REQUIRED',
  1109: 'ACCOUNT_SUSPENDED',
  1200: 'PERMISSION_DENIED',
  1201: 'NOT_A_MEMBER',
  1202: 'BANNED',
  1203: 'MUTED',
  1204: 'BLOCKED_BY_USER',
  1205: 'PRIVACY_RESTRICTED',
  1206: 'BOT_PERMISSION_MISSING',
  1300: 'VALIDATION_FAILED',
  1301: 'FIELD_REQUIRED',
  1302: 'FIELD_TOO_LONG',
  1303: 'INVALID_FORMAT',
  1304: 'UNSUPPORTED_MEDIA_TYPE',
  1305: 'INVALID_KEY_MATERIAL',
  1306: 'USERNAME_TAKEN',
  1307: 'USERNAME_RESERVED',
  1308: 'WEAK_PASSWORD',
  1400: 'RATE_LIMITED',
  1401: 'QUOTA_EXCEEDED',
  1402: 'SLOW_MODE_ACTIVE',
  1403: 'TOO_MANY_SUBSCRIPTIONS',
  1404: 'TOO_MANY_SESSIONS',
  1405: 'UPLOAD_LIMIT_EXCEEDED',
  1500: 'NOT_FOUND',
  1501: 'ALREADY_EXISTS',
  1502: 'CONFLICT',
  1503: 'SEQUENCE_GAP',
  1504: 'HISTORY_TRUNCATED',
  1505: 'ROOM_FULL',
  1506: 'ROOM_ARCHIVED',
  1507: 'PREKEYS_EXHAUSTED',
  1508: 'GAME_NOT_YOUR_TURN',
  1509: 'IDEMPOTENCY_MISMATCH',
  1510: 'INSUFFICIENT_BALANCE',
  1600: 'INTERNAL_ERROR',
  1601: 'STORAGE_UNAVAILABLE',
  1602: 'CACHE_UNAVAILABLE',
  1603: 'MEDIA_UNAVAILABLE',
  1604: 'OVERLOADED',
  1605: 'SHUTTING_DOWN',
  1606: 'FEATURE_DISABLED',
  1607: 'TIMEOUT',
  1700: 'PEER_UNREACHABLE',
  1701: 'REGION_DEGRADED',
  1702: 'ROOM_READ_ONLY_PARTITION',
  1703: 'MESH_AUTH_FAILED',
  1704: 'ROUTING_EPOCH_STALE',
};

export type ErrorClassName = 'Protocol' | 'Auth' | 'Permission' | 'Validation' | 'RateLimit' | 'State' | 'Server' | 'Federation' | 'Unknown';

const ERROR_CLASSES: ReadonlyArray<{ from: number; to: number; name: ErrorClassName; retryable: boolean; action: string }> = [
  { from: 1000, to: 1099, name: 'Protocol', retryable: false, action: 'fatal_upgrade' },
  { from: 1100, to: 1199, name: 'Auth', retryable: false, action: 'reauthenticate' },
  { from: 1200, to: 1299, name: 'Permission', retryable: false, action: 'surface_denied' },
  { from: 1300, to: 1399, name: 'Validation', retryable: false, action: 'log_bug' },
  { from: 1400, to: 1499, name: 'RateLimit', retryable: true, action: 'retry_after' },
  { from: 1500, to: 1599, name: 'State', retryable: false, action: 'reconcile' },
  { from: 1600, to: 1699, name: 'Server', retryable: true, action: 'backoff_retry' },
  { from: 1700, to: 1799, name: 'Federation', retryable: true, action: 'degraded_retry' },
];

export function errorClass(code: number): ErrorClassName {
  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.name ?? 'Unknown';
}

export function isRetryable(code: number): boolean {
  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.retryable ?? false;
}

/** What a client should do about this error, without knowing every code. */
export function clientAction(code: number): string {
  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.action ?? 'backoff_retry';
}

/** Client platform reported in HELLO */
export enum Platform {
  Unknown = 0,
  Web = 1,
  Android = 2,
  Ios = 3,
  Desktop = 4,
  Bot = 5,
  LoadTest = 6,
}

/** Negotiated in HELLO so the server stops sending what the client will not render */
export enum BandwidthMode {
  Unknown = 0,
  Auto = 1,
  Normal = 2,
  LowData = 3,
  UltraLowData = 4,
}

export enum PresenceState {
  Unknown = 0,
  Offline = 1,
  Online = 2,
  Away = 3,
  Busy = 4,
  Invisible = 5,
}

export enum MessageKind {
  Unknown = 0,
  Text = 1,
  Media = 2,
  System = 3,
  Game = 4,
  Gift = 5,
  Sticker = 6,
  Voice = 7,
  KeyExchange = 8,
}

export enum ConversationKind {
  Unknown = 0,
  Direct = 1,
  Group = 2,
  Room = 3,
}

/** What the UI is allowed to claim for this conversation */
export enum EncryptionMode {
  Unknown = 0,
  None = 1,
  Transport = 2,
  EndToEnd = 3,
}

export enum ReceiptKind {
  Unknown = 0,
  Delivered = 1,
  Read = 2,
}

export enum TypingState {
  Unknown = 0,
  Start = 1,
  Stop = 2,
}

/** Truncated tells the client to render a history boundary instead of silently missing messages */
export enum SyncStatus {
  Unknown = 0,
  Ok = 1,
  Truncated = 2,
}

/** Subscription scope */
export enum TopicKind {
  Unknown = 0,
  Conversation = 1,
  Room = 2,
  User = 3,
  Game = 4,
}

export enum RoomKind {
  Unknown = 0,
  Public = 1,
  Managed = 2,
}

/** Ordered: a numerically higher role outranks a lower one */
export enum RoomRole {
  Unknown = 0,
  Member = 1,
  Helper = 2,
  Moderator = 3,
  Admin = 4,
  Manager = 5,
  Owner = 6,
}

export enum NotificationKind {
  Unknown = 0,
  Message = 1,
  Mention = 2,
  Reply = 3,
  FriendRequest = 4,
  Gift = 5,
  LevelUp = 6,
  Achievement = 7,
  RoomInvite = 8,
  RoomAnnouncement = 9,
  Event = 10,
  GameChallenge = 11,
  VoiceNote = 12,
  MissedCall = 13,
  IncomingCall = 14,
}

export enum RelationshipKind {
  Unknown = 0,
  Friend = 1,
  PendingOutgoing = 2,
  PendingIncoming = 3,
  Follow = 4,
  Block = 5,
  Favorite = 6,
}

/** Sent in RECONNECT_HINT / close frames so the client can pick the right recovery path */
export enum CloseReason {
  Unknown = 0,
  ClientRequest = 1,
  ServerShutdown = 2,
  NodeDraining = 3,
  SessionLagging = 4,
  ResumeRequired = 5,
  AuthExpired = 6,
  Rebalance = 7,
  ProtocolViolation = 8,
}

/** Who is connecting. Used for feature gating and abuse triage, never for tracking. */
export interface ClientInfo {
  platform: Platform;
  appVersion: string;
  osVersion?: string;
  deviceModel?: string;
}

export function encodeClientInfo(w: Writer, v: ClientInfo): void {
  w.enter();
  w.u32(v.platform);
  w.str(v.appVersion);
  let present = 0;
  if (v.osVersion !== undefined) present++;
  if (v.deviceModel !== undefined) present++;
  w.u32(present);
  if (v.osVersion !== undefined) { const value = v.osVersion; w.optional(1, (w) => { w.str(value); }); }
  if (v.deviceModel !== undefined) { const value = v.deviceModel; w.optional(2, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeClientInfo(r: Reader): ClientInfo {
  r.enter();
  const platform = r.u32() as Platform;
  const appVersion = r.str();
  const out: ClientInfo = { platform, appVersion } as ClientInfo;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.osVersion = sub.str(); break;
      case 2: out.deviceModel = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Resume an existing session instead of a full re-sync. */
export interface ResumeRequest {
  sessionId: Id;
  lastFrameSeq: number;
}

export function encodeResumeRequest(w: Writer, v: ResumeRequest): void {
  w.enter();
  w.id(v.sessionId);
  w.u64(v.lastFrameSeq);
  w.u32(0);
  w.leave();
}

export function decodeResumeRequest(r: Reader): ResumeRequest {
  r.enter();
  const sessionId = r.id();
  const lastFrameSeq = r.u64();
  const out: ResumeRequest = { sessionId, lastFrameSeq } as ResumeRequest;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

/** First frame on every connection. */
export interface Hello {
  protocolVersion: number;
  client: ClientInfo;
  /** Client feature bitmask; the session uses the intersection with the server's */
  features: bigint;
  locale: string;
  bandwidthMode: BandwidthMode;
  /** Saves a round trip: authenticate inside HELLO */
  accessToken?: string;
  deviceId?: Id;
  resume?: ResumeRequest;
}

export function encodeHello(w: Writer, v: Hello): void {
  w.enter();
  w.u32(v.protocolVersion);
  encodeClientInfo(w, v.client);
  w.u64big(v.features);
  w.str(v.locale);
  w.u32(v.bandwidthMode);
  let present = 0;
  if (v.accessToken !== undefined) present++;
  if (v.deviceId !== undefined) present++;
  if (v.resume !== undefined) present++;
  w.u32(present);
  if (v.accessToken !== undefined) { const value = v.accessToken; w.optional(1, (w) => { w.str(value); }); }
  if (v.deviceId !== undefined) { const value = v.deviceId; w.optional(2, (w) => { w.id(value); }); }
  if (v.resume !== undefined) { const value = v.resume; w.optional(3, (w) => { encodeResumeRequest(w, value); }); }
  w.leave();
}

export function decodeHello(r: Reader): Hello {
  r.enter();
  const protocolVersion = r.u32();
  const client = decodeClientInfo(r);
  const features = r.u64big();
  const locale = r.str();
  const bandwidthMode = r.u32() as BandwidthMode;
  const out: Hello = { protocolVersion, client, features, locale, bandwidthMode } as Hello;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.accessToken = sub.str(); break;
      case 2: out.deviceId = sub.id(); break;
      case 3: out.resume = decodeResumeRequest(sub); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Server-dictated limits. The client must respect these, not its own constants. */
export interface Limits {
  maxFrameBytes: number;
  maxBatchItems: number;
  maxSubscriptions: number;
  heartbeatMs: number;
}

export function encodeLimits(w: Writer, v: Limits): void {
  w.enter();
  w.u32(v.maxFrameBytes);
  w.u32(v.maxBatchItems);
  w.u32(v.maxSubscriptions);
  w.u32(v.heartbeatMs);
  w.u32(0);
  w.leave();
}

export function decodeLimits(r: Reader): Limits {
  r.enter();
  const maxFrameBytes = r.u32();
  const maxBatchItems = r.u32();
  const maxSubscriptions = r.u32();
  const heartbeatMs = r.u32();
  const out: Limits = { maxFrameBytes, maxBatchItems, maxSubscriptions, heartbeatMs } as Limits;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface NodeInfo {
  nodeId: string;
  region: string;
  country: string;
}

export function encodeNodeInfo(w: Writer, v: NodeInfo): void {
  w.enter();
  w.str(v.nodeId);
  w.str(v.region);
  w.str(v.country);
  w.u32(0);
  w.leave();
}

export function decodeNodeInfo(r: Reader): NodeInfo {
  r.enter();
  const nodeId = r.str();
  const region = r.str();
  const country = r.str();
  const out: NodeInfo = { nodeId, region, country } as NodeInfo;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface Welcome {
  sessionId: Id;
  node: NodeInfo;
  features: bigint;
  serverTime: number;
  limits: Limits;
  resumed?: boolean;
  resumeFromSeq?: number;
  /** Present when HELLO carried a valid access token */
  authenticatedUser?: Id;
}

export function encodeWelcome(w: Writer, v: Welcome): void {
  w.enter();
  w.id(v.sessionId);
  encodeNodeInfo(w, v.node);
  w.u64big(v.features);
  w.timestamp(v.serverTime);
  encodeLimits(w, v.limits);
  let present = 0;
  if (v.resumed !== undefined) present++;
  if (v.resumeFromSeq !== undefined) present++;
  if (v.authenticatedUser !== undefined) present++;
  w.u32(present);
  if (v.resumed !== undefined) { const value = v.resumed; w.optional(1, (w) => { w.bool(value); }); }
  if (v.resumeFromSeq !== undefined) { const value = v.resumeFromSeq; w.optional(2, (w) => { w.u64(value); }); }
  if (v.authenticatedUser !== undefined) { const value = v.authenticatedUser; w.optional(3, (w) => { w.id(value); }); }
  w.leave();
}

export function decodeWelcome(r: Reader): Welcome {
  r.enter();
  const sessionId = r.id();
  const node = decodeNodeInfo(r);
  const features = r.u64big();
  const serverTime = r.timestamp();
  const limits = decodeLimits(r);
  const out: Welcome = { sessionId, node, features, serverTime, limits } as Welcome;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.resumed = sub.bool(); break;
      case 2: out.resumeFromSeq = sub.u64(); break;
      case 3: out.authenticatedUser = sub.id(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface Authenticate {
  accessToken: string;
  deviceId: Id;
}

export function encodeAuthenticate(w: Writer, v: Authenticate): void {
  w.enter();
  w.str(v.accessToken);
  w.id(v.deviceId);
  w.u32(0);
  w.leave();
}

export function decodeAuthenticate(r: Reader): Authenticate {
  r.enter();
  const accessToken = r.str();
  const deviceId = r.id();
  const out: Authenticate = { accessToken, deviceId } as Authenticate;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface UserProfile {
  userId: Id;
  /** MGO-XXXXXXXX, immutable, shareable */
  publicId: string;
  username: string;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  country?: string;
  language?: string;
  level?: number;
  presence?: PresenceState;
  badges?: string[];
  verified?: boolean;
  customStatus?: string;
}

export function encodeUserProfile(w: Writer, v: UserProfile): void {
  w.enter();
  w.id(v.userId);
  w.str(v.publicId);
  w.str(v.username);
  w.str(v.displayName);
  let present = 0;
  if (v.avatarUrl !== undefined) present++;
  if (v.bio !== undefined) present++;
  if (v.country !== undefined) present++;
  if (v.language !== undefined) present++;
  if (v.level !== undefined) present++;
  if (v.presence !== undefined) present++;
  if (v.badges !== undefined) present++;
  if (v.verified !== undefined) present++;
  if (v.customStatus !== undefined) present++;
  w.u32(present);
  if (v.avatarUrl !== undefined) { const value = v.avatarUrl; w.optional(1, (w) => { w.str(value); }); }
  if (v.bio !== undefined) { const value = v.bio; w.optional(2, (w) => { w.str(value); }); }
  if (v.country !== undefined) { const value = v.country; w.optional(3, (w) => { w.str(value); }); }
  if (v.language !== undefined) { const value = v.language; w.optional(4, (w) => { w.str(value); }); }
  if (v.level !== undefined) { const value = v.level; w.optional(5, (w) => { w.u32(value); }); }
  if (v.presence !== undefined) { const value = v.presence; w.optional(6, (w) => { w.u32(value); }); }
  if (v.badges !== undefined) { const value = v.badges; w.optional(7, (w) => { { w.listLen(value.length); for (const item of value) { w.str(item); } } }); }
  if (v.verified !== undefined) { const value = v.verified; w.optional(8, (w) => { w.bool(value); }); }
  if (v.customStatus !== undefined) { const value = v.customStatus; w.optional(9, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeUserProfile(r: Reader): UserProfile {
  r.enter();
  const userId = r.id();
  const publicId = r.str();
  const username = r.str();
  const displayName = r.str();
  const out: UserProfile = { userId, publicId, username, displayName } as UserProfile;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.avatarUrl = sub.str(); break;
      case 2: out.bio = sub.str(); break;
      case 3: out.country = sub.str(); break;
      case 4: out.language = sub.str(); break;
      case 5: out.level = sub.u32(); break;
      case 6: out.presence = sub.u32() as PresenceState; break;
      case 7: out.badges = ((): string[] => { const n = sub.listLen(); const v: string[] = []; for (let i = 0; i < n; i++) v.push(sub.str()); return v; })(); break;
      case 8: out.verified = sub.bool(); break;
      case 9: out.customStatus = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface Authenticated {
  userId: Id;
  deviceId: Id;
  /** Capability bitmask for this session */
  capabilities: bigint;
  profile?: UserProfile;
}

export function encodeAuthenticated(w: Writer, v: Authenticated): void {
  w.enter();
  w.id(v.userId);
  w.id(v.deviceId);
  w.u64big(v.capabilities);
  let present = 0;
  if (v.profile !== undefined) present++;
  w.u32(present);
  if (v.profile !== undefined) { const value = v.profile; w.optional(1, (w) => { encodeUserProfile(w, value); }); }
  w.leave();
}

export function decodeAuthenticated(r: Reader): Authenticated {
  r.enter();
  const userId = r.id();
  const deviceId = r.id();
  const capabilities = r.u64big();
  const out: Authenticated = { userId, deviceId, capabilities } as Authenticated;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.profile = decodeUserProfile(sub); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Carried with the ERROR flag on any opcode, or standalone. */
export interface Error {
  code: number;
  /** Stable machine-readable symbol; clients localise from this, never from message */
  symbol: string;
  /** Developer-facing detail. Never shown verbatim to users */
  message?: string;
  retryAfterMs?: number;
  /** Offending field for validation errors */
  field?: string;
}

export function encodeError(w: Writer, v: Error): void {
  w.enter();
  w.u32(v.code);
  w.str(v.symbol);
  let present = 0;
  if (v.message !== undefined) present++;
  if (v.retryAfterMs !== undefined) present++;
  if (v.field !== undefined) present++;
  w.u32(present);
  if (v.message !== undefined) { const value = v.message; w.optional(1, (w) => { w.str(value); }); }
  if (v.retryAfterMs !== undefined) { const value = v.retryAfterMs; w.optional(2, (w) => { w.u32(value); }); }
  if (v.field !== undefined) { const value = v.field; w.optional(3, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeError(r: Reader): Error {
  r.enter();
  const code = r.u32();
  const symbol = r.str();
  const out: Error = { code, symbol } as Error;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.message = sub.str(); break;
      case 2: out.retryAfterMs = sub.u32(); break;
      case 3: out.field = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface Acknowledged {
  ok: boolean;
}

export function encodeAcknowledged(w: Writer, v: Acknowledged): void {
  w.enter();
  w.bool(v.ok);
  w.u32(0);
  w.leave();
}

export function decodeAcknowledged(r: Reader): Acknowledged {
  r.enter();
  const ok = r.bool();
  const out: Acknowledged = { ok } as Acknowledged;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface Ping {
  clientTime: number;
}

export function encodePing(w: Writer, v: Ping): void {
  w.enter();
  w.timestamp(v.clientTime);
  w.u32(0);
  w.leave();
}

export function decodePing(r: Reader): Ping {
  r.enter();
  const clientTime = r.timestamp();
  const out: Ping = { clientTime } as Ping;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface Pong {
  /** Echoed so the client can compute RTT without keeping state */
  clientTime: number;
  serverTime: number;
}

export function encodePong(w: Writer, v: Pong): void {
  w.enter();
  w.timestamp(v.clientTime);
  w.timestamp(v.serverTime);
  w.u32(0);
  w.leave();
}

export function decodePong(r: Reader): Pong {
  r.enter();
  const clientTime = r.timestamp();
  const serverTime = r.timestamp();
  const out: Pong = { clientTime, serverTime } as Pong;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

/** Cumulative watermark. One ACK retires every held frame at or below it. */
export interface Ack {
  frameSeq: number;
}

export function encodeAck(w: Writer, v: Ack): void {
  w.enter();
  w.u64(v.frameSeq);
  w.u32(0);
  w.leave();
}

export function decodeAck(r: Reader): Ack {
  r.enter();
  const frameSeq = r.u64();
  const out: Ack = { frameSeq } as Ack;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

/** Planned drain. after_ms is randomised per session to avoid a thundering herd. */
export interface ReconnectHint {
  reason: CloseReason;
  afterMs: number;
  endpoint?: string;
}

export function encodeReconnectHint(w: Writer, v: ReconnectHint): void {
  w.enter();
  w.u32(v.reason);
  w.u32(v.afterMs);
  let present = 0;
  if (v.endpoint !== undefined) present++;
  w.u32(present);
  if (v.endpoint !== undefined) { const value = v.endpoint; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeReconnectHint(r: Reader): ReconnectHint {
  r.enter();
  const reason = r.u32() as CloseReason;
  const afterMs = r.u32();
  const out: ReconnectHint = { reason, afterMs } as ReconnectHint;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.endpoint = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface Topic {
  kind: TopicKind;
  id: Id;
}

export function encodeTopic(w: Writer, v: Topic): void {
  w.enter();
  w.u32(v.kind);
  w.id(v.id);
  w.u32(0);
  w.leave();
}

export function decodeTopic(r: Reader): Topic {
  r.enter();
  const kind = r.u32() as TopicKind;
  const id = r.id();
  const out: Topic = { kind, id } as Topic;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface SubscribeRequest {
  topics: Topic[];
}

export function encodeSubscribeRequest(w: Writer, v: SubscribeRequest): void {
  w.enter();
  { w.listLen(v.topics.length); for (const item of v.topics) { encodeTopic(w, item); } }
  w.u32(0);
  w.leave();
}

export function decodeSubscribeRequest(r: Reader): SubscribeRequest {
  r.enter();
  const topics = ((): Topic[] => { const n = r.listLen(); const v: Topic[] = []; for (let i = 0; i < n; i++) v.push(decodeTopic(r)); return v; })();
  const out: SubscribeRequest = { topics } as SubscribeRequest;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface SubscribeResponse {
  accepted: Topic[];
  rejected?: Topic[];
}

export function encodeSubscribeResponse(w: Writer, v: SubscribeResponse): void {
  w.enter();
  { w.listLen(v.accepted.length); for (const item of v.accepted) { encodeTopic(w, item); } }
  let present = 0;
  if (v.rejected !== undefined) present++;
  w.u32(present);
  if (v.rejected !== undefined) { const value = v.rejected; w.optional(1, (w) => { { w.listLen(value.length); for (const item of value) { encodeTopic(w, item); } } }); }
  w.leave();
}

export function decodeSubscribeResponse(r: Reader): SubscribeResponse {
  r.enter();
  const accepted = ((): Topic[] => { const n = r.listLen(); const v: Topic[] = []; for (let i = 0; i < n; i++) v.push(decodeTopic(r)); return v; })();
  const out: SubscribeResponse = { accepted } as SubscribeResponse;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.rejected = ((): Topic[] => { const n = sub.listLen(); const v: Topic[] = []; for (let i = 0; i < n; i++) v.push(decodeTopic(sub)); return v; })(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface MessageSend {
  /** Client-generated ULID. Makes retry idempotent */
  messageId: Id;
  conversationId: Id;
  kind: MessageKind;
  /** E2E ciphertext for private conversations; MSE room payload for rooms */
  envelope: Uint8Array;
  replyTo?: Id;
  /** Disappearing messages */
  expiresInMs?: number;
  senderKeyId?: number;
}

export function encodeMessageSend(w: Writer, v: MessageSend): void {
  w.enter();
  w.id(v.messageId);
  w.id(v.conversationId);
  w.u32(v.kind);
  w.bytes(v.envelope);
  let present = 0;
  if (v.replyTo !== undefined) present++;
  if (v.expiresInMs !== undefined) present++;
  if (v.senderKeyId !== undefined) present++;
  w.u32(present);
  if (v.replyTo !== undefined) { const value = v.replyTo; w.optional(1, (w) => { w.id(value); }); }
  if (v.expiresInMs !== undefined) { const value = v.expiresInMs; w.optional(2, (w) => { w.u32(value); }); }
  if (v.senderKeyId !== undefined) { const value = v.senderKeyId; w.optional(3, (w) => { w.u32(value); }); }
  w.leave();
}

export function decodeMessageSend(r: Reader): MessageSend {
  r.enter();
  const messageId = r.id();
  const conversationId = r.id();
  const kind = r.u32() as MessageKind;
  const envelope = r.bytes();
  const out: MessageSend = { messageId, conversationId, kind, envelope } as MessageSend;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.replyTo = sub.id(); break;
      case 2: out.expiresInMs = sub.u32(); break;
      case 3: out.senderKeyId = sub.u32(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface MessageAccepted {
  messageId: Id;
  conversationId: Id;
  seq: number;
  createdAt: number;
  /** True when dedup matched an earlier send. Success, not an error */
  duplicate?: boolean;
}

export function encodeMessageAccepted(w: Writer, v: MessageAccepted): void {
  w.enter();
  w.id(v.messageId);
  w.id(v.conversationId);
  w.u64(v.seq);
  w.timestamp(v.createdAt);
  let present = 0;
  if (v.duplicate !== undefined) present++;
  w.u32(present);
  if (v.duplicate !== undefined) { const value = v.duplicate; w.optional(1, (w) => { w.bool(value); }); }
  w.leave();
}

export function decodeMessageAccepted(r: Reader): MessageAccepted {
  r.enter();
  const messageId = r.id();
  const conversationId = r.id();
  const seq = r.u64();
  const createdAt = r.timestamp();
  const out: MessageAccepted = { messageId, conversationId, seq, createdAt } as MessageAccepted;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.duplicate = sub.bool(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface MessageEvent {
  messageId: Id;
  conversationId: Id;
  seq: number;
  senderId: Id;
  senderDevice: Id;
  kind: MessageKind;
  envelope: Uint8Array;
  createdAt: number;
  replyTo?: Id;
  editedAt?: number;
  /** Tombstone, so offline clients converge instead of keeping ghosts */
  deleted?: boolean;
  senderKeyId?: number;
}

export function encodeMessageEvent(w: Writer, v: MessageEvent): void {
  w.enter();
  w.id(v.messageId);
  w.id(v.conversationId);
  w.u64(v.seq);
  w.id(v.senderId);
  w.id(v.senderDevice);
  w.u32(v.kind);
  w.bytes(v.envelope);
  w.timestamp(v.createdAt);
  let present = 0;
  if (v.replyTo !== undefined) present++;
  if (v.editedAt !== undefined) present++;
  if (v.deleted !== undefined) present++;
  if (v.senderKeyId !== undefined) present++;
  w.u32(present);
  if (v.replyTo !== undefined) { const value = v.replyTo; w.optional(1, (w) => { w.id(value); }); }
  if (v.editedAt !== undefined) { const value = v.editedAt; w.optional(2, (w) => { w.timestamp(value); }); }
  if (v.deleted !== undefined) { const value = v.deleted; w.optional(3, (w) => { w.bool(value); }); }
  if (v.senderKeyId !== undefined) { const value = v.senderKeyId; w.optional(4, (w) => { w.u32(value); }); }
  w.leave();
}

export function decodeMessageEvent(r: Reader): MessageEvent {
  r.enter();
  const messageId = r.id();
  const conversationId = r.id();
  const seq = r.u64();
  const senderId = r.id();
  const senderDevice = r.id();
  const kind = r.u32() as MessageKind;
  const envelope = r.bytes();
  const createdAt = r.timestamp();
  const out: MessageEvent = { messageId, conversationId, seq, senderId, senderDevice, kind, envelope, createdAt } as MessageEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.replyTo = sub.id(); break;
      case 2: out.editedAt = sub.timestamp(); break;
      case 3: out.deleted = sub.bool(); break;
      case 4: out.senderKeyId = sub.u32(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface MessageDelete {
  messageId: Id;
  conversationId: Id;
  forEveryone: boolean;
}

export function encodeMessageDelete(w: Writer, v: MessageDelete): void {
  w.enter();
  w.id(v.messageId);
  w.id(v.conversationId);
  w.bool(v.forEveryone);
  w.u32(0);
  w.leave();
}

export function decodeMessageDelete(r: Reader): MessageDelete {
  r.enter();
  const messageId = r.id();
  const conversationId = r.id();
  const forEveryone = r.bool();
  const out: MessageDelete = { messageId, conversationId, forEveryone } as MessageDelete;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface MessageReceipt {
  conversationId: Id;
  kind: ReceiptKind;
  /** Cumulative: everything up to seq is delivered/read */
  seq: number;
  userId?: Id;
  at?: number;
}

export function encodeMessageReceipt(w: Writer, v: MessageReceipt): void {
  w.enter();
  w.id(v.conversationId);
  w.u32(v.kind);
  w.u64(v.seq);
  let present = 0;
  if (v.userId !== undefined) present++;
  if (v.at !== undefined) present++;
  w.u32(present);
  if (v.userId !== undefined) { const value = v.userId; w.optional(1, (w) => { w.id(value); }); }
  if (v.at !== undefined) { const value = v.at; w.optional(2, (w) => { w.timestamp(value); }); }
  w.leave();
}

export function decodeMessageReceipt(r: Reader): MessageReceipt {
  r.enter();
  const conversationId = r.id();
  const kind = r.u32() as ReceiptKind;
  const seq = r.u64();
  const out: MessageReceipt = { conversationId, kind, seq } as MessageReceipt;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.userId = sub.id(); break;
      case 2: out.at = sub.timestamp(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface SyncRequest {
  conversationId: Id;
  /** Highest contiguous seq the client holds */
  haveSeq: number;
  limit: number;
  /** Ranged fetch for a detected gap */
  toSeq?: number;
  /** Paging older history */
  backwards?: boolean;
}

export function encodeSyncRequest(w: Writer, v: SyncRequest): void {
  w.enter();
  w.id(v.conversationId);
  w.u64(v.haveSeq);
  w.u32(v.limit);
  let present = 0;
  if (v.toSeq !== undefined) present++;
  if (v.backwards !== undefined) present++;
  w.u32(present);
  if (v.toSeq !== undefined) { const value = v.toSeq; w.optional(1, (w) => { w.u64(value); }); }
  if (v.backwards !== undefined) { const value = v.backwards; w.optional(2, (w) => { w.bool(value); }); }
  w.leave();
}

export function decodeSyncRequest(r: Reader): SyncRequest {
  r.enter();
  const conversationId = r.id();
  const haveSeq = r.u64();
  const limit = r.u32();
  const out: SyncRequest = { conversationId, haveSeq, limit } as SyncRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.toSeq = sub.u64(); break;
      case 2: out.backwards = sub.bool(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface SyncResponse {
  conversationId: Id;
  status: SyncStatus;
  fromSeq: number;
  toSeq: number;
  more: boolean;
  messages: MessageEvent[];
}

export function encodeSyncResponse(w: Writer, v: SyncResponse): void {
  w.enter();
  w.id(v.conversationId);
  w.u32(v.status);
  w.u64(v.fromSeq);
  w.u64(v.toSeq);
  w.bool(v.more);
  { w.listLen(v.messages.length); for (const item of v.messages) { encodeMessageEvent(w, item); } }
  w.u32(0);
  w.leave();
}

export function decodeSyncResponse(r: Reader): SyncResponse {
  r.enter();
  const conversationId = r.id();
  const status = r.u32() as SyncStatus;
  const fromSeq = r.u64();
  const toSeq = r.u64();
  const more = r.bool();
  const messages = ((): MessageEvent[] => { const n = r.listLen(); const v: MessageEvent[] = []; for (let i = 0; i < n; i++) v.push(decodeMessageEvent(r)); return v; })();
  const out: SyncResponse = { conversationId, status, fromSeq, toSeq, more, messages } as SyncResponse;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface ConversationSummary {
  conversationId: Id;
  kind: ConversationKind;
  encryption: EncryptionMode;
  lastSeq: number;
  readSeq: number;
  title?: string;
  avatarUrl?: string;
  members?: Id[];
  lastMessage?: MessageEvent;
  mutedUntil?: number;
  pinned?: boolean;
  archived?: boolean;
}

export function encodeConversationSummary(w: Writer, v: ConversationSummary): void {
  w.enter();
  w.id(v.conversationId);
  w.u32(v.kind);
  w.u32(v.encryption);
  w.u64(v.lastSeq);
  w.u64(v.readSeq);
  let present = 0;
  if (v.title !== undefined) present++;
  if (v.avatarUrl !== undefined) present++;
  if (v.members !== undefined) present++;
  if (v.lastMessage !== undefined) present++;
  if (v.mutedUntil !== undefined) present++;
  if (v.pinned !== undefined) present++;
  if (v.archived !== undefined) present++;
  w.u32(present);
  if (v.title !== undefined) { const value = v.title; w.optional(1, (w) => { w.str(value); }); }
  if (v.avatarUrl !== undefined) { const value = v.avatarUrl; w.optional(2, (w) => { w.str(value); }); }
  if (v.members !== undefined) { const value = v.members; w.optional(3, (w) => { { w.listLen(value.length); for (const item of value) { w.id(item); } } }); }
  if (v.lastMessage !== undefined) { const value = v.lastMessage; w.optional(4, (w) => { encodeMessageEvent(w, value); }); }
  if (v.mutedUntil !== undefined) { const value = v.mutedUntil; w.optional(5, (w) => { w.timestamp(value); }); }
  if (v.pinned !== undefined) { const value = v.pinned; w.optional(6, (w) => { w.bool(value); }); }
  if (v.archived !== undefined) { const value = v.archived; w.optional(7, (w) => { w.bool(value); }); }
  w.leave();
}

export function decodeConversationSummary(r: Reader): ConversationSummary {
  r.enter();
  const conversationId = r.id();
  const kind = r.u32() as ConversationKind;
  const encryption = r.u32() as EncryptionMode;
  const lastSeq = r.u64();
  const readSeq = r.u64();
  const out: ConversationSummary = { conversationId, kind, encryption, lastSeq, readSeq } as ConversationSummary;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.title = sub.str(); break;
      case 2: out.avatarUrl = sub.str(); break;
      case 3: out.members = ((): Id[] => { const n = sub.listLen(); const v: Id[] = []; for (let i = 0; i < n; i++) v.push(sub.id()); return v; })(); break;
      case 4: out.lastMessage = decodeMessageEvent(sub); break;
      case 5: out.mutedUntil = sub.timestamp(); break;
      case 6: out.pinned = sub.bool(); break;
      case 7: out.archived = sub.bool(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface ConversationListRequest {
  limit: number;
  cursor?: string;
}

export function encodeConversationListRequest(w: Writer, v: ConversationListRequest): void {
  w.enter();
  w.u32(v.limit);
  let present = 0;
  if (v.cursor !== undefined) present++;
  w.u32(present);
  if (v.cursor !== undefined) { const value = v.cursor; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeConversationListRequest(r: Reader): ConversationListRequest {
  r.enter();
  const limit = r.u32();
  const out: ConversationListRequest = { limit } as ConversationListRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.cursor = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface ConversationListResponse {
  conversations: ConversationSummary[];
  nextCursor?: string;
}

export function encodeConversationListResponse(w: Writer, v: ConversationListResponse): void {
  w.enter();
  { w.listLen(v.conversations.length); for (const item of v.conversations) { encodeConversationSummary(w, item); } }
  let present = 0;
  if (v.nextCursor !== undefined) present++;
  w.u32(present);
  if (v.nextCursor !== undefined) { const value = v.nextCursor; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeConversationListResponse(r: Reader): ConversationListResponse {
  r.enter();
  const conversations = ((): ConversationSummary[] => { const n = r.listLen(); const v: ConversationSummary[] = []; for (let i = 0; i < n; i++) v.push(decodeConversationSummary(r)); return v; })();
  const out: ConversationListResponse = { conversations } as ConversationListResponse;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.nextCursor = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Direct conversations are deterministic in their member set, so creation is idempotent. */
export interface ConversationCreateRequest {
  kind: ConversationKind;
  members: Id[];
  title?: string;
}

export function encodeConversationCreateRequest(w: Writer, v: ConversationCreateRequest): void {
  w.enter();
  w.u32(v.kind);
  { w.listLen(v.members.length); for (const item of v.members) { w.id(item); } }
  let present = 0;
  if (v.title !== undefined) present++;
  w.u32(present);
  if (v.title !== undefined) { const value = v.title; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeConversationCreateRequest(r: Reader): ConversationCreateRequest {
  r.enter();
  const kind = r.u32() as ConversationKind;
  const members = ((): Id[] => { const n = r.listLen(); const v: Id[] = []; for (let i = 0; i < n; i++) v.push(r.id()); return v; })();
  const out: ConversationCreateRequest = { kind, members } as ConversationCreateRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.title = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface TypingEvent {
  conversationId: Id;
  state: TypingState;
  userId?: Id;
}

export function encodeTypingEvent(w: Writer, v: TypingEvent): void {
  w.enter();
  w.id(v.conversationId);
  w.u32(v.state);
  let present = 0;
  if (v.userId !== undefined) present++;
  w.u32(present);
  if (v.userId !== undefined) { const value = v.userId; w.optional(1, (w) => { w.id(value); }); }
  w.leave();
}

export function decodeTypingEvent(r: Reader): TypingEvent {
  r.enter();
  const conversationId = r.id();
  const state = r.u32() as TypingState;
  const out: TypingEvent = { conversationId, state } as TypingEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.userId = sub.id(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface PresenceUpdate {
  state: PresenceState;
  customStatus?: string;
}

export function encodePresenceUpdate(w: Writer, v: PresenceUpdate): void {
  w.enter();
  w.u32(v.state);
  let present = 0;
  if (v.customStatus !== undefined) present++;
  w.u32(present);
  if (v.customStatus !== undefined) { const value = v.customStatus; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodePresenceUpdate(r: Reader): PresenceUpdate {
  r.enter();
  const state = r.u32() as PresenceState;
  const out: PresenceUpdate = { state } as PresenceUpdate;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.customStatus = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface PresenceEvent {
  userId: Id;
  state: PresenceState;
  customStatus?: string;
  lastSeen?: number;
}

export function encodePresenceEvent(w: Writer, v: PresenceEvent): void {
  w.enter();
  w.id(v.userId);
  w.u32(v.state);
  let present = 0;
  if (v.customStatus !== undefined) present++;
  if (v.lastSeen !== undefined) present++;
  w.u32(present);
  if (v.customStatus !== undefined) { const value = v.customStatus; w.optional(1, (w) => { w.str(value); }); }
  if (v.lastSeen !== undefined) { const value = v.lastSeen; w.optional(2, (w) => { w.timestamp(value); }); }
  w.leave();
}

export function decodePresenceEvent(r: Reader): PresenceEvent {
  r.enter();
  const userId = r.id();
  const state = r.u32() as PresenceState;
  const out: PresenceEvent = { userId, state } as PresenceEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.customStatus = sub.str(); break;
      case 2: out.lastSeen = sub.timestamp(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface PrekeyEntry {
  keyId: number;
  publicKey: Uint8Array;
}

export function encodePrekeyEntry(w: Writer, v: PrekeyEntry): void {
  w.enter();
  w.u32(v.keyId);
  w.bytes(v.publicKey);
  w.u32(0);
  w.leave();
}

export function decodePrekeyEntry(r: Reader): PrekeyEntry {
  r.enter();
  const keyId = r.u32();
  const publicKey = r.bytes();
  const out: PrekeyEntry = { keyId, publicKey } as PrekeyEntry;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

/** Public halves only. The server never receives private key material. */
export interface KeyPublish {
  identityKey: Uint8Array;
  signedPrekeyId: number;
  signedPrekey: Uint8Array;
  signedPrekeySignature: Uint8Array;
  oneTimePrekeys: PrekeyEntry[];
}

export function encodeKeyPublish(w: Writer, v: KeyPublish): void {
  w.enter();
  w.bytes(v.identityKey);
  w.u32(v.signedPrekeyId);
  w.bytes(v.signedPrekey);
  w.bytes(v.signedPrekeySignature);
  { w.listLen(v.oneTimePrekeys.length); for (const item of v.oneTimePrekeys) { encodePrekeyEntry(w, item); } }
  w.u32(0);
  w.leave();
}

export function decodeKeyPublish(r: Reader): KeyPublish {
  r.enter();
  const identityKey = r.bytes();
  const signedPrekeyId = r.u32();
  const signedPrekey = r.bytes();
  const signedPrekeySignature = r.bytes();
  const oneTimePrekeys = ((): PrekeyEntry[] => { const n = r.listLen(); const v: PrekeyEntry[] = []; for (let i = 0; i < n; i++) v.push(decodePrekeyEntry(r)); return v; })();
  const out: KeyPublish = { identityKey, signedPrekeyId, signedPrekey, signedPrekeySignature, oneTimePrekeys } as KeyPublish;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface KeyPublishResult {
  acceptedPrekeys: number;
  /** Shown in the UI for out-of-band verification */
  identityFingerprint: string;
}

export function encodeKeyPublishResult(w: Writer, v: KeyPublishResult): void {
  w.enter();
  w.u32(v.acceptedPrekeys);
  w.str(v.identityFingerprint);
  w.u32(0);
  w.leave();
}

export function decodeKeyPublishResult(r: Reader): KeyPublishResult {
  r.enter();
  const acceptedPrekeys = r.u32();
  const identityFingerprint = r.str();
  const out: KeyPublishResult = { acceptedPrekeys, identityFingerprint } as KeyPublishResult;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface KeyBundleRequest {
  userId: Id;
  /** Omit to fetch a bundle for every device of the user */
  deviceId?: Id;
}

export function encodeKeyBundleRequest(w: Writer, v: KeyBundleRequest): void {
  w.enter();
  w.id(v.userId);
  let present = 0;
  if (v.deviceId !== undefined) present++;
  w.u32(present);
  if (v.deviceId !== undefined) { const value = v.deviceId; w.optional(1, (w) => { w.id(value); }); }
  w.leave();
}

export function decodeKeyBundleRequest(r: Reader): KeyBundleRequest {
  r.enter();
  const userId = r.id();
  const out: KeyBundleRequest = { userId } as KeyBundleRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.deviceId = sub.id(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface KeyBundle {
  userId: Id;
  deviceId: Id;
  identityKey: Uint8Array;
  signedPrekeyId: number;
  signedPrekey: Uint8Array;
  signedPrekeySignature: Uint8Array;
  oneTimePrekeyId?: number;
  oneTimePrekey?: Uint8Array;
}

export function encodeKeyBundle(w: Writer, v: KeyBundle): void {
  w.enter();
  w.id(v.userId);
  w.id(v.deviceId);
  w.bytes(v.identityKey);
  w.u32(v.signedPrekeyId);
  w.bytes(v.signedPrekey);
  w.bytes(v.signedPrekeySignature);
  let present = 0;
  if (v.oneTimePrekeyId !== undefined) present++;
  if (v.oneTimePrekey !== undefined) present++;
  w.u32(present);
  if (v.oneTimePrekeyId !== undefined) { const value = v.oneTimePrekeyId; w.optional(1, (w) => { w.u32(value); }); }
  if (v.oneTimePrekey !== undefined) { const value = v.oneTimePrekey; w.optional(2, (w) => { w.bytes(value); }); }
  w.leave();
}

export function decodeKeyBundle(r: Reader): KeyBundle {
  r.enter();
  const userId = r.id();
  const deviceId = r.id();
  const identityKey = r.bytes();
  const signedPrekeyId = r.u32();
  const signedPrekey = r.bytes();
  const signedPrekeySignature = r.bytes();
  const out: KeyBundle = { userId, deviceId, identityKey, signedPrekeyId, signedPrekey, signedPrekeySignature } as KeyBundle;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.oneTimePrekeyId = sub.u32(); break;
      case 2: out.oneTimePrekey = sub.bytes(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface KeyBundleResponse {
  bundles: KeyBundle[];
}

export function encodeKeyBundleResponse(w: Writer, v: KeyBundleResponse): void {
  w.enter();
  { w.listLen(v.bundles.length); for (const item of v.bundles) { encodeKeyBundle(w, item); } }
  w.u32(0);
  w.leave();
}

export function decodeKeyBundleResponse(r: Reader): KeyBundleResponse {
  r.enter();
  const bundles = ((): KeyBundle[] => { const n = r.listLen(); const v: KeyBundle[] = []; for (let i = 0; i < n; i++) v.push(decodeKeyBundle(r)); return v; })();
  const out: KeyBundleResponse = { bundles } as KeyBundleResponse;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface ProfileRequest {
  userIds: Id[];
}

export function encodeProfileRequest(w: Writer, v: ProfileRequest): void {
  w.enter();
  { w.listLen(v.userIds.length); for (const item of v.userIds) { w.id(item); } }
  w.u32(0);
  w.leave();
}

export function decodeProfileRequest(r: Reader): ProfileRequest {
  r.enter();
  const userIds = ((): Id[] => { const n = r.listLen(); const v: Id[] = []; for (let i = 0; i < n; i++) v.push(r.id()); return v; })();
  const out: ProfileRequest = { userIds } as ProfileRequest;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface ProfileResponse {
  profiles: UserProfile[];
}

export function encodeProfileResponse(w: Writer, v: ProfileResponse): void {
  w.enter();
  { w.listLen(v.profiles.length); for (const item of v.profiles) { encodeUserProfile(w, item); } }
  w.u32(0);
  w.leave();
}

export function decodeProfileResponse(r: Reader): ProfileResponse {
  r.enter();
  const profiles = ((): UserProfile[] => { const n = r.listLen(); const v: UserProfile[] = []; for (let i = 0; i < n; i++) v.push(decodeUserProfile(r)); return v; })();
  const out: ProfileResponse = { profiles } as ProfileResponse;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface RoomSummary {
  roomId: Id;
  publicId: string;
  kind: RoomKind;
  name: string;
  memberCount: number;
  onlineCount: number;
  topic?: string;
  description?: string;
  avatarUrl?: string;
  category?: string;
  language?: string;
  country?: string;
  verified?: boolean;
  myRole?: RoomRole;
  slowModeMs?: number;
}

export function encodeRoomSummary(w: Writer, v: RoomSummary): void {
  w.enter();
  w.id(v.roomId);
  w.str(v.publicId);
  w.u32(v.kind);
  w.str(v.name);
  w.u32(v.memberCount);
  w.u32(v.onlineCount);
  let present = 0;
  if (v.topic !== undefined) present++;
  if (v.description !== undefined) present++;
  if (v.avatarUrl !== undefined) present++;
  if (v.category !== undefined) present++;
  if (v.language !== undefined) present++;
  if (v.country !== undefined) present++;
  if (v.verified !== undefined) present++;
  if (v.myRole !== undefined) present++;
  if (v.slowModeMs !== undefined) present++;
  w.u32(present);
  if (v.topic !== undefined) { const value = v.topic; w.optional(1, (w) => { w.str(value); }); }
  if (v.description !== undefined) { const value = v.description; w.optional(2, (w) => { w.str(value); }); }
  if (v.avatarUrl !== undefined) { const value = v.avatarUrl; w.optional(3, (w) => { w.str(value); }); }
  if (v.category !== undefined) { const value = v.category; w.optional(4, (w) => { w.str(value); }); }
  if (v.language !== undefined) { const value = v.language; w.optional(5, (w) => { w.str(value); }); }
  if (v.country !== undefined) { const value = v.country; w.optional(6, (w) => { w.str(value); }); }
  if (v.verified !== undefined) { const value = v.verified; w.optional(7, (w) => { w.bool(value); }); }
  if (v.myRole !== undefined) { const value = v.myRole; w.optional(8, (w) => { w.u32(value); }); }
  if (v.slowModeMs !== undefined) { const value = v.slowModeMs; w.optional(9, (w) => { w.u32(value); }); }
  w.leave();
}

export function decodeRoomSummary(r: Reader): RoomSummary {
  r.enter();
  const roomId = r.id();
  const publicId = r.str();
  const kind = r.u32() as RoomKind;
  const name = r.str();
  const memberCount = r.u32();
  const onlineCount = r.u32();
  const out: RoomSummary = { roomId, publicId, kind, name, memberCount, onlineCount } as RoomSummary;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.topic = sub.str(); break;
      case 2: out.description = sub.str(); break;
      case 3: out.avatarUrl = sub.str(); break;
      case 4: out.category = sub.str(); break;
      case 5: out.language = sub.str(); break;
      case 6: out.country = sub.str(); break;
      case 7: out.verified = sub.bool(); break;
      case 8: out.myRole = sub.u32() as RoomRole; break;
      case 9: out.slowModeMs = sub.u32(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface RoomJoinRequest {
  roomId: Id;
  inviteCode?: string;
}

export function encodeRoomJoinRequest(w: Writer, v: RoomJoinRequest): void {
  w.enter();
  w.id(v.roomId);
  let present = 0;
  if (v.inviteCode !== undefined) present++;
  w.u32(present);
  if (v.inviteCode !== undefined) { const value = v.inviteCode; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeRoomJoinRequest(r: Reader): RoomJoinRequest {
  r.enter();
  const roomId = r.id();
  const out: RoomJoinRequest = { roomId } as RoomJoinRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.inviteCode = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface RoomJoinResponse {
  room: RoomSummary;
  conversationId: Id;
  encryption: EncryptionMode;
  lastSeq: number;
}

export function encodeRoomJoinResponse(w: Writer, v: RoomJoinResponse): void {
  w.enter();
  encodeRoomSummary(w, v.room);
  w.id(v.conversationId);
  w.u32(v.encryption);
  w.u64(v.lastSeq);
  w.u32(0);
  w.leave();
}

export function decodeRoomJoinResponse(r: Reader): RoomJoinResponse {
  r.enter();
  const room = decodeRoomSummary(r);
  const conversationId = r.id();
  const encryption = r.u32() as EncryptionMode;
  const lastSeq = r.u64();
  const out: RoomJoinResponse = { room, conversationId, encryption, lastSeq } as RoomJoinResponse;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface RoomLeaveRequest {
  roomId: Id;
}

export function encodeRoomLeaveRequest(w: Writer, v: RoomLeaveRequest): void {
  w.enter();
  w.id(v.roomId);
  w.u32(0);
  w.leave();
}

export function decodeRoomLeaveRequest(r: Reader): RoomLeaveRequest {
  r.enter();
  const roomId = r.id();
  const out: RoomLeaveRequest = { roomId } as RoomLeaveRequest;
  const optionalCount = r.u32();
  // No optional fields in this version of the struct. Each entry is length-delimited,
  // so reading it is skipping it, and a newer peer may well have sent one.
  for (let i = 0; i < optionalCount; i++) r.optional();
  r.leave();
  return out;
}

export interface RoomListRequest {
  limit: number;
  query?: string;
  category?: string;
  language?: string;
  country?: string;
  cursor?: string;
}

export function encodeRoomListRequest(w: Writer, v: RoomListRequest): void {
  w.enter();
  w.u32(v.limit);
  let present = 0;
  if (v.query !== undefined) present++;
  if (v.category !== undefined) present++;
  if (v.language !== undefined) present++;
  if (v.country !== undefined) present++;
  if (v.cursor !== undefined) present++;
  w.u32(present);
  if (v.query !== undefined) { const value = v.query; w.optional(1, (w) => { w.str(value); }); }
  if (v.category !== undefined) { const value = v.category; w.optional(2, (w) => { w.str(value); }); }
  if (v.language !== undefined) { const value = v.language; w.optional(3, (w) => { w.str(value); }); }
  if (v.country !== undefined) { const value = v.country; w.optional(4, (w) => { w.str(value); }); }
  if (v.cursor !== undefined) { const value = v.cursor; w.optional(5, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeRoomListRequest(r: Reader): RoomListRequest {
  r.enter();
  const limit = r.u32();
  const out: RoomListRequest = { limit } as RoomListRequest;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.query = sub.str(); break;
      case 2: out.category = sub.str(); break;
      case 3: out.language = sub.str(); break;
      case 4: out.country = sub.str(); break;
      case 5: out.cursor = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface RoomListResponse {
  rooms: RoomSummary[];
  nextCursor?: string;
}

export function encodeRoomListResponse(w: Writer, v: RoomListResponse): void {
  w.enter();
  { w.listLen(v.rooms.length); for (const item of v.rooms) { encodeRoomSummary(w, item); } }
  let present = 0;
  if (v.nextCursor !== undefined) present++;
  w.u32(present);
  if (v.nextCursor !== undefined) { const value = v.nextCursor; w.optional(1, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeRoomListResponse(r: Reader): RoomListResponse {
  r.enter();
  const rooms = ((): RoomSummary[] => { const n = r.listLen(); const v: RoomSummary[] = []; for (let i = 0; i < n; i++) v.push(decodeRoomSummary(r)); return v; })();
  const out: RoomListResponse = { rooms } as RoomListResponse;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.nextCursor = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface RoomMemberEvent {
  roomId: Id;
  userId: Id;
  joined: boolean;
  role?: RoomRole;
  memberCount?: number;
}

export function encodeRoomMemberEvent(w: Writer, v: RoomMemberEvent): void {
  w.enter();
  w.id(v.roomId);
  w.id(v.userId);
  w.bool(v.joined);
  let present = 0;
  if (v.role !== undefined) present++;
  if (v.memberCount !== undefined) present++;
  w.u32(present);
  if (v.role !== undefined) { const value = v.role; w.optional(1, (w) => { w.u32(value); }); }
  if (v.memberCount !== undefined) { const value = v.memberCount; w.optional(2, (w) => { w.u32(value); }); }
  w.leave();
}

export function decodeRoomMemberEvent(r: Reader): RoomMemberEvent {
  r.enter();
  const roomId = r.id();
  const userId = r.id();
  const joined = r.bool();
  const out: RoomMemberEvent = { roomId, userId, joined } as RoomMemberEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.role = sub.u32() as RoomRole; break;
      case 2: out.memberCount = sub.u32(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Coalesced room counters and metadata. Deltas only. */
export interface RoomStateEvent {
  roomId: Id;
  onlineCount?: number;
  memberCount?: number;
  topic?: string;
  slowModeMs?: number;
}

export function encodeRoomStateEvent(w: Writer, v: RoomStateEvent): void {
  w.enter();
  w.id(v.roomId);
  let present = 0;
  if (v.onlineCount !== undefined) present++;
  if (v.memberCount !== undefined) present++;
  if (v.topic !== undefined) present++;
  if (v.slowModeMs !== undefined) present++;
  w.u32(present);
  if (v.onlineCount !== undefined) { const value = v.onlineCount; w.optional(1, (w) => { w.u32(value); }); }
  if (v.memberCount !== undefined) { const value = v.memberCount; w.optional(2, (w) => { w.u32(value); }); }
  if (v.topic !== undefined) { const value = v.topic; w.optional(3, (w) => { w.str(value); }); }
  if (v.slowModeMs !== undefined) { const value = v.slowModeMs; w.optional(4, (w) => { w.u32(value); }); }
  w.leave();
}

export function decodeRoomStateEvent(r: Reader): RoomStateEvent {
  r.enter();
  const roomId = r.id();
  const out: RoomStateEvent = { roomId } as RoomStateEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.onlineCount = sub.u32(); break;
      case 2: out.memberCount = sub.u32(); break;
      case 3: out.topic = sub.str(); break;
      case 4: out.slowModeMs = sub.u32(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** Never carries private plaintext. Push payloads are generic (brief 77). */
export interface NotificationEvent {
  kind: NotificationKind;
  at: number;
  title?: string;
  body?: string;
  conversationId?: Id;
  roomId?: Id;
  actorId?: Id;
}

export function encodeNotificationEvent(w: Writer, v: NotificationEvent): void {
  w.enter();
  w.u32(v.kind);
  w.timestamp(v.at);
  let present = 0;
  if (v.title !== undefined) present++;
  if (v.body !== undefined) present++;
  if (v.conversationId !== undefined) present++;
  if (v.roomId !== undefined) present++;
  if (v.actorId !== undefined) present++;
  w.u32(present);
  if (v.title !== undefined) { const value = v.title; w.optional(1, (w) => { w.str(value); }); }
  if (v.body !== undefined) { const value = v.body; w.optional(2, (w) => { w.str(value); }); }
  if (v.conversationId !== undefined) { const value = v.conversationId; w.optional(3, (w) => { w.id(value); }); }
  if (v.roomId !== undefined) { const value = v.roomId; w.optional(4, (w) => { w.id(value); }); }
  if (v.actorId !== undefined) { const value = v.actorId; w.optional(5, (w) => { w.id(value); }); }
  w.leave();
}

export function decodeNotificationEvent(r: Reader): NotificationEvent {
  r.enter();
  const kind = r.u32() as NotificationKind;
  const at = r.timestamp();
  const out: NotificationEvent = { kind, at } as NotificationEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.title = sub.str(); break;
      case 2: out.body = sub.str(); break;
      case 3: out.conversationId = sub.id(); break;
      case 4: out.roomId = sub.id(); break;
      case 5: out.actorId = sub.id(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

/** An intent. The server decides the outcome (brief 89). */
export interface GameAction {
  gameId: Id;
  roomId: Id;
  /** Monotonic per game per player; replays are detected */
  actionId: number;
  action: string;
  args?: string[];
}

export function encodeGameAction(w: Writer, v: GameAction): void {
  w.enter();
  w.id(v.gameId);
  w.id(v.roomId);
  w.u64(v.actionId);
  w.str(v.action);
  let present = 0;
  if (v.args !== undefined) present++;
  w.u32(present);
  if (v.args !== undefined) { const value = v.args; w.optional(1, (w) => { { w.listLen(value.length); for (const item of value) { w.str(item); } } }); }
  w.leave();
}

export function decodeGameAction(r: Reader): GameAction {
  r.enter();
  const gameId = r.id();
  const roomId = r.id();
  const actionId = r.u64();
  const action = r.str();
  const out: GameAction = { gameId, roomId, actionId, action } as GameAction;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.args = ((): string[] => { const n = sub.listLen(); const v: string[] = []; for (let i = 0; i < n; i++) v.push(sub.str()); return v; })(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export interface GameEvent {
  gameId: Id;
  roomId: Id;
  stateVersion: number;
  event: string;
  /** Delta, never a full state snapshot */
  payload?: Uint8Array;
  actorId?: Id;
  /** Pre-rendered bot line for thin clients */
  text?: string;
}

export function encodeGameEvent(w: Writer, v: GameEvent): void {
  w.enter();
  w.id(v.gameId);
  w.id(v.roomId);
  w.u64(v.stateVersion);
  w.str(v.event);
  let present = 0;
  if (v.payload !== undefined) present++;
  if (v.actorId !== undefined) present++;
  if (v.text !== undefined) present++;
  w.u32(present);
  if (v.payload !== undefined) { const value = v.payload; w.optional(1, (w) => { w.bytes(value); }); }
  if (v.actorId !== undefined) { const value = v.actorId; w.optional(2, (w) => { w.id(value); }); }
  if (v.text !== undefined) { const value = v.text; w.optional(3, (w) => { w.str(value); }); }
  w.leave();
}

export function decodeGameEvent(r: Reader): GameEvent {
  r.enter();
  const gameId = r.id();
  const roomId = r.id();
  const stateVersion = r.u64();
  const event = r.str();
  const out: GameEvent = { gameId, roomId, stateVersion, event } as GameEvent;
  const optionalCount = r.u32();
  for (let i = 0; i < optionalCount; i++) {
    const [fieldId, sub] = r.optional();
    switch (fieldId) {
      case 1: out.payload = sub.bytes(); break;
      case 2: out.actorId = sub.id(); break;
      case 3: out.text = sub.str(); break;
      default: break; // unknown optional field: skipped by length
    }
  }
  r.leave();
  return out;
}

export type DeliveryClass = 'Critical' | 'Coalescable' | 'Droppable';
export type AuthLevel = 'None' | 'User' | 'Bot' | 'Server';
export type Direction = 'client_to_server' | 'server_to_client' | 'both';

export const OP = {
  /** Handshake. Also carries optional token and resume. */
  HELLO: 1,
  PING: 2,
  /** Cumulative watermark; retires held frames. */
  ACK: 3,
  /** Standalone (non-correlated) error, usually fatal. */
  ERROR: 4,
  RECONNECT_HINT: 5,
  AUTHENTICATE: 6,
  SUBSCRIBE: 7,
  UNSUBSCRIBE: 8,
  /** Publish public identity/prekeys for this device. */
  KEY_PUBLISH: 16,
  KEY_BUNDLE_FETCH: 17,
  MESSAGE_SEND: 32,
  MESSAGE_EVENT: 33,
  MESSAGE_RECEIPT: 34,
  MESSAGE_DELETE: 35,
  SYNC: 36,
  CONVERSATION_LIST: 37,
  CONVERSATION_CREATE: 38,
  TYPING: 39,
  PRESENCE_SET: 64,
  PRESENCE_EVENT: 65,
  ROOM_JOIN: 80,
  ROOM_LEAVE: 81,
  ROOM_LIST: 82,
  ROOM_MEMBER_EVENT: 83,
  ROOM_STATE_EVENT: 84,
  PROFILE_FETCH: 112,
  NOTIFICATION_EVENT: 144,
  GAME_ACTION: 176,
  GAME_EVENT: 177,
} as const;
export type OpcodeValue = (typeof OP)[keyof typeof OP];

export interface OpcodeMeta {
  readonly code: number;
  readonly name: string;
  readonly cost: number;
  readonly cls: DeliveryClass;
  readonly auth: AuthLevel;
  readonly direction: Direction;
  readonly ackRequired: boolean;
  readonly payload: string;
  readonly response?: string;
  readonly coalesceKey?: string;
}

export const OPCODES: Readonly<Record<number, OpcodeMeta>> = {
  1: { code: 1, name: 'HELLO', cost: 5, cls: 'Critical', auth: 'None', direction: 'client_to_server', ackRequired: false, payload: 'Hello', response: 'Welcome' },
  2: { code: 2, name: 'PING', cost: 1, cls: 'Critical', auth: 'None', direction: 'both', ackRequired: false, payload: 'Ping', response: 'Pong' },
  3: { code: 3, name: 'ACK', cost: 0, cls: 'Critical', auth: 'None', direction: 'client_to_server', ackRequired: false, payload: 'Ack' },
  4: { code: 4, name: 'ERROR', cost: 0, cls: 'Critical', auth: 'None', direction: 'server_to_client', ackRequired: false, payload: 'Error' },
  5: { code: 5, name: 'RECONNECT_HINT', cost: 0, cls: 'Critical', auth: 'None', direction: 'server_to_client', ackRequired: false, payload: 'ReconnectHint' },
  6: { code: 6, name: 'AUTHENTICATE', cost: 10, cls: 'Critical', auth: 'None', direction: 'client_to_server', ackRequired: false, payload: 'Authenticate', response: 'Authenticated' },
  7: { code: 7, name: 'SUBSCRIBE', cost: 2, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'SubscribeRequest', response: 'SubscribeResponse' },
  8: { code: 8, name: 'UNSUBSCRIBE', cost: 1, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'SubscribeRequest', response: 'SubscribeResponse' },
  16: { code: 16, name: 'KEY_PUBLISH', cost: 20, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'KeyPublish', response: 'KeyPublishResult' },
  17: { code: 17, name: 'KEY_BUNDLE_FETCH', cost: 5, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'KeyBundleRequest', response: 'KeyBundleResponse' },
  32: { code: 32, name: 'MESSAGE_SEND', cost: 1, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'MessageSend', response: 'MessageAccepted' },
  33: { code: 33, name: 'MESSAGE_EVENT', cost: 0, cls: 'Critical', auth: 'User', direction: 'server_to_client', ackRequired: true, payload: 'MessageEvent' },
  34: { code: 34, name: 'MESSAGE_RECEIPT', cost: 1, cls: 'Critical', auth: 'User', direction: 'both', ackRequired: false, payload: 'MessageReceipt' },
  35: { code: 35, name: 'MESSAGE_DELETE', cost: 2, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'MessageDelete', response: 'MessageAccepted' },
  36: { code: 36, name: 'SYNC', cost: 3, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'SyncRequest', response: 'SyncResponse' },
  37: { code: 37, name: 'CONVERSATION_LIST', cost: 3, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'ConversationListRequest', response: 'ConversationListResponse' },
  38: { code: 38, name: 'CONVERSATION_CREATE', cost: 10, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'ConversationCreateRequest', response: 'ConversationSummary' },
  39: { code: 39, name: 'TYPING', cost: 1, cls: 'Coalescable', auth: 'User', direction: 'both', ackRequired: false, payload: 'TypingEvent', coalesceKey: 'conversation_id' },
  64: { code: 64, name: 'PRESENCE_SET', cost: 1, cls: 'Coalescable', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'PresenceUpdate', response: 'Acknowledged' },
  65: { code: 65, name: 'PRESENCE_EVENT', cost: 0, cls: 'Coalescable', auth: 'User', direction: 'server_to_client', ackRequired: false, payload: 'PresenceEvent', coalesceKey: 'user_id' },
  80: { code: 80, name: 'ROOM_JOIN', cost: 20, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'RoomJoinRequest', response: 'RoomJoinResponse' },
  81: { code: 81, name: 'ROOM_LEAVE', cost: 5, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'RoomLeaveRequest', response: 'Acknowledged' },
  82: { code: 82, name: 'ROOM_LIST', cost: 5, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'RoomListRequest', response: 'RoomListResponse' },
  83: { code: 83, name: 'ROOM_MEMBER_EVENT', cost: 0, cls: 'Coalescable', auth: 'User', direction: 'server_to_client', ackRequired: false, payload: 'RoomMemberEvent', coalesceKey: 'room_id' },
  84: { code: 84, name: 'ROOM_STATE_EVENT', cost: 0, cls: 'Coalescable', auth: 'User', direction: 'server_to_client', ackRequired: false, payload: 'RoomStateEvent', coalesceKey: 'room_id' },
  112: { code: 112, name: 'PROFILE_FETCH', cost: 3, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'ProfileRequest', response: 'ProfileResponse' },
  144: { code: 144, name: 'NOTIFICATION_EVENT', cost: 0, cls: 'Droppable', auth: 'User', direction: 'server_to_client', ackRequired: false, payload: 'NotificationEvent' },
  176: { code: 176, name: 'GAME_ACTION', cost: 2, cls: 'Critical', auth: 'User', direction: 'client_to_server', ackRequired: false, payload: 'GameAction', response: 'Acknowledged' },
  177: { code: 177, name: 'GAME_EVENT', cost: 0, cls: 'Critical', auth: 'User', direction: 'server_to_client', ackRequired: false, payload: 'GameEvent' },
};

export function opcodeName(code: number): string {
  return OPCODES[code]?.name ?? `UNKNOWN(0x${code.toString(16)})`;
}
