#!/usr/bin/env node
/**
 * Migo protocol code generator.
 *
 * Reads the IDL in shared/protocol/schema and emits:
 *   server/crates/migo-protocol/src/generated.rs
 *   packages/protocol/src/generated.ts
 *
 * The IDL is the single source of truth (ADR-0002); generated files are committed
 * (ADR-0010) and must never be hand-edited.
 *
 * Usage:
 *   node tools/protocol-codegen/generate.mjs            # write files
 *   node tools/protocol-codegen/generate.mjs --check    # fail if stale (CI gate)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
/// The package runner the repository pins in package.json's `packageManager`.
const PNPM = process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm';
const SCHEMA = join(ROOT, 'shared/protocol/schema');
const CHECK = process.argv.includes('--check');

const read = (f) => JSON.parse(readFileSync(join(SCHEMA, f), 'utf8'));
const meta = read('meta.json');
const { enums } = read('enums.json');
const { structs } = read('structs.json');
const opcodesDoc = read('opcodes.json');
const errorsDoc = read('errors.json');

// ---------------------------------------------------------------- validation

const enumNames = new Set(enums.map((e) => e.name));
const structNames = new Set(structs.map((s) => s.name));
const problems = [];

const listInner = (t) => (t.startsWith('list<') ? t.slice(5, -1) : null);
const PRIMS = new Set(['bool', 'u32', 'u64', 'bitmask64', 'string', 'bytes', 'id', 'timestamp']);

function checkType(t, where) {
  const inner = listInner(t);
  if (inner) {
    if (listInner(inner)) problems.push(`${where}: nested list<list<>> is not supported`);
    return checkType(inner, where);
  }
  if (!PRIMS.has(t) && !enumNames.has(t) && !structNames.has(t)) {
    problems.push(`${where}: unknown type "${t}"`);
  }
}

for (const s of structs) {
  const optIds = new Set();
  let sawOptional = false;
  for (const f of s.fields) {
    checkType(f.type, `${s.name}.${f.name}`);
    if (f.optional) {
      sawOptional = true;
      if (typeof f.id !== 'number' || f.id < 1) {
        problems.push(`${s.name}.${f.name}: optional field needs a positive stable id`);
      } else if (optIds.has(f.id)) {
        problems.push(`${s.name}.${f.name}: duplicate optional id ${f.id}`);
      }
      optIds.add(f.id);
    } else if (sawOptional) {
      // Required fields are positional; they must all precede the optional section.
      problems.push(`${s.name}.${f.name}: required field declared after an optional field`);
    }
  }
}

const seenCodes = new Map();
for (const op of opcodesDoc.opcodes) {
  if (seenCodes.has(op.code))
    problems.push(`opcode ${op.name}: code ${op.code} already used by ${seenCodes.get(op.code)}`);
  seenCodes.set(op.code, op.name);
  if (typeof op.cost !== 'number')
    problems.push(`opcode ${op.name}: missing rate-limit cost (ADR-0006)`);
  if (!op.class) problems.push(`opcode ${op.name}: missing delivery class (ADR-0008)`);
  if (!structNames.has(op.payload))
    problems.push(`opcode ${op.name}: unknown payload struct "${op.payload}"`);
  if (op.response && !structNames.has(op.response))
    problems.push(`opcode ${op.name}: unknown response struct "${op.response}"`);
  const inRange = opcodesDoc.ranges.some((r) => op.code >= r.from && op.code <= r.to);
  if (!inRange) problems.push(`opcode ${op.name}: code ${op.code} outside every declared range`);
}

const seenErr = new Set();
for (const e of errorsDoc.errors) {
  if (seenErr.has(e.code)) problems.push(`error ${e.symbol}: duplicate code ${e.code}`);
  seenErr.add(e.code);
  if (!errorsDoc.classes.some((c) => e.code >= c.range[0] && e.code <= c.range[1])) {
    problems.push(`error ${e.symbol}: code ${e.code} outside every declared class range`);
  }
}

if (problems.length) {
  console.error('protocol schema is invalid:');
  for (const p of problems) console.error('  - ' + p);
  process.exit(1);
}

// ---------------------------------------------------------------- helpers

const pascal = (s) => s.replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const camel = (s) => {
  const p = pascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
};
// Prefixes every non-empty line with `n` spaces. Used by the Kotlin emitter, whose
// write helpers return statement blocks that land at different indentation depths
// (top-level struct body vs. inside an optional-field lambda).
const indentLines = (text, n) => {
  const pad = ' '.repeat(n);
  return text
    .split('\n')
    .map((l) => (l ? pad + l : l))
    .join('\n');
};
const banner = (lang) =>
  `${lang === 'rs' ? '//' : '//'} @generated by tools/protocol-codegen/generate.mjs — DO NOT EDIT.\n` +
  `${'//'} Source of truth: shared/protocol/schema (MWP/${meta.protocol.version}).\n` +
  `${'//'} Regenerate with: make protocol\n`;

const docLines = (text, indent = '') =>
  text
    ? text
        .split('\n')
        .map((l) => `${indent}/// ${l}`)
        .join('\n') + '\n'
    : '';

// ---------------------------------------------------------------- Rust

function rustType(t) {
  const inner = listInner(t);
  if (inner) return `Vec<${rustType(inner)}>`;
  switch (t) {
    case 'bool':
      return 'bool';
    case 'u32':
      return 'u32';
    case 'u64':
    case 'bitmask64':
      return 'u64';
    case 'string':
      return 'String';
    case 'bytes':
      return 'Vec<u8>';
    case 'id':
      return 'Id';
    case 'timestamp':
      return 'Timestamp';
    default:
      return t;
  }
}

// `byRef` says whether `expr` is already a reference. Required fields are place
// expressions on `self` (owned), while optional fields and list items arrive as
// borrows. Getting this wrong is the difference between a clean build and a
// hundred type errors, so it is a parameter rather than a guess.
function rustWrite(t, expr, w = 'w', byRef = false) {
  const inner = listInner(t);
  if (inner) {
    return `{ ${w}.list_len(${expr}.len())?; for item in ${expr}.iter() { ${rustWrite(inner, 'item', w, true)} } }`;
  }
  const star = byRef ? '*' : '';
  const amp = byRef ? '' : '&';
  switch (t) {
    case 'bool':
      return `${w}.write_bool(${star}${expr});`;
    case 'u32':
      return `${w}.write_u32(${star}${expr});`;
    case 'u64':
    case 'bitmask64':
      return `${w}.write_u64(${star}${expr});`;
    case 'string':
      return `${w}.write_str(${amp}${expr})?;`;
    case 'bytes':
      return `${w}.write_bytes(${amp}${expr})?;`;
    case 'id':
      return `${w}.write_id(${amp}${expr});`;
    case 'timestamp':
      return `${w}.write_timestamp(${star}${expr});`;
    default:
      if (enumNames.has(t)) return `${w}.write_u32(${expr}.to_wire());`;
      return `${expr}.encode(${w})?;`;
  }
}

function rustRead(t, r = 'r') {
  const inner = listInner(t);
  if (inner) {
    return `{ let n = ${r}.read_list_len()?; let mut v = Vec::with_capacity(n); for _ in 0..n { v.push(${rustRead(inner, r)}); } v }`;
  }
  switch (t) {
    case 'bool':
      return `${r}.read_bool()?`;
    case 'u32':
      return `${r}.read_u32()?`;
    case 'u64':
    case 'bitmask64':
      return `${r}.read_u64()?`;
    case 'string':
      return `${r}.read_string()?`;
    case 'bytes':
      return `${r}.read_bytes()?`;
    case 'id':
      return `${r}.read_id()?`;
    case 'timestamp':
      return `${r}.read_timestamp()?`;
    default:
      if (enumNames.has(t)) return `${t}::from_wire(${r}.read_u32()?)`;
      return `${t}::decode(${r})?`;
  }
}

function genRust() {
  let out = banner('rs');
  out += `
// Generated code is held to the same lint bar as hand-written code, with three
// exceptions that are inherent to codegen rather than sloppiness.
#![allow(
    clippy::too_many_lines,
    clippy::needless_range_loop,
    clippy::field_reassign_with_default,
    clippy::match_single_binding,
    unused_imports
)]

use migo_core::{Id, Timestamp};
use migo_wire::{Decode, Encode, Reader, Result, WireError, Writer};

/// Protocol name and version this build speaks.
pub const PROTOCOL_NAME: &str = "${meta.protocol.name}";
pub const PROTOCOL_VERSION: u32 = ${meta.protocol.version};
/// Milliseconds between the Unix epoch and the Migo epoch (saves a byte per timestamp).
pub const EPOCH_MS: i64 = ${meta.epoch_ms};

/// Codec and session limits.
///
/// Re-exported from \`migo-wire\` rather than restated here: the codec is the
/// component that has to enforce them, and two copies of a number is one copy
/// too many.
pub mod limits {
    pub use migo_wire::limits::*;
}
`;
  out += `\n/// Frame flag bits (see docs/02-protocol.md section 3).\n///\n/// Re-exported from \`migo-wire\`, which is the crate that acts on them.\npub mod flags {\n    pub use migo_wire::flags::*;\n}\n`;

  out += `\n/// Negotiable feature bits exchanged in HELLO/WELCOME.\npub mod features {\n`;
  for (const f of meta.features)
    out += `    /// ${f.description}\n    pub const ${f.name}: u64 = 1 << ${f.bit};\n`;
  out += `\n    /// Everything this build understands.\n    pub const ALL: u64 = ${meta.features.map((f) => f.name).join(' | ')};\n}\n`;

  out += `\n/// Stable protocol error codes. Frozen once released.\npub mod codes {\n`;
  for (const e of errorsDoc.errors) {
    if (e.doc) out += `    /// ${e.doc}\n`;
    out += `    pub const ${e.symbol}: u32 = ${e.code};\n`;
  }
  out += `\n    /// Every code in this build, for exhaustive tests and registry dumps.\n    ///\n    /// A table that maps codes to symbols or HTTP statuses is only correct if\n    /// every code appears in it, and the only way to assert that is to have the\n    /// list itself be generated too.\n    pub const ALL: &[u32] = &[\n${errorsDoc.errors.map((e) => `        ${e.symbol},`).join('\n')}\n    ];\n`;
  out += `}\n`;

  // Error metadata
  out += `
/// Behavioural class of an error code, so clients can act without knowing every member.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ErrorClass {
${errorsDoc.classes.map((c) => `    ${c.name},`).join('\n')}
    Unknown,
}

impl ErrorClass {
    #[must_use]
    pub const fn of(code: u32) -> Self {
        match code {
${errorsDoc.classes.map((c) => `            ${c.range[0]}..=${c.range[1]} => Self::${c.name},`).join('\n')}
            _ => Self::Unknown,
        }
    }

    /// Whether a client may retry the same request unchanged.
    #[must_use]
    pub const fn retryable(self) -> bool {
        match self {
${errorsDoc.classes.map((c) => `            Self::${c.name} => ${c.retryable},`).join('\n')}
            Self::Unknown => false,
        }
    }
}

/// Symbolic name for a code, or \`None\` if this build does not know it.
#[must_use]
pub fn error_symbol(code: u32) -> Option<&'static str> {
    Some(match code {
${errorsDoc.errors.map((e) => `        codes::${e.symbol} => "${e.symbol}",`).join('\n')}
        _ => return None,
    })
}

/// HTTP status used when the same failure is surfaced over REST.
#[must_use]
pub fn error_http_status(code: u32) -> u16 {
    match code {
${errorsDoc.errors.map((e) => `        codes::${e.symbol} => ${e.http},`).join('\n')}
        _ => 500,
    }
}
`;

  // Enums
  for (const e of enums) {
    out += `\n`;
    if (e.doc) out += docLines(e.doc);
    out += `#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\n#[repr(u32)]\npub enum ${e.name} {\n`;
    for (const v of e.variants) {
      const isUnknown = v.name === 'Unknown';
      out += `${isUnknown ? '    #[default]\n' : ''}    ${v.name} = ${v.value},\n`;
    }
    out += `}\n\nimpl ${e.name} {\n    #[must_use]\n    pub const fn to_wire(self) -> u32 { self as u32 }\n\n`;
    out += `    /// Unknown discriminants decode to \`Unknown\` so a new variant never breaks an old peer.\n`;
    out += `    #[must_use]\n    pub const fn from_wire(v: u32) -> Self {\n        match v {\n`;
    for (const v of e.variants)
      if (v.name !== 'Unknown') out += `            ${v.value} => Self::${v.name},\n`;
    out += `            _ => Self::Unknown,\n        }\n    }\n\n    #[must_use]\n    pub const fn as_str(self) -> &'static str {\n        match self {\n`;
    for (const v of e.variants) out += `            Self::${v.name} => "${v.name}",\n`;
    out += `        }\n    }\n}\n`;
  }

  // Structs
  for (const s of structs) {
    const req = s.fields.filter((f) => !f.optional);
    const opt = s.fields.filter((f) => f.optional);
    out += `\n`;
    if (s.doc) out += docLines(s.doc);
    out += `#[derive(Debug, Clone, PartialEq, Default)]\npub struct ${s.name} {\n`;
    for (const f of s.fields) {
      if (f.doc) out += `    /// ${f.doc}\n`;
      const t = rustType(f.type);
      out += `    pub ${f.name}: ${f.optional ? `Option<${t}>` : t},\n`;
    }
    out += `}\n\nimpl Encode for ${s.name} {\n    fn encode(&self, w: &mut Writer) -> Result<()> {\n        w.enter()?;\n`;
    for (const f of req) out += `        ${rustWrite(f.type, `self.${f.name}`, 'w', false)}\n`;
    if (opt.length) {
      out += `        let present = ${opt.map((f) => `usize::from(self.${f.name}.is_some())`).join(' + ')};\n`;
      out += `        w.write_u32(present as u32);\n`;
      for (const f of opt) {
        out += `        if let Some(v) = &self.${f.name} {\n            w.optional(${f.id}, |w| { ${rustWrite(f.type, 'v', 'w', true)} Ok(()) })?;\n        }\n`;
      }
    } else {
      out += `        w.write_u32(0);\n`;
    }
    out += `        w.leave();\n        Ok(())\n    }\n}\n\nimpl Decode for ${s.name} {\n    fn decode(r: &mut Reader) -> Result<Self> {\n        r.enter()?;\n`;
    // `mut` only when a field is actually assigned: a struct with no fields at all
    // never mutates its accumulator, and clippy denies the unused-mut warning the
    // other shape would raise.
    out +=
      req.length + opt.length
        ? `        let mut out = Self::default();\n`
        : `        let out = Self::default();\n`;
    for (const f of req) out += `        out.${f.name} = ${rustRead(f.type)};\n`;
    // The optional block is always read, even for a struct that currently has no
    // optional fields: a newer peer may send some, and skipping them by length is
    // exactly the forward compatibility MSE exists to provide. Only the shape of
    // the loop body differs, so that the emitted code carries no unused bindings.
    out += `        let optional_count = r.read_u32()?;\n        for _ in 0..optional_count {\n`;
    if (opt.length) {
      out += `            let (field_id, mut owned) = r.read_optional()?;\n            let sub = &mut owned;\n            match field_id {\n`;
      for (const f of opt)
        out += `                ${f.id} => out.${f.name} = Some(${rustRead(f.type, 'sub')}),\n`;
      out += `                _ => { /* unknown optional field: skipped by length (forward compatibility) */ }\n            }\n`;
    } else {
      out += `            // No optional fields are defined for this struct in this\n            // protocol build; a newer peer's fields are skipped by length.\n            let _ = r.read_optional()?;\n`;
    }
    out += `        }\n        r.leave();\n        Ok(out)\n    }\n}\n`;
  }

  // Opcodes
  out += `
/// Delivery class, deciding what happens when a session queue is full (ADR-0008).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DeliveryClass {
${meta.delivery_classes.map((c) => `    /// ${c.description}\n    ${c.name},`).join('\n')}
}

/// Minimum session state an opcode requires.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum AuthLevel {
${meta.auth_levels.map((a) => `    /// ${a.description}\n    ${a.name},`).join('\n')}
}

/// Direction an opcode may legally travel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Direction {
    ClientToServer,
    ServerToClient,
    Both,
}

/// Every opcode in MWP/${meta.protocol.version}.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum Opcode {
${opcodesDoc.opcodes.map((o) => `${o.doc ? `    /// ${o.doc}\n` : ''}    ${pascal(o.name.toLowerCase())} = ${o.code},`).join('\n')}
}

impl Opcode {
    #[must_use]
    pub const fn to_wire(self) -> u32 { self as u32 }

    /// \`None\` for an opcode this build does not know — the caller answers UNKNOWN_OPCODE.
    #[must_use]
    pub const fn from_wire(v: u32) -> Option<Self> {
        Some(match v {
${opcodesDoc.opcodes.map((o) => `            ${o.code} => Self::${pascal(o.name.toLowerCase())},`).join('\n')}
            _ => return None,
        })
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => "${o.name}",`).join('\n')}
        }
    }

    /// Rate-limit cost in tokens (ADR-0006).
    #[must_use]
    pub const fn cost(self) -> u32 {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => ${o.cost},`).join('\n')}
        }
    }

    #[must_use]
    pub const fn class(self) -> DeliveryClass {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => DeliveryClass::${o.class},`).join('\n')}
        }
    }

    #[must_use]
    pub const fn auth(self) -> AuthLevel {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => AuthLevel::${o.auth},`).join('\n')}
        }
    }

    #[must_use]
    pub const fn direction(self) -> Direction {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => Direction::${o.direction === 'client_to_server' ? 'ClientToServer' : o.direction === 'server_to_client' ? 'ServerToClient' : 'Both'},`).join('\n')}
        }
    }

    /// Whether the receiver must acknowledge this frame by watermark.
    #[must_use]
    pub const fn ack_required(self) -> bool {
        match self {
${opcodesDoc.opcodes.map((o) => `            Self::${pascal(o.name.toLowerCase())} => ${o.ack_required ? 'true' : 'false'},`).join('\n')}
        }
    }

    /// Whether a client socket may send this opcode at all.
    #[must_use]
    pub const fn accepts_from_client(self) -> bool {
        matches!(self.direction(), Direction::ClientToServer | Direction::Both)
            && !matches!(self.auth(), AuthLevel::Server)
    }

    /// All opcodes, for exhaustive tests and registry dumps.
    pub const ALL: &'static [Opcode] = &[
${opcodesDoc.opcodes.map((o) => `        Self::${pascal(o.name.toLowerCase())},`).join('\n')}
    ];
}
`;
  return out;
}

// ---------------------------------------------------------------- TypeScript

function tsType(t) {
  const inner = listInner(t);
  if (inner) return `${tsType(inner)}[]`;
  switch (t) {
    case 'bool':
      return 'boolean';
    case 'u32':
    case 'u64':
      return 'number';
    case 'bitmask64':
      return 'bigint';
    case 'string':
      return 'string';
    case 'bytes':
      return 'Uint8Array';
    case 'id':
      return 'Id';
    case 'timestamp':
      return 'number';
    default:
      return t;
  }
}

function tsWrite(t, expr, w = 'w') {
  const inner = listInner(t);
  if (inner)
    return `{ ${w}.listLen(${expr}.length); for (const item of ${expr}) { ${tsWrite(inner, 'item', w)} } }`;
  switch (t) {
    case 'bool':
      return `${w}.bool(${expr});`;
    case 'u32':
      return `${w}.u32(${expr});`;
    case 'u64':
      return `${w}.u64(${expr});`;
    case 'bitmask64':
      return `${w}.u64big(${expr});`;
    case 'string':
      return `${w}.str(${expr});`;
    case 'bytes':
      return `${w}.bytes(${expr});`;
    case 'id':
      return `${w}.id(${expr});`;
    case 'timestamp':
      return `${w}.timestamp(${expr});`;
    default:
      if (enumNames.has(t)) return `${w}.u32(${expr});`;
      return `encode${t}(${w}, ${expr});`;
  }
}

function tsRead(t, r = 'r') {
  const inner = listInner(t);
  if (inner)
    return `((): ${tsType(t)} => { const n = ${r}.listLen(); const v: ${tsType(inner)}[] = []; for (let i = 0; i < n; i++) v.push(${tsRead(inner, r)}); return v; })()`;
  switch (t) {
    case 'bool':
      return `${r}.bool()`;
    case 'u32':
      return `${r}.u32()`;
    case 'u64':
      return `${r}.u64()`;
    case 'bitmask64':
      return `${r}.u64big()`;
    case 'string':
      return `${r}.str()`;
    case 'bytes':
      return `${r}.bytes()`;
    case 'id':
      return `${r}.id()`;
    case 'timestamp':
      return `${r}.timestamp()`;
    default:
      if (enumNames.has(t)) return `${r}.u32() as ${t}`;
      return `decode${t}(${r})`;
  }
}

function genTs() {
  let out = banner('ts');
  out += `/* eslint-disable */\nimport type { Id } from '@migo/wire';\nimport { Reader, Writer } from '@migo/wire';\n\n`;
  out += `export const PROTOCOL_NAME = '${meta.protocol.name}' as const;\nexport const PROTOCOL_VERSION = ${meta.protocol.version} as const;\nexport const EPOCH_MS = ${meta.epoch_ms} as const;\n\n`;
  out += `export const LIMITS = {\n${Object.entries(meta.limits)
    .map(([k, v]) => `  ${k}: ${v},`)
    .join('\n')}\n} as const;\n\n`;
  out += `/** Frame flag bits. */\nexport const FLAG = {\n${meta.flags.map((f) => `  /** ${f.description} */\n  ${f.name}: ${1 << f.bit},`).join('\n')}\n} as const;\nexport const RESERVED_FLAG_MASK = FLAG.RESERVED_6 | FLAG.FLAGS_EXT;\n\n`;
  out += `/** Negotiable feature bits (64-bit, hence bigint). */\nexport const FEATURE = {\n${meta.features.map((f) => `  /** ${f.description} */\n  ${f.name}: 1n << ${f.bit}n,`).join('\n')}\n} as const;\nexport const ALL_FEATURES = ${meta.features.map((f) => `FEATURE.${f.name}`).join(' | ')};\n\n`;
  out += `/** Stable protocol error codes. */\nexport const CODE = {\n${errorsDoc.errors.map((e) => `${e.doc ? `  /** ${e.doc} */\n` : ''}  ${e.symbol}: ${e.code},`).join('\n')}\n} as const;\nexport type ErrorCode = (typeof CODE)[keyof typeof CODE];\n\n`;
  out += `export const ERROR_SYMBOLS: Record<number, string> = {\n${errorsDoc.errors.map((e) => `  ${e.code}: '${e.symbol}',`).join('\n')}\n};\n\n`;
  out += `export type ErrorClassName = ${errorsDoc.classes.map((c) => `'${c.name}'`).join(' | ')} | 'Unknown';\n\n`;
  out += `const ERROR_CLASSES: ReadonlyArray<{ from: number; to: number; name: ErrorClassName; retryable: boolean; action: string }> = [\n${errorsDoc.classes.map((c) => `  { from: ${c.range[0]}, to: ${c.range[1]}, name: '${c.name}', retryable: ${c.retryable}, action: '${c.client_action}' },`).join('\n')}\n];\n\n`;
  out += `export function errorClass(code: number): ErrorClassName {\n  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.name ?? 'Unknown';\n}\n\nexport function isRetryable(code: number): boolean {\n  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.retryable ?? false;\n}\n\n/** What a client should do about this error, without knowing every code. */\nexport function clientAction(code: number): string {\n  return ERROR_CLASSES.find((c) => code >= c.from && code <= c.to)?.action ?? 'backoff_retry';\n}\n\n`;

  for (const e of enums) {
    if (e.doc) out += `/** ${e.doc} */\n`;
    out += `export enum ${e.name} {\n${e.variants.map((v) => `  ${v.name} = ${v.value},`).join('\n')}\n}\n\n`;
  }

  for (const s of structs) {
    const req = s.fields.filter((f) => !f.optional);
    const opt = s.fields.filter((f) => f.optional);
    if (s.doc) out += `/** ${s.doc} */\n`;
    out += `export interface ${s.name} {\n`;
    for (const f of s.fields) {
      if (f.doc) out += `  /** ${f.doc} */\n`;
      out += `  ${camel(f.name)}${f.optional ? '?' : ''}: ${tsType(f.type)};\n`;
    }
    out += `}\n\n`;
    // A struct with no fields never reads its value parameter, and `tsc`'s
    // noUnusedParameters rejects that unless the name carries the underscore
    // exemption. The wire shape is unchanged: an empty struct still encodes as
    // its zero optional count.
    const valueParam = req.length + opt.length === 0 ? '_v' : 'v';
    out += `export function encode${s.name}(w: Writer, ${valueParam}: ${s.name}): void {\n  w.enter();\n`;
    for (const f of req) out += `  ${tsWrite(f.type, `${valueParam}.${camel(f.name)}`)}\n`;
    if (opt.length) {
      out += `  let present = 0;\n${opt.map((f) => `  if (${valueParam}.${camel(f.name)} !== undefined) present++;`).join('\n')}\n  w.u32(present);\n`;
      for (const f of opt) {
        out += `  if (${valueParam}.${camel(f.name)} !== undefined) { const value = ${valueParam}.${camel(f.name)}; w.optional(${f.id}, (w) => { ${tsWrite(f.type, 'value')} }); }\n`;
      }
    } else {
      out += `  w.u32(0);\n`;
    }
    out += `  w.leave();\n}\n\n`;
    out += `export function decode${s.name}(r: Reader): ${s.name} {\n  r.enter();\n`;
    for (const f of req) out += `  const ${camel(f.name)} = ${tsRead(f.type)};\n`;
    out += `  const out: ${s.name} = { ${req.map((f) => camel(f.name)).join(', ')} } as ${s.name};\n`;
    out += `  const optionalCount = r.u32();\n`;
    if (opt.length) {
      out += `  for (let i = 0; i < optionalCount; i++) {\n    const [fieldId, sub] = r.optional();\n    switch (fieldId) {\n`;
      for (const f of opt)
        out += `      case ${f.id}: out.${camel(f.name)} = ${tsRead(f.type, 'sub')}; break;\n`;
      out += `      default: break; // unknown optional field: skipped by length\n    }\n  }\n`;
    } else {
      // A struct with no optional fields still reads the count and still skips whatever a
      // newer peer sent. Destructuring the entry would bind a `sub` reader nothing uses,
      // and this workspace compiles with `noUnusedLocals` — generated code has to pass the
      // same checks as hand-written code, or the strictness is theatre.
      out += `  // No optional fields in this version of the struct. Each entry is length-delimited,\n  // so reading it is skipping it, and a newer peer may well have sent one.\n  for (let i = 0; i < optionalCount; i++) r.optional();\n`;
    }
    out += `  r.leave();\n  return out;\n}\n\n`;
  }

  out += `export type DeliveryClass = ${meta.delivery_classes.map((c) => `'${c.name}'`).join(' | ')};\nexport type AuthLevel = ${meta.auth_levels.map((a) => `'${a.name}'`).join(' | ')};\nexport type Direction = 'client_to_server' | 'server_to_client' | 'both';\n\n`;
  out += `export const OP = {\n${opcodesDoc.opcodes.map((o) => `${o.doc ? `  /** ${o.doc} */\n` : ''}  ${o.name}: ${o.code},`).join('\n')}\n} as const;\nexport type OpcodeValue = (typeof OP)[keyof typeof OP];\n\n`;
  out += `export interface OpcodeMeta {\n  readonly code: number;\n  readonly name: string;\n  readonly cost: number;\n  readonly cls: DeliveryClass;\n  readonly auth: AuthLevel;\n  readonly direction: Direction;\n  readonly ackRequired: boolean;\n  readonly payload: string;\n  readonly response?: string;\n  readonly coalesceKey?: string;\n}\n\n`;
  out += `export const OPCODES: Readonly<Record<number, OpcodeMeta>> = {\n${opcodesDoc.opcodes.map((o) => `  ${o.code}: { code: ${o.code}, name: '${o.name}', cost: ${o.cost}, cls: '${o.class}', auth: '${o.auth}', direction: '${o.direction}', ackRequired: ${!!o.ack_required}, payload: '${o.payload}'${o.response ? `, response: '${o.response}'` : ''}${o.coalesce_key ? `, coalesceKey: '${o.coalesce_key}'` : ''} },`).join('\n')}\n};\n\n`;
  out += `export function opcodeName(code: number): string {\n  return OPCODES[code]?.name ?? \`UNKNOWN(0x\${code.toString(16)})\`;\n}\n`;
  return out;
}

function genRustLimits() {
  let out = banner('rs');
  out += `
//! Codec and session limits, generated from \`shared/protocol/schema/meta.json\`.
//!
//! These are enforced *before* allocation. A peer that claims a 4 GiB string
//! must be rejected while reading the length, not after reserving the buffer:
//! otherwise a 6-byte frame is a remote out-of-memory primitive.

`;
  const usizeKeys = new Set([
    'MAX_FRAME_BYTES',
    'MAX_STRING_BYTES',
    'MAX_BYTES_LEN',
    'MAX_LIST_ITEMS',
    'MAX_MAP_ITEMS',
    'MAX_NESTING_DEPTH',
    'MAX_BATCH_ITEMS',
    'MAX_VARINT_BYTES',
    'COMPRESS_MIN_BYTES',
    'MAX_SUBSCRIPTIONS',
    'SESSION_QUEUE_CAPACITY',
    'RESUME_BUFFER_FRAMES',
  ]);
  for (const [k, v] of Object.entries(meta.limits)) {
    const doc = LIMIT_DOCS[k];
    if (doc) out += `/// ${doc}\n`;
    out += `pub const ${k}: ${usizeKeys.has(k) ? 'usize' : 'u32'} = ${v};\n`;
  }
  return out;
}

const LIMIT_DOCS = {
  MAX_FRAME_BYTES:
    'Largest single frame, before compression on send and after decompression on receive.',
  MAX_STRING_BYTES: 'Largest UTF-8 string field.',
  MAX_BYTES_LEN: 'Largest opaque byte field, sized for one E2E ciphertext.',
  MAX_LIST_ITEMS: 'Largest list field.',
  MAX_MAP_ITEMS: 'Largest map field.',
  MAX_NESTING_DEPTH: 'Deepest struct nesting; bounds recursive decoding.',
  MAX_BATCH_ITEMS: 'Frames per BATCH envelope.',
  MAX_VARINT_BYTES: 'Longest accepted varint encoding (10 bytes covers u64).',
  COMPRESS_MIN_BYTES:
    'Payloads below this are never compressed: the header costs more than the saving.',
  COMPRESS_MIN_GAIN_PERCENT:
    'Compression is discarded unless it saves at least this share of the payload.',
  MAX_SUBSCRIPTIONS: 'Topics one session may subscribe to.',
  DEFAULT_HEARTBEAT_MS: 'Default heartbeat interval advertised in WELCOME.',
  SESSION_QUEUE_CAPACITY: 'Bounded outbound queue depth per session (ADR-0008).',
  LAGGING_DEADLINE_MS: 'Grace period before a session that cannot keep up is closed.',
  BATCH_LINGER_MS: 'How long a batch stays open waiting for more events.',
  RESUME_BUFFER_FRAMES: 'Frames retained per session for resume after a reconnect.',
  RESUME_WINDOW_MS: 'How long after a disconnect a session may still be resumed.',
};

function genRustFlags() {
  let out = banner('rs');
  out += `
//! Frame flag bits, generated from \`shared/protocol/schema/meta.json\`.
//!
//! Reserved bits are listed explicitly and a receiver must **reject** a frame
//! that sets one. Ignoring unknown flags feels forgiving, but it would make the
//! bits unusable forever: old peers would already be accepting frames whose
//! meaning they cannot see, so a future version could never rely on them.

`;
  for (const f of meta.flags) {
    out += `/// ${f.description}\n`;
    out += `pub const ${f.name}: u8 = 1 << ${f.bit};\n`;
  }
  out += `\n/// Bits a MWP/${meta.protocol.version} receiver must reject.\npub const RESERVED_MASK: u8 = ${meta.flags
    .filter((f) => /^RESERVED_|^FLAGS_EXT$/.test(f.name))
    .map((f) => f.name)
    .join(' | ')};\n`;
  out += `\n/// Every bit this build understands.\npub const KNOWN_MASK: u8 = ${meta.flags
    .filter((f) => !/^RESERVED_|^FLAGS_EXT$/.test(f.name))
    .map((f) => f.name)
    .join(' | ')};\n`;
  out += `
/// Renders the set bits as a stable, comma-separated list for logs.
#[must_use]
pub fn describe(bits: u8) -> String {
    let mut parts: Vec<&'static str> = Vec::new();
${meta.flags.map((f) => `    if bits & ${f.name} != 0 {\n        parts.push("${f.name}");\n    }`).join('\n')}
    if parts.is_empty() {
        return "none".to_string();
    }
    parts.join(",")
}
`;
  return out;
}

// ---------------------------------------------------------------- Kotlin
//
// Emits the protocol layer for the Android client (package com.migo.core.protocol). The wire
// foundation — Reader, Writer, Id, Limits, varint, framing, batching, compression — is
// hand-written and lives in com.migo.core.wire, so this generator imports only Id/Reader/Writer
// from there and emits the schema-derived surface: constants, features, the error registry,
// enums, structs, and the opcode table. The encode/decode bodies mirror the Rust and TypeScript
// encoders statement for statement so all three implementations stay byte-identical against the
// shared conformance vectors. Kotlin has no in-tree formatter, so the output is emitted as-is,
// the same treatment TypeScript gets.

function kotlinType(t) {
  const inner = listInner(t);
  if (inner) return `List<${kotlinType(inner)}>`;
  switch (t) {
    case 'bool':
      return 'Boolean';
    case 'u32':
    case 'u64':
      return 'Long';
    case 'bitmask64':
      return 'ULong';
    case 'string':
      return 'String';
    case 'bytes':
      return 'ByteArray';
    case 'id':
      return 'Id';
    case 'timestamp':
      return 'Long';
    default:
      return t; // enum or struct — its own generated type
  }
}

// Kotlin writes land in statement position, so a list expands to two statements rather than an
// expression. `w` is the writer in scope — inside an optional field it is the child writer the
// lambda receives, so the caller passes that name in.
function kotlinWrite(t, expr, w = 'w') {
  const inner = listInner(t);
  if (inner) {
    return `${w}.listLen(${expr}.size)\nfor (item in ${expr}) { ${kotlinWrite(inner, 'item', w)} }`;
  }
  switch (t) {
    case 'bool':
      return `${w}.bool(${expr})`;
    case 'u32':
      return `${w}.u32(${expr})`;
    case 'u64':
      return `${w}.u64(${expr})`;
    case 'bitmask64':
      return `${w}.u64big(${expr})`;
    case 'string':
      return `${w}.str(${expr})`;
    case 'bytes':
      return `${w}.bytes(${expr})`;
    case 'id':
      return `${w}.id(${expr})`;
    case 'timestamp':
      return `${w}.timestamp(${expr})`;
    default:
      if (enumNames.has(t)) return `${w}.u32(${expr}.toWire())`;
      return `${expr}.encode(${w})`;
  }
}

// Kotlin reads are expressions, so a list becomes a `run { … }` block that yields the list.
function kotlinRead(t, r = 'r') {
  const inner = listInner(t);
  if (inner) {
    return `run { val n = ${r}.listLen(); val acc = ArrayList<${kotlinType(inner)}>(n); for (i in 0 until n) acc.add(${kotlinRead(inner, r)}); acc }`;
  }
  switch (t) {
    case 'bool':
      return `${r}.bool()`;
    case 'u32':
      return `${r}.u32()`;
    case 'u64':
      return `${r}.u64()`;
    case 'bitmask64':
      return `${r}.u64big()`;
    case 'string':
      return `${r}.str()`;
    case 'bytes':
      return `${r}.bytes()`;
    case 'id':
      return `${r}.id()`;
    case 'timestamp':
      return `${r}.timestamp()`;
    default:
      if (enumNames.has(t)) return `${t}.fromWire(${r}.u32())`;
      return `${t}.decode(${r})`;
  }
}

function genKotlin() {
  const dirMap = {
    client_to_server: 'ClientToServer',
    server_to_client: 'ServerToClient',
    both: 'Both',
  };
  const kdoc = (text, pad = '') => (text ? `${pad}/** ${text.replace(/\n/g, ' ')} */\n` : '');

  let out = banner('kt');
  out += `@file:Suppress("NAME_SHADOWING", "unused", "RedundantVisibilityModifier", "MemberVisibilityCanBePrivate")\n\n`;
  out += `package com.migo.core.protocol\n\n`;
  out += `import com.migo.core.wire.Id\nimport com.migo.core.wire.Reader\nimport com.migo.core.wire.Writer\n\n`;

  // Protocol identity
  out += kdoc('Protocol name and version this build speaks.');
  out += `const val PROTOCOL_NAME: String = "${meta.protocol.name}"\n`;
  out += `const val PROTOCOL_VERSION: Int = ${meta.protocol.version}\n`;
  out += kdoc(
    'Milliseconds between the Unix epoch and the Migo epoch; timestamps travel relative to it.',
  );
  out += `const val EPOCH_MS: Long = ${meta.epoch_ms}L\n\n`;

  // Features. bitmask64 maps to ULong, which is not a const-safe type, so these are `val`s on
  // an object. The bit value is precomputed rather than shifted at runtime, so nothing depends
  // on whether the stdlib exposes `shl` for ULong on the target Kotlin version.
  out += kdoc('Negotiable feature bits exchanged in HELLO/WELCOME.');
  out += `object Feature {\n`;
  for (const f of meta.features) {
    out += kdoc(f.description, '    ');
    out += `    val ${f.name}: ULong = ${1n << BigInt(f.bit)}uL\n`;
  }
  out += `\n`;
  out += kdoc('Everything this build understands.', '    ');
  out += `    val ALL: ULong = ${meta.features.map((f) => f.name).join(' or ')}\n}\n\n`;

  // Error codes
  out += kdoc('Stable protocol error codes. Frozen once released.');
  out += `object Code {\n`;
  for (const e of errorsDoc.errors) {
    out += kdoc(e.doc, '    ');
    out += `    const val ${e.symbol}: Long = ${e.code}L\n`;
  }
  out += `\n`;
  out += kdoc('Every code in this build, for exhaustive tests and registry dumps.', '    ');
  out += `    val ALL: LongArray = longArrayOf(\n${errorsDoc.errors.map((e) => `        ${e.symbol},`).join('\n')}\n    )\n}\n\n`;

  // Registry lookups
  out += kdoc('Symbolic name for a code, or null if this build does not know it.');
  out += `val ERROR_SYMBOLS: Map<Long, String> = mapOf(\n${errorsDoc.errors.map((e) => `    ${e.code}L to "${e.symbol}",`).join('\n')}\n)\n\n`;
  out += kdoc('Suggested HTTP status for a code, for gateways that bridge to REST.');
  out += `val ERROR_HTTP_STATUS: Map<Long, Int> = mapOf(\n${errorsDoc.errors.map((e) => `    ${e.code}L to ${e.http},`).join('\n')}\n)\n\n`;
  out += `fun errorSymbol(code: Long): String? = ERROR_SYMBOLS[code]\n\n`;

  // Error classes
  out += kdoc(
    'Behavioural class of an error code, so a client can react without knowing every code.',
  );
  out += `enum class ErrorClass {\n${errorsDoc.classes.map((c) => `    ${c.name},`).join('\n')}\n    Unknown,\n}\n\n`;
  out += `private data class ErrorRange(val from: Long, val to: Long, val cls: ErrorClass, val retryable: Boolean, val action: String)\n\n`;
  out += `private val ERROR_RANGES: List<ErrorRange> = listOf(\n${errorsDoc.classes.map((c) => `    ErrorRange(${c.range[0]}L, ${c.range[1]}L, ErrorClass.${c.name}, ${c.retryable}, "${c.client_action}"),`).join('\n')}\n)\n\n`;
  out += `private fun rangeOf(code: Long): ErrorRange? = ERROR_RANGES.firstOrNull { code in it.from..it.to }\n\n`;
  out += `fun errorClass(code: Long): ErrorClass = rangeOf(code)?.cls ?: ErrorClass.Unknown\n\n`;
  out += kdoc('Whether a client may retry the same request unchanged.');
  out += `fun isRetryable(code: Long): Boolean = rangeOf(code)?.retryable ?: false\n\n`;
  out += kdoc('What a client should do about this error, without knowing every code.');
  out += `fun clientAction(code: Long): String = rangeOf(code)?.action ?: "backoff_retry"\n\n`;

  // Enums
  for (const e of enums) {
    out += kdoc(e.doc);
    out += `enum class ${e.name}(val wire: Int) {\n`;
    out += e.variants.map((v) => `${kdoc(v.doc, '    ')}    ${v.name}(${v.value})`).join(',\n');
    out += `;\n\n    fun toWire(): Int = wire\n\n    companion object {\n`;
    out += `        /** Unknown discriminants decode to [Unknown] so a new variant never breaks an old peer. */\n`;
    out += `        fun fromWire(value: Long): ${e.name} = when (value) {\n`;
    for (const v of e.variants)
      if (v.name !== 'Unknown') out += `            ${v.value}L -> ${v.name}\n`;
    out += `            else -> Unknown\n        }\n    }\n}\n\n`;
  }

  // Structs
  for (const s of structs) {
    const req = s.fields.filter((f) => !f.optional);
    const opt = s.fields.filter((f) => f.optional);
    const all = [...req, ...opt];
    out += kdoc(s.doc);
    // An empty struct would compile in Rust and TypeScript, but Kotlin refuses a `data class`
    // with no primary constructor parameters — the grammar demands at least one. A plain
    // `class` with the empty constructor that the body already emits works.
    out += `${all.length === 0 ? 'class' : 'data class'} ${s.name}(\n`;
    for (const f of req) {
      out += kdoc(f.doc, '    ');
      out += `    val ${camel(f.name)}: ${kotlinType(f.type)},\n`;
    }
    for (const f of opt) {
      out += kdoc(f.doc, '    ');
      out += `    val ${camel(f.name)}: ${kotlinType(f.type)}? = null,\n`;
    }
    out += `) {\n`;

    // encode: required fields positional, then a count of present optionals, then each present
    // optional as (field_id, byte_len, bytes) — identical framing to the Rust/TS encoders.
    out += `    fun encode(w: Writer) {\n        w.enter()\n`;
    for (const f of req) out += indentLines(kotlinWrite(f.type, camel(f.name)), 8) + '\n';
    if (opt.length) {
      out += `        var present = 0\n`;
      for (const f of opt) out += `        if (${camel(f.name)} != null) present++\n`;
      out += `        w.u32(present)\n`;
      for (const f of opt) {
        const name = camel(f.name);
        out += `        if (${name} != null) {\n            val value = ${name}\n            w.optional(${f.id}) { w ->\n`;
        out += indentLines(kotlinWrite(f.type, 'value'), 16) + '\n';
        out += `            }\n        }\n`;
      }
    } else {
      out += `        w.u32(0)\n`;
    }
    out += `        w.leave()\n    }\n\n`;

    // decode: read required, then the optional count, then dispatch each length-delimited field
    // by id. Unknown ids are skipped by their length prefix — the forward compatibility MSE exists
    // to provide.
    out += `    companion object {\n        fun decode(r: Reader): ${s.name} {\n            r.enter()\n`;
    for (const f of req) out += `            val ${camel(f.name)} = ${kotlinRead(f.type)}\n`;
    for (const f of opt) out += `            var ${camel(f.name)}: ${kotlinType(f.type)}? = null\n`;
    out += `            val optionalCount = r.u32()\n            for (i in 0L until optionalCount) {\n`;
    if (opt.length) {
      out += `                val (fieldId, sub) = r.optional()\n                when (fieldId) {\n`;
      for (const f of opt)
        out += `                    ${f.id}L -> ${camel(f.name)} = ${kotlinRead(f.type, 'sub')}\n`;
      out += `                    else -> {} // unknown optional field: skipped by length (forward compatibility)\n                }\n`;
    } else {
      out += `                r.optional() // no optional fields in this build; a newer peer's are skipped by length\n`;
    }
    out += `            }\n            r.leave()\n            return ${s.name}(${all.map((f) => camel(f.name)).join(', ')})\n        }\n    }\n}\n\n`;
  }

  // Delivery / auth / direction
  out += kdoc('Delivery class, deciding what happens when a session queue is full.');
  out += `enum class DeliveryClass { ${meta.delivery_classes.map((c) => c.name).join(', ')} }\n`;
  out += kdoc('Minimum session state an opcode requires.');
  out += `enum class AuthLevel { ${meta.auth_levels.map((a) => a.name).join(', ')} }\n`;
  out += kdoc('Direction an opcode may legally travel.');
  out += `enum class Direction { ClientToServer, ServerToClient, Both }\n\n`;

  // Opcodes
  out += kdoc(`Every opcode in MWP/${meta.protocol.version}.`);
  out += `object Op {\n`;
  for (const o of opcodesDoc.opcodes) {
    out += kdoc(o.doc, '    ');
    out += `    const val ${o.name}: Long = ${o.code}L\n`;
  }
  out += `}\n\n`;

  out += kdoc(
    'Static metadata for one opcode: its rate-limit cost, delivery class, required auth, and shape.',
  );
  out += `data class OpcodeMeta(\n    val code: Long,\n    val name: String,\n    val cost: Int,\n    val cls: DeliveryClass,\n    val auth: AuthLevel,\n    val direction: Direction,\n    val ackRequired: Boolean,\n    val payload: String,\n    val response: String? = null,\n    val coalesceKey: String? = null,\n)\n\n`;

  out += `val OPCODES: Map<Long, OpcodeMeta> = mapOf(\n`;
  for (const o of opcodesDoc.opcodes) {
    const parts = [
      `${o.code}L`,
      `"${o.name}"`,
      `${o.cost}`,
      `DeliveryClass.${o.class}`,
      `AuthLevel.${o.auth}`,
      `Direction.${dirMap[o.direction]}`,
      `${!!o.ack_required}`,
      `"${o.payload}"`,
      o.response ? `"${o.response}"` : 'null',
      o.coalesce_key ? `"${o.coalesce_key}"` : 'null',
    ];
    out += `    ${o.code}L to OpcodeMeta(${parts.join(', ')}),\n`;
  }
  out += `)\n\n`;

  out += kdoc('Human name for an opcode, for logs and errors. Never used on the wire.');
  out += `fun opcodeName(code: Long): String = OPCODES[code]?.name ?: ("UNKNOWN(0x" + code.toString(16) + ")")\n`;

  return out;
}

// ---------------------------------------------------------------- emit

/**
 * Formats emitted Rust with rustfmt.
 *
 * Without this, two CI gates contradict each other: `make fmt` reformats the
 * committed generated file, and `make protocol-check` then reports it stale
 * because the generator would have emitted something else. Whichever ran last
 * wins and the other fails, which is not a race anybody should have to debug.
 *
 * Running the generator's output through the same formatter the repository uses
 * makes it canonical, so `cargo fmt` is a no-op on these files forever. It also
 * serves ADR-0010 directly: generated code is committed so that humans read it in
 * review, and unformatted Rust is not read.
 */
function rustfmt(source, label) {
  const result = spawnSync('rustfmt', ['--edition', '2021', '--emit', 'stdout'], {
    input: source,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error?.code === 'ENOENT') {
    console.error(
      'rustfmt is not on PATH. Generated Rust must be formatted or the fmt and\n' +
        'protocol-check gates disagree — run `rustup component add rustfmt`.',
    );
    process.exit(1);
  }
  if (result.status !== 0) {
    // A syntax error here is a bug in the generator, and it is far cheaper to
    // find now than as a confusing compile error in the emitted file.
    console.error(`rustfmt rejected the generated ${label}:\n${result.stderr}`);
    process.exit(1);
  }
  return result.stdout;
}

/**
 * Formats emitted TypeScript with the repository's prettier.
 *
 * The same reasoning as `rustfmt`, one toolchain over: `make fmt-check-js`
 * gates the committed file on prettier, and `make protocol-check` gates it on
 * the generator's output. Until the feature registry and the error table were
 * small enough, the generator's hand-wrapped lines stayed inside prettier's
 * width and the two gates agreed by accident; TCP_TRANSPORT and CHALLENGE_INVALID
 * pushed two constructs past it, and the gates now contradict. Running the
 * output through the same prettier the repository uses makes it canonical, so
 * the two can never disagree again.
 */
function prettify(source) {
  const result = spawnSync(
    PNPM,
    ['exec', 'prettier', '--stdin-filepath', 'packages/protocol/src/generated.ts'],
    {
      cwd: ROOT,
      input: source,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    },
  );
  if (result.error?.code === 'ENOENT' || result.status !== 0) {
    console.error(
      'prettier is unavailable (run `pnpm install`). Generated TypeScript must be\n' +
        'formatted or the fmt-check-js and protocol-check gates disagree.',
    );
    process.exit(1);
  }
  return result.stdout;
}

const targets = [
  {
    path: join(ROOT, 'server/crates/migo-wire/src/limits.rs'),
    content: rustfmt(genRustLimits(), 'limits.rs'),
  },
  {
    path: join(ROOT, 'server/crates/migo-wire/src/flags.rs'),
    content: rustfmt(genRustFlags(), 'flags.rs'),
  },
  {
    path: join(ROOT, 'server/crates/migo-protocol/src/generated.rs'),
    content: rustfmt(genRust(), 'generated.rs'),
  },
  // TypeScript through the repository's prettier, for the same reason the Rust
  // targets go through rustfmt: the fmt gate and the protocol gate must agree
  // on one canonical form.
  { path: join(ROOT, 'packages/protocol/src/generated.ts'), content: prettify(genTs()) },
  // Kotlin, likewise emitted as-is — the Android build has no in-tree formatter, and
  // the wire foundation it imports (com.migo.core.wire) is hand-written, not generated.
  {
    path: join(ROOT, 'clients/android/core/src/main/kotlin/com/migo/core/protocol/Generated.kt'),
    content: genKotlin(),
  },
];

let stale = false;
for (const t of targets) {
  const existing = existsSync(t.path) ? readFileSync(t.path, 'utf8') : null;
  if (existing === t.content) {
    console.log(`up to date  ${t.path.replace(ROOT + '/', '')}`);
    continue;
  }
  if (CHECK) {
    stale = true;
    console.error(`STALE       ${t.path.replace(ROOT + '/', '')}`);
    continue;
  }
  mkdirSync(dirname(t.path), { recursive: true });
  writeFileSync(t.path, t.content);
  console.log(`written     ${t.path.replace(ROOT + '/', '')}  (${t.content.length} bytes)`);
}

if (CHECK && stale) {
  console.error('\ngenerated protocol code is stale — run `make protocol` and commit the result');
  process.exit(1);
}
console.log(
  `\n${structs.length} structs, ${enums.length} enums, ${opcodesDoc.opcodes.length} opcodes, ${errorsDoc.errors.length} error codes`,
);
