-- 0001_initial.sql — the schema Migo starts from.
--
-- Applied by `migod migrate`, which embeds this file through SeaORM's migrator.
-- Once applied it must never be edited (docs/04-data-model.md §5): the migrator
-- records only that the name ran, not what it contained, so an edit here silently
-- means "applied" on old databases and something else on new ones. Fix a mistake
-- with 0002, not with a rewrite of history — `make brief-check` cannot catch this
-- one for you.
--
-- Conventions used throughout:
--
--   * Primary keys are UUIDv7 generated by the application, not by the database.
--     Time-ordered keys give index locality, and generating them in the process
--     means an insert needs no round trip to learn its own id — which matters
--     for a client that created the id offline.
--   * Enumerations are `smallint` matching the protocol's generated enums. Not
--     Postgres `enum` types: adding a variant to those takes a lock, and the
--     protocol is already the single source of truth for the numbering.
--   * Every timestamp is `timestamptz`. A naive timestamp in a system that will
--     run in more than one region is a bug with a delay fuse.
--   * Money is `bigint` minor units. Never floating point.
--   * Deletes that clients must converge on are tombstones, not row removals.

-- ---------------------------------------------------------------------------
-- Accounts, devices, sessions
-- ---------------------------------------------------------------------------

create table account (
    account_id      uuid primary key,
    username        text        not null,
    username_lower  text        not null,
    email           text,
    email_lower     text,
    phone           text,
    password_hash   text        not null,
    status          smallint    not null default 0,   -- 0 active, 1 suspended, 2 deactivated, 3 deleted
    country         char(2),
    locale          text        not null default 'en',
    created_at      timestamptz not null,
    updated_at      timestamptz not null,
    last_login_at   timestamptz,
    suspended_until timestamptz,
    deleted_at      timestamptz,
    -- Country is normalised on the way in and held to it here. Section 32's country
    -- leaderboard compares this column to a code the client supplied, and it has to do
    -- that through account_country_idx rather than through upper(country), or a top-ten
    -- becomes a scan of every account ever registered. An index on a raw column serves
    -- only an exact comparison, so the column is allowed exactly one spelling. Null
    -- passes: a check is not evaluated against an unknown.
    check (country = upper(country))
);

-- Case-insensitive uniqueness without the citext extension: a generated lower
-- column plus a plain unique index. One less extension to keep installed on
-- every replica, and the index is usable by lookups written the same way.
create unique index account_username_lower_key on account (username_lower);
create unique index account_email_lower_key on account (email_lower) where email_lower is not null;
create unique index account_phone_key on account (phone) where phone is not null;
create index account_created_at_idx on account (created_at desc);
-- Section 32 wants a country leaderboard. Partial, because the column is nullable
-- and a null country is not a country anybody can be top of.
create index account_country_idx on account (country) where country is not null;

create table profile (
    account_id      uuid primary key references account (account_id) on delete cascade,
    display_name    text        not null,
    bio             text,
    avatar_media_id uuid,
    birth_year      smallint,
    -- Presence and "last seen" are ephemeral (Redis), but the *policy* for who
    -- may see them is durable, so it lives here.
    show_last_seen  smallint    not null default 1,   -- 0 nobody, 1 friends, 2 everyone
    who_can_message smallint    not null default 2,   -- 0 nobody, 1 friends, 2 everyone
    who_can_add     smallint    not null default 2,
    searchable      boolean     not null default true,
    updated_at      timestamptz not null
);

create table device (
    device_id     uuid primary key,
    account_id    uuid        not null references account (account_id) on delete cascade,
    platform      smallint    not null,
    display_name  text        not null,
    app_version   text        not null,
    os_version    text,
    device_model  text,
    -- Push tokens are credentials for a third-party service, and section 77 says
    -- they are stored hashed and never logged. A hash alone would be unusable --
    -- a one-way hash of a push token is a token nobody can ever push to -- so the
    -- credential is split across two columns with two different jobs.
    --
    -- push_token holds the token sealed by migo-notify before it ever reaches the
    -- storage layer: nonce || ciphertext || tag, base64. No key for it exists in
    -- this process or in this database, so a dump of these columns is not a set of
    -- push credentials.
    --
    -- push_token_hash is the handle. Every lookup, every deduplication, and every
    -- reference in a log line uses it, which is what makes "never log the token"
    -- a rule somebody can actually follow while still debugging delivery.
    push_token      text,
    push_token_hash text,
    push_provider   smallint,
    -- When the registration was last refreshed. FCM and APNs both expire tokens
    -- silently, and a send to a dead token is charged, rate-limited, and useless;
    -- this is what the sweeper reads to stop paying for devices that left.
    push_updated_at timestamptz,
    created_at      timestamptz not null,
    last_seen_at    timestamptz not null,
    revoked_at      timestamptz
);

create index device_account_idx on device (account_id) where revoked_at is null;

-- Unique, because a token identifies a *phone*, not a row here. Restore a backup
-- onto a new handset and the platform hands the same token to a device row that
-- did not exist yesterday; without this the old row keeps it too, and one
-- notification becomes two pushes to one phone, forever. The insert takes the
-- token from whoever held it last.
create unique index device_push_token_hash_key on device (push_token_hash)
    where push_token_hash is not null;

create table session (
    session_id         uuid primary key,
    account_id         uuid        not null references account (account_id) on delete cascade,
    device_id          uuid        not null references device (device_id) on delete cascade,
    -- All rotations of one login share a family. Detecting reuse of a retired
    -- refresh token means the family was stolen, and the whole family dies.
    family_id          uuid        not null,
    refresh_hash       bytea       not null,
    generation         integer     not null default 0,
    created_at         timestamptz not null,
    -- When the human last proved presence by typing a password or passkey. Carried
    -- forward across rotations, because a refresh proves possession of a token and
    -- not the presence of a person. Sensitive operations compare against this
    -- (REAUTHENTICATION_REQUIRED, error 1108).
    authenticated_at   timestamptz not null,
    rotated_at         timestamptz,
    access_expires_at  timestamptz not null,
    refresh_expires_at timestamptz not null,
    revoked_at         timestamptz,
    revoked_reason     smallint,
    -- Truncated to a /24 or /48 class before storage, kept 7 days (retention
    -- policy in docs/04-data-model.md §6). Never a full address.
    ip_class           text,
    user_agent         text
);

create unique index session_refresh_hash_key on session (refresh_hash);
create index session_account_idx on session (account_id) where revoked_at is null;
create index session_family_idx on session (family_id);
create index session_refresh_expiry_idx on session (refresh_expires_at) where revoked_at is null;

-- ---------------------------------------------------------------------------
-- Key material: public halves only, forever
-- ---------------------------------------------------------------------------

create table identity_key (
    account_id  uuid        not null references account (account_id) on delete cascade,
    device_id   uuid        not null references device (device_id) on delete cascade,
    -- 64 bytes: Ed25519 signing key || X25519 exchange key.
    public_key  bytea       not null,
    created_at  timestamptz not null,
    revoked_at  timestamptz,
    primary key (account_id, device_id)
);

create table signed_prekey (
    account_id  uuid        not null,
    device_id   uuid        not null,
    key_id      integer     not null,
    public_key  bytea       not null,
    signature   bytea       not null,
    created_at  timestamptz not null,
    expires_at  timestamptz not null,
    primary key (account_id, device_id, key_id),
    foreign key (account_id, device_id) references identity_key (account_id, device_id) on delete cascade
);

create table one_time_prekey (
    account_id  uuid        not null,
    device_id   uuid        not null,
    key_id      integer     not null,
    public_key  bytea       not null,
    created_at  timestamptz not null,
    consumed_at timestamptz,
    primary key (account_id, device_id, key_id),
    foreign key (account_id, device_id) references identity_key (account_id, device_id) on delete cascade
);

-- Handing out a bundle takes the oldest unconsumed key. Partial index so that
-- pick is an index scan over live rows only, not over every key ever published.
create index one_time_prekey_available_idx
    on one_time_prekey (account_id, device_id, key_id)
    where consumed_at is null;

-- ---------------------------------------------------------------------------
-- Conversations and messages
-- ---------------------------------------------------------------------------

create table conversation (
    conversation_id uuid primary key,
    kind            smallint    not null,             -- ConversationKind
    encryption      smallint    not null,             -- EncryptionMode
    room_id         uuid,
    -- The sequencer. `update ... returning` on this row is what makes seq
    -- assignment atomic without a global lock or a sequence per conversation.
    last_seq        bigint      not null default 0,
    created_by      uuid        not null references account (account_id),
    created_at      timestamptz not null,
    last_message_at timestamptz,
    archived_at     timestamptz
);

create index conversation_room_idx on conversation (room_id) where room_id is not null;

create table conversation_member (
    conversation_id uuid        not null references conversation (conversation_id) on delete cascade,
    account_id      uuid        not null references account (account_id) on delete cascade,
    role            smallint    not null default 0,
    joined_at       timestamptz not null,
    left_at         timestamptz,
    muted_until     timestamptz,
    pinned          boolean     not null default false,
    primary key (conversation_id, account_id)
);

create index conversation_member_account_idx
    on conversation_member (account_id)
    where left_at is null;

-- A direct conversation is keyed by its ordered pair so "open a chat with Bob"
-- is idempotent under concurrency instead of racing into two conversations.
create table direct_conversation (
    low_account_id  uuid not null references account (account_id) on delete cascade,
    high_account_id uuid not null references account (account_id) on delete cascade,
    conversation_id uuid not null references conversation (conversation_id) on delete cascade,
    primary key (low_account_id, high_account_id),
    check (low_account_id < high_account_id)
);

-- The hottest table in the system, partitioned monthly by created_at.
--
-- The partition key has to be in every unique constraint, which is why the
-- primary key is (created_at, message_id) rather than message_id alone. Dedup of
-- a client retry is by (conversation_id, message_id) inside a partition; retries
-- happen within seconds, so a retry landing in a different month is not a case
-- worth carrying complexity for.
create table message (
    message_id      uuid        not null,
    conversation_id uuid        not null,
    seq             bigint      not null,
    sender_id       uuid        not null,
    sender_device   uuid,
    kind            smallint    not null,
    -- Ciphertext for private conversations, MSE payload for public rooms. The
    -- database cannot read the former, and no server role can either.
    envelope        bytea       not null,
    reply_to        uuid,
    expires_at      timestamptz,
    created_at      timestamptz not null,
    edited_at       timestamptz,
    deleted_at      timestamptz,
    deleted_by      uuid,
    primary key (created_at, message_id)
) partition by range (created_at);

create unique index message_conversation_seq_key on message (conversation_id, seq, created_at);
create unique index message_dedup_key on message (conversation_id, message_id, created_at);
create index message_paging_idx on message (conversation_id, seq desc);
create index message_live_idx on message (conversation_id, created_at desc) where deleted_at is null;
create index message_expiry_idx on message (expires_at) where expires_at is not null;

-- Partitions for the current window. `migod maintain` creates the next month
-- ahead of time; the default partition means a missing one degrades to a slower
-- insert instead of a failed one, which is the right way round for a chat app.
create table message_default partition of message default;
create table message_2026_01 partition of message for values from ('2026-01-01') to ('2026-02-01');
create table message_2026_02 partition of message for values from ('2026-02-01') to ('2026-03-01');
create table message_2026_03 partition of message for values from ('2026-03-01') to ('2026-04-01');
create table message_2026_04 partition of message for values from ('2026-04-01') to ('2026-05-01');
create table message_2026_05 partition of message for values from ('2026-05-01') to ('2026-06-01');
create table message_2026_06 partition of message for values from ('2026-06-01') to ('2026-07-01');
create table message_2026_07 partition of message for values from ('2026-07-01') to ('2026-08-01');
create table message_2026_08 partition of message for values from ('2026-08-01') to ('2026-09-01');
create table message_2026_09 partition of message for values from ('2026-09-01') to ('2026-10-01');
create table message_2026_10 partition of message for values from ('2026-10-01') to ('2026-11-01');
create table message_2026_11 partition of message for values from ('2026-11-01') to ('2026-12-01');
create table message_2026_12 partition of message for values from ('2026-12-01') to ('2027-01-01');

-- Unread counts are derived: last_seq − read_seq. A stored counter drifts, and
-- reconciling a drifted counter is worse than computing the difference.
create table conversation_cursor (
    conversation_id uuid        not null references conversation (conversation_id) on delete cascade,
    account_id      uuid        not null references account (account_id) on delete cascade,
    delivered_seq   bigint      not null default 0,
    read_seq        bigint      not null default 0,
    notified_seq    bigint      not null default 0,
    updated_at      timestamptz not null,
    primary key (conversation_id, account_id)
);

-- ---------------------------------------------------------------------------
-- Rooms
-- ---------------------------------------------------------------------------

create table room (
    room_id           uuid primary key,
    conversation_id   uuid        not null unique references conversation (conversation_id) on delete cascade,
    slug              text        not null,
    name              text        not null,
    topic             text,
    kind              smallint    not null,           -- RoomKind: public | managed | private
    owner_id          uuid        not null references account (account_id),
    home_region       text        not null,
    member_count      integer     not null default 0,
    max_members       integer     not null default 500,
    slow_mode_seconds integer     not null default 0,
    join_policy       smallint    not null default 0, -- 0 open, 1 request, 2 invite only
    -- Public and Managed rooms are transport-encrypted and server-readable, and
    -- the client is required to say so. Private rooms are end-to-end.
    encryption        smallint    not null,
    created_at        timestamptz not null,
    updated_at        timestamptz not null,
    archived_at       timestamptz
);

create unique index room_slug_key on room (lower(slug));
create index room_browse_idx on room (kind, member_count desc) where archived_at is null;

create table room_member (
    room_id           uuid        not null references room (room_id) on delete cascade,
    account_id        uuid        not null references account (account_id) on delete cascade,
    role              smallint    not null default 0, -- RoomRole
    -- Effective permission = role_default | grant, then & ~deny. Deny wins:
    -- moderation must never be overridable by an inherited grant.
    permissions_grant bigint      not null default 0,
    permissions_deny  bigint      not null default 0,
    joined_at         timestamptz not null,
    left_at           timestamptz,
    muted_until       timestamptz,
    banned_until      timestamptz,
    ban_reason        text,
    invited_by        uuid,
    primary key (room_id, account_id)
);

create index room_member_account_idx on room_member (account_id) where left_at is null;
create index room_member_roster_idx on room_member (room_id, role) where left_at is null;

create table room_moderation_action (
    action_id  uuid primary key,
    room_id    uuid        not null references room (room_id) on delete cascade,
    actor_id   uuid        not null references account (account_id),
    target_id  uuid        references account (account_id),
    action     smallint    not null,
    reason     text,
    expires_at timestamptz,
    created_at timestamptz not null
);

create index room_moderation_room_idx on room_moderation_action (room_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Social graph
-- ---------------------------------------------------------------------------

create table relationship (
    account_id uuid        not null references account (account_id) on delete cascade,
    other_id   uuid        not null references account (account_id) on delete cascade,
    kind       smallint    not null,                  -- RelationshipKind
    created_at timestamptz not null,
    -- Set on a friend request until the other side accepts. A pending row is
    -- how "requested" is represented; there is no separate request table.
    accepted_at timestamptz,
    primary key (account_id, other_id, kind),
    check (account_id <> other_id)
);

create index relationship_reverse_idx on relationship (other_id, kind);

-- ---------------------------------------------------------------------------
-- Economy: double-entry, append-only (ADR-0007)
-- ---------------------------------------------------------------------------

create table ledger_account (
    ledger_account_id uuid primary key,
    owner_id          uuid references account (account_id) on delete restrict,
    kind              smallint    not null,           -- 0 user, 1 mint, 2 fee, 3 escrow
    currency          smallint    not null,           -- 0 coins, 1 gems, 2 points
    created_at        timestamptz not null
);

-- One account per (owner, kind, currency). System accounts have a null owner,
-- and `coalesce` keeps the unique index working for them.
create unique index ledger_account_owner_key
    on ledger_account (coalesce(owner_id, '00000000-0000-0000-0000-000000000000'::uuid), kind, currency);

create table ledger_transaction (
    tx_id           uuid primary key,
    reason          smallint    not null,
    ref_id          uuid,
    -- A retried gift must not double-charge. The key is unique, so the retry
    -- collides and the caller reads back the original transaction.
    idempotency_key text        not null unique,
    created_at      timestamptz not null,
    created_by      uuid references account (account_id)
);

create table ledger_entry (
    tx_id      uuid        not null references ledger_transaction (tx_id) on delete restrict,
    -- Which leg of the transaction this is. Part of the key rather than a
    -- surrogate id, because nothing outside the ledger ever needs to name a
    -- single entry, and the legs have to read back in the order they were
    -- posted: a debit followed by a credit is a transfer, the other order is a
    -- refund, and the difference matters in a receipt.
    leg_index  smallint    not null,
    account_id uuid        not null references ledger_account (ledger_account_id) on delete restrict,
    -- Signed minor units. Every transaction's entries must sum to zero; the
    -- application asserts it before insert and a nightly job re-asserts it over
    -- the whole table, because an invariant nobody checks is a wish.
    amount     bigint      not null,
    currency   smallint    not null,
    created_at timestamptz not null,
    primary key (tx_id, leg_index),
    check (amount <> 0)
);

-- No index on tx_id alone: the primary key already leads with it.
create index ledger_entry_account_idx on ledger_entry (account_id, created_at desc);

-- Balances are the sum of entries. Snapshots exist only so that sum does not
-- have to start from the beginning of time; they are derived and rebuildable.
create table ledger_snapshot (
    ledger_account_id uuid        not null references ledger_account (ledger_account_id) on delete cascade,
    as_of             timestamptz not null,
    balance           bigint      not null,
    entry_count       bigint      not null,
    primary key (ledger_account_id, as_of)
);

-- Who gave what to whom. Section 28 says gifts appear in a profile and in chat,
-- and the ledger cannot answer that: a ledger transaction records that coins
-- moved, not that the thing they bought was a Dragon. This is the receipt.
--
-- Written in the same transaction as the ledger post it names, which is what
-- makes "charge and deliver" one event rather than two. The unique index on
-- tx_id is the mechanism: the ledger's own idempotency key already collapses a
-- retried gift into one transaction, and one transaction can carry exactly one
-- receipt, so a retry cannot produce a second Dragon either.
create table gift_sent (
    gift_id         uuid primary key,
    tx_id           uuid        not null references ledger_transaction (tx_id) on delete restrict,
    sender_id       uuid        not null references account (account_id) on delete cascade,
    recipient_id    uuid        not null references account (account_id) on delete cascade,
    -- Text and not a smallint, unlike every other discriminator in this schema,
    -- and section 28 is the reason: gifts can be limited and seasonal, so this
    -- catalogue grows every December while NotificationKind does not. A code
    -- somebody can read in a dump beats a number they have to look up, and it
    -- matches badge_award.badge_code, which is the same kind of list.
    gift_code       text        not null,
    -- Where it was shown, when it was shown anywhere. Null for a gift sent from a
    -- profile. Set null on delete: the gift stays received after the conversation
    -- it was sent in is gone.
    conversation_id uuid references conversation (conversation_id) on delete set null,
    created_at      timestamptz not null
);

-- One receipt per transaction, in both directions. See the comment above.
create unique index gift_sent_tx_key on gift_sent (tx_id);
-- The profile view: everything this account has been given, newest first.
create index gift_recipient_idx on gift_sent (recipient_id, created_at desc);
-- The chat view.
create index gift_conversation_idx on gift_sent (conversation_id, created_at desc)
    where conversation_id is not null;

-- What an account owns. Section 29 lists seven things currency buys -- avatar
-- items, stickers, profile frames, themes, cosmetics, event entry, and gifts --
-- and six of those seven are durable. Without this table, spending coins burns
-- them and yields nothing anybody can point at, which is not a currency.
--
-- Deliberately the same shape as badge_award: a composite primary key over the
-- owner and a text code, no surrogate id. The primary key is what makes buying
-- the same theme twice impossible to represent rather than merely discouraged.
create table entitlement (
    account_id  uuid        not null references account (account_id) on delete cascade,
    -- Catalogue code, e.g. 'theme.midnight'. Text for the same reason as
    -- gift_code: this list is content, and content grows.
    sku         text        not null,
    acquired_at timestamptz not null,
    -- The purchase that granted it, absent for something granted by the system.
    -- Set null rather than restrict: an old transaction can be archived out from
    -- under an entitlement without taking away what somebody bought.
    tx_id       uuid references ledger_transaction (tx_id) on delete set null,
    primary key (account_id, sku)
);

-- ---------------------------------------------------------------------------
-- Progression
-- ---------------------------------------------------------------------------

create table progression (
    account_id uuid primary key references account (account_id) on delete cascade,
    xp         bigint      not null default 0,
    level      integer     not null default 1,
    updated_at timestamptz not null
);

-- Section 32's global leaderboard is "order by xp desc limit n", which without
-- this index is a sequential scan and a sort over every account that has ever
-- earned a point. The country leaderboard joins account_country_idx to this one.
create index progression_xp_idx on progression (xp desc);

-- One row per XP award, which the running total above cannot replace.
--
-- Two requirements need it and neither can be met by a counter. Section 32 ranks
-- weekly and monthly, and a weekly rank is the sum of what was earned inside the
-- week -- a lifetime total does not contain that number. Section 30 says "gunakan
-- anti-farming system", and the only honest way to cap what an account earns from
-- one source per day is to know what it has already earned from that source today.
-- Both are sums over a window, and a window needs events.
--
-- The total in progression is kept alongside rather than derived from this table,
-- because every profile view and the all-time leaderboard read it, and summing a
-- lifetime of awards to render one number would be the most expensive read in the
-- product. Both rows are written in one transaction, so the two cannot disagree.
--
-- No room_id column: the room leaderboard ranks a room's current members by what
-- they have earned anywhere, because five of section 30's seven sources have nothing
-- to do with a room. A column that only one source could ever fill would invite a
-- reader to believe the other six were losing data.
create table xp_award (
    award_id        uuid primary key,
    account_id      uuid        not null references account (account_id) on delete cascade,
    source          smallint    not null,
    amount          bigint      not null,
    ref_id          uuid,
    idempotency_key text,
    created_at      timestamptz not null,
    -- Section 30 describes earning and never spending. XP that can go down is XP a
    -- bug can take away, and an account holder who loses a level has no way to prove
    -- they ever had it.
    check (amount > 0)
);

-- The anti-farming read: what this account has earned since a cutoff, narrowed by
-- source in memory because one account's day is a handful of rows either way.
create index xp_award_account_idx on xp_award (account_id, created_at desc);
-- The windowed leaderboards group by account over a range of time.
create index xp_award_window_idx on xp_award (created_at desc);
-- A retried award is the same award. Partial, because most awards have nothing to be
-- idempotent against, and in PostgreSQL two null keys do not collide anyway -- the
-- predicate keeps those rows out of the index rather than relying on that.
create unique index xp_award_key on xp_award (idempotency_key) where idempotency_key is not null;

create table badge_award (
    account_id uuid        not null references account (account_id) on delete cascade,
    badge_code text        not null,
    awarded_at timestamptz not null,
    ref_id     uuid,
    primary key (account_id, badge_code)
);

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------

-- The inbox behind the bell icon.
--
-- Section 44 lists fourteen notification kinds. Six of them are not rows here,
-- and the discriminator is one question: does answering it make it go away by
-- itself?
--
-- An unread message answers yes -- conversation_cursor already holds last_seq and
-- read_seq, and the comment above it rejects a stored counter because a stored
-- counter drifts. A row per message would be that counter kept in a second place,
-- disagreeing with the first by the end of the week. The same goes for a voice
-- note, a mention, and a reply, which are messages with an attachment or a name in
-- them. A pending friend request answers yes too: the relationship row *is* the
-- inbox item, and it disappears when the request is answered, where a notification
-- row would linger until a second write cleared it. An incoming call answers yes
-- by expiring -- a call nobody picked up becomes a missed call, which is a row.
--
-- What is left answers no. A gift, a level up, a badge, an invitation to a room, a
-- room announcement, a scheduled event, a game challenge, a missed call: each one
-- happened, each one leaves a trace somewhere (a ledger transaction, a badge
-- award), and none of those traces records whether the person it happened to has
-- seen it. That is what this table is for, and it is all it is for.
--
-- Hence the two absences. There is no conversation_id, so a future author in a
-- hurry cannot fill this table with messages. And there is no title and no body,
-- for the same reason section 145's NotificationEvent leaves both empty: the
-- sentence is written on the client in the reader's own language, and a server
-- that stored the sentence would be storing "Alice: see you at eight" in plaintext
-- next to the ciphertext of the message it was rendered from.
create table notification (
    notification_id uuid primary key,
    account_id      uuid        not null references account (account_id) on delete cascade,
    kind            smallint    not null,      -- NotificationKind: 5 gift, 6 level up, 7 achievement, 8 room invite, 9 room announcement, 10 event, 11 game challenge, 13 missed call
    room_id         uuid references room (room_id) on delete cascade,
    -- Who caused it, where somebody did. Null for a level up, which nobody caused.
    -- Set null rather than cascade on delete: a gift that was received stays
    -- received after the giver closes their account.
    actor_id        uuid references account (account_id) on delete set null,
    -- What it points at: a transaction, a badge award, a call, a game session. No
    -- foreign key, because which table it points into depends on the kind, and a
    -- column that referenced one of them would quietly forbid the others.
    subject_id      uuid,
    created_at      timestamptz not null,
    read_at         timestamptz
);

-- Two indexes on the same columns, differing only in the predicate, because the
-- two queries are not equally hot: the badge count runs every time the app comes
-- to the foreground, while the list runs only when somebody taps the bell. The
-- partial index is the size of what is unread rather than of everything that has
-- ever happened, which is the difference between a count that stays cheap on an
-- old account and one that stops being cheap exactly when the account gets busy.
create index notification_unread_idx on notification (account_id, created_at desc)
    where read_at is null;
create index notification_inbox_idx on notification (account_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Media
-- ---------------------------------------------------------------------------

create table media_object (
    media_id    uuid primary key,
    owner_id    uuid        not null references account (account_id) on delete cascade,
    kind        smallint    not null,
    mime        text        not null,
    byte_size   bigint      not null,
    width       integer,
    height      integer,
    duration_ms integer,
    -- Object key in the bucket. The bytes never pass through the API process;
    -- clients upload and download with signed URLs.
    storage_key text        not null,
    -- Where the upload was destined, recorded when the client asks to begin so a
    -- later download can be authorised against membership rather than against
    -- knowledge of the id. Null for profile media such as an avatar, which every
    -- authenticated account may render. On delete set null rather than cascade:
    -- deleting a conversation must not silently delete the bytes people uploaded
    -- to it, because the sweeper is what removes bytes and it needs the row.
    conversation_id uuid references conversation (conversation_id) on delete set null,
    checksum    bytea,
    scan_status smallint    not null default 0,       -- 0 pending, 1 clean, 2 rejected
    created_at  timestamptz not null,
    deleted_at  timestamptz
);

create index media_owner_idx on media_object (owner_id, created_at desc);
create index media_conversation_idx on media_object (conversation_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Safety: reports, audit
-- ---------------------------------------------------------------------------

create table report (
    report_id    uuid primary key,
    reporter_id  uuid        not null references account (account_id) on delete cascade,
    subject_kind smallint    not null,                -- 0 user, 1 message, 2 room, 3 media, 4 bot
    subject_id   uuid        not null,
    room_id      uuid references room (room_id) on delete set null,
    reason       smallint    not null,
    note         text,
    -- Evidence is a reference, never a copy of message content: copying private
    -- ciphertext into a moderation table would defeat the point of encrypting it.
    evidence_ref uuid,
    status       smallint    not null default 0,      -- 0 open, 1 actioned, 2 dismissed
    created_at   timestamptz not null,
    resolved_at  timestamptz,
    resolved_by  uuid references account (account_id),
    resolution   smallint
);

create index report_queue_idx on report (status, created_at) where status = 0;
create index report_subject_idx on report (subject_kind, subject_id);

-- Written in the same transaction as the action it records, so an action
-- without an audit row cannot exist.
create table audit_entry (
    audit_id    uuid primary key,
    actor_id    uuid references account (account_id) on delete set null,
    actor_kind  smallint    not null default 0,       -- 0 user, 1 system, 2 bot, 3 operator
    action      text        not null,
    target_kind smallint    not null,
    target_id   uuid,
    -- A summary of what changed. Never message content.
    summary     text        not null,
    reason      text,
    request_id  text,
    ip_class    text,
    created_at  timestamptz not null
);

create index audit_actor_idx on audit_entry (actor_id, created_at desc);
create index audit_target_idx on audit_entry (target_kind, target_id, created_at desc);
create index audit_created_idx on audit_entry (created_at desc);

-- ---------------------------------------------------------------------------
-- Games and bots
-- ---------------------------------------------------------------------------

create table game_session (
    game_id         uuid primary key,
    kind            smallint    not null,
    conversation_id uuid        not null references conversation (conversation_id) on delete cascade,
    -- Authoritative state lives on the server: a client that computes its own
    -- score is a client that will eventually report a very good one.
    state           bytea       not null,
    turn_of         uuid references account (account_id),
    status          smallint    not null default 0,   -- 0 open, 1 finished, 2 abandoned
    stake_currency  smallint,
    stake_amount    bigint,
    created_at      timestamptz not null,
    updated_at      timestamptz not null,
    finished_at     timestamptz
);

create index game_conversation_idx on game_session (conversation_id, status);

create table bot (
    bot_id      uuid primary key,
    owner_id    uuid        not null references account (account_id) on delete cascade,
    account_id  uuid        not null unique references account (account_id) on delete cascade,
    name        text        not null,
    -- Hash, not the token. A leaked database must not yield working bot tokens.
    token_hash  bytea       not null,
    scopes      bigint      not null default 0,
    webhook_url text,
    created_at  timestamptz not null,
    disabled_at timestamptz
);

create unique index bot_token_hash_key on bot (token_hash);

-- ---------------------------------------------------------------------------
-- Federation
-- ---------------------------------------------------------------------------

create table node_peer (
    node_id      text primary key,
    public_key   bytea       not null,
    base_url     text        not null,
    region       text        not null,
    status       smallint    not null default 0,      -- 0 allowed, 1 paused, 2 blocked
    added_at     timestamptz not null,
    last_seen_at timestamptz
);

create unique index node_peer_key_key on node_peer (public_key);

-- Outbound federation events, delivered at least once with retries. A queue in
-- the database rather than in Redis: this one must survive a restart, and it is
-- written in the same transaction as the state change it announces.
create table federation_outbox (
    event_id        uuid primary key,
    target_node     text        not null,
    opcode          integer     not null,
    payload         bytea       not null,
    attempts        integer     not null default 0,
    created_at      timestamptz not null,
    next_attempt_at timestamptz not null,
    delivered_at    timestamptz,
    last_error      text
);

create index federation_outbox_due_idx
    on federation_outbox (next_attempt_at)
    where delivered_at is null;

-- ---------------------------------------------------------------------------
-- down (local development only; production is forward-only)
-- ---------------------------------------------------------------------------
-- drop table if exists federation_outbox, node_peer, bot, game_session,
--     audit_entry, report, media_object, badge_award, progression,
--     ledger_snapshot, ledger_entry, ledger_transaction, ledger_account,
--     relationship, room_moderation_action, room_member, room,
--     conversation_cursor, message, direct_conversation, conversation_member,
--     conversation, one_time_prekey, signed_prekey, identity_key, session,
--     device, profile, account cascade;
