-- 0002_captcha_challenges -- a one-row-per-challenge table for the public
-- bootstrap captcha. Consumed by `migo-captcha` (HMAC-signed numeric challenges
-- for /v1/auth/register and /v1/auth/login after enough failed attempts).
--
-- Applied by `migod migrate`, which embeds this file through SeaORM's migrator.
-- Once applied it must never be edited (docs/04-data-model.md §5): the migrator
-- records only that the name ran, not what it contained, so an edit here silently
-- means "applied" on old databases and something else on new ones. Fix a mistake
-- with 0003, not with a rewrite of history -- `make brief-check` cannot catch
-- this one for you.
--
-- Conventions (see 0001_initial.sql header for the long version):
--   * Primary keys are UUIDv7 generated by the application, time-ordered.
--   * Every timestamp is `timestamptz`.
--   * Indexes are created after the table and named `<table>_<columns>_idx`.

create table captcha_challenge (
    challenge_id  uuid primary key,
    -- The MAC tag over (challenge_id || code). Never the code itself: an attacker
    -- who can read this table still cannot answer without the secret, and the
    -- application code is the only thing that knows it. The code is gone the
    -- moment the challenge is consumed or expires.
    tag           bytea       not null,
    -- Wall-clock instant the challenge stops being accepted. Half-open: a verify
    -- at exactly this instant returns false. The default TTL is 60 seconds; the
    -- service bumps that on hot paths and stores the bumped value here.
    expires_at    timestamptz not null,
    created_at    timestamptz not null default now()
);

-- The hot path is `delete ... where expires_at < now()`. A partial index lets that
-- sweep touch only live rows, and the `expires_at_idx` name matches what the
-- captcha service expects in its `get` query plan.
create index captcha_challenge_expires_at_idx on captcha_challenge (expires_at);
