-- 0003_password_recovery -- the recovery-token table behind /v1/auth/recovery/*.
--
-- Applied by `migod migrate`, which embeds this file through SeaORM's migrator.
-- Once applied it must never be edited (docs/04-data-model.md §5): the migrator
-- records only that the name ran, not what it contained, so an edit here silently
-- means "applied" on old databases and something else on new ones. Fix a mistake
-- with 0004, not with a rewrite of history -- `make brief-check` cannot catch this
-- one for you.
--
-- Conventions (see 0001_initial.sql header for the long version):
--   * Primary keys are UUIDv7 generated by the application, time-ordered.
--   * Every timestamp is `timestamptz`.
--   * Indexes are created after the table and named `<table>_<columns>_idx`.

create table password_recovery (
    token_id    uuid primary key,
    -- Owning account. Indexed below so a future "list my outstanding recovery
    -- tokens" view does not scan the whole table.
    account_id  uuid        not null,
    -- The MAC tag over (token_id || 'recovery'). 32 bytes, like every other
    -- server-side tag. Never the plaintext, so a database dump is not a
    -- bypass: confirming a token requires the same MacKey root every other
    -- short-lived server token uses, with the LABEL_RECOVERY derivation.
    tag         bytea       not null,
    -- Wall-clock instant the token stops being accepted. The default is
    -- twenty minutes, derived from the captcha TTL plus a generous allowance
    -- for the email hop that does not exist yet.
    expires_at  timestamptz not null,
    -- Stamped when the token is exchanged for a new password. Distinct from
    -- the `expires_at` value so an operator can tell a deliberate use from a
    -- timeout without reading the audit log.
    consumed_at timestamptz,
    created_at  timestamptz not null default now()
);

-- "Which account asked for a recovery" is the one query an operator might
-- run from a manual console; serving it from the index turns a potential
-- table scan into a small bounded one.
create index password_recovery_account_idx on password_recovery (account_id);

-- The background sweep is `delete ... where expires_at < now() and consumed_at is null`.
-- A separate index on `expires_at` is cheap and lets that sweep walk only the live
-- rows, which is the same shape the captcha store uses.
create index password_recovery_expires_at_idx on password_recovery (expires_at);
