-- 0004_identity_login -- the ML-DSA account identity, its single-use login
-- challenges, and the EVM wallet registry (brief section 182).
--
-- Applied by `migod migrate`, which embeds this file through SeaORM's migrator.
-- Once applied it must never be edited (docs/04-data-model.md §5): the migrator
-- records only that the name ran, not what it contained, so an edit here silently
-- means "applied" on old databases and something else on new ones. Fix a mistake
-- with 0005, not with a rewrite of history -- `make brief-check` cannot catch this
-- one for you.
--
-- Conventions (see 0001_initial.sql header for the long version):
--   * Primary keys are UUIDv7 generated by the application, time-ordered.
--   * Every timestamp is `timestamptz`.
--   * Indexes are created after the table and named `<table>_<columns>__idx`.
--
-- Naming, stated once because it will confuse somebody eventually: `identity_key`
-- (singular, 0001) is the E2EE table -- the 64-byte Ed25519||X25519 pair X3DH
-- starts from. `identity_keys` (plural, here) is the ML-DSA account identity used
-- for challenge login. Different keys, different protocols, one letter apart;
-- the queries that touch them never overlap.

-- ---------------------------------------------------------------------------
-- The ML-DSA account identity
-- ---------------------------------------------------------------------------

create table identity_keys (
    key_id      uuid primary key,
    account_id  uuid        not null references account (account_id) on delete cascade,
    -- Agility is a column, not a constant (brief section 182): "ML-DSA-65" is
    -- what the first row says, and the next algorithm is a new row with a new
    -- name, never a redefinition of this one.
    algorithm   text        not null,
    -- 1-based, unique per account. Rotation appends version N+1 and flips the
    -- previous row to ROTATED inside one transaction, so an account always has
    -- exactly one ACTIVE identity key, whatever crashed mid-way.
    key_version integer     not null,
    -- The public half only: 1952 bytes for ML-DSA-65. The seed that produced it
    -- never leaves the device (brief section 182, SERVER TIDAK MENYIMPAN).
    public_key  bytea       not null,
    -- 1 active, 2 rotated, 3 revoked.
    status      smallint    not null,
    created_at  timestamptz not null,
    revoked_at  timestamptz
);

-- One active key per version number, and the (account_id, key_version) prefix
-- also serves the "list this account's keys newest first" read.
create unique index identity_keys_account_version_key on identity_keys (account_id, key_version);

-- ---------------------------------------------------------------------------
-- Single-use ML-DSA login challenges
-- ---------------------------------------------------------------------------

create table login_challenge (
    challenge_id uuid primary key,
    account_id   uuid        not null references account (account_id) on delete cascade,
    -- The challenge is bound to the device it was issued for. For purpose
    -- add-device that device row is created PENDING at issue time and activated
    -- only when the challenge is consumed, so an unconsumed challenge leaves no
    -- usable credential behind.
    device_id    uuid        not null references device (device_id) on delete cascade,
    -- Mirrors the protocol's MlDsaPurpose: 1 login, 2 add-device, 3 rotate.
    -- A challenge signed for one purpose is never accepted for another.
    purpose      smallint    not null,
    -- The exact canonical MSE bytes the client must sign, stored as issued and
    -- never re-derived: verification signs over what the server sent, not over
    -- what the client claims it received.
    payload      bytea       not null,
    -- Five minutes by policy. Expired rows are deleted by the same sweep that
    -- owns the captcha and recovery tables.
    expires_at   timestamptz not null,
    -- Stamped on first successful use; a second attempt sees the same error as
    -- an expired challenge, so replay tells the attacker nothing.
    consumed_at  timestamptz,
    created_at   timestamptz not null default now()
);

create index login_challenge_expires_at_idx on login_challenge (expires_at);

-- ---------------------------------------------------------------------------
-- EVM wallet registry -- addresses only
-- ---------------------------------------------------------------------------

create table wallet (
    wallet_id        uuid primary key,
    account_id       uuid        not null references account (account_id) on delete cascade,
    -- Lowercase hex, 40 characters, no 0x prefix: the canonical form, so the
    -- unique index below cannot be defeated by a checksum-cased duplicate. The
    -- EIP-55 form is display material the clients derive; the server never
    -- needs it. No on-chain balance, no broadcast, no RPC in this version.
    address          text        not null,
    -- "evm" today. A second chain is a new row with a new chain_type, not a
    -- schema change.
    chain_type       text        not null,
    -- Optional, user-chosen, display only.
    label            text,
    -- The i in m/44'/60'/0'/0/i. Kept so a restore can re-register the same
    -- wallets in the same order without deriving a single key server-side.
    derivation_index integer     not null,
    -- 1 active, 2 archived.
    status           smallint    not null,
    created_at       timestamptz not null,
    archived_at      timestamptz
);

-- One registration per address per chain per account.
create unique index wallet_account_chain_address_key on wallet (account_id, chain_type, address);

-- ---------------------------------------------------------------------------
-- Device columns: lifecycle and the per-device login credential
-- ---------------------------------------------------------------------------

-- 1 pending, 2 active, 3 revoked. Every device that exists today is active --
-- `revoked_at` already carries the third state -- so the column arrives with a
-- default rather than a backfill.
alter table device add column status smallint not null default 2;

-- The ML-DSA public key of the device credential (1952 bytes for ML-DSA-65).
-- Null on devices registered before this migration, and filled in the first
-- time such a device signs in with the new flow or completes the legacy
-- upgrade. The seed behind it is random per device and never derived from the
-- root, so a leaked root secret alone cannot impersonate a registered device.
alter table device add column public_credential bytea;
