-- 0005_global_admins -- the global admins for public rooms, appointed by the
-- service's Owner/CEO (the account named by `auth.owner_account_id`).
--
-- Applied by `migod migrate`, which embeds this file through SeaORM's migrator.
-- Once applied it must never be edited (docs/04-data-model.md §5): the migrator
-- records only that the name ran, not what it contained, so an edit here silently
-- means "applied" on old databases and something else on new ones. Fix a mistake
-- with 0006, not with a rewrite of history.
--
-- Conventions (see 0001_initial.sql header for the long version):
--   * Primary keys are UUIDv7 generated by the application, time-ordered.
--   * Every timestamp is `timestamptz`.
--   * Indexes are created after the table and named `<table>_<columns>__idx`.

-- ---------------------------------------------------------------------------
-- The global admin registry
-- ---------------------------------------------------------------------------

-- One row per account that may moderate every public room. The primary key is
-- the account itself rather than a minted row id, because the row has no life
-- outside the account it names: a grant is the account's presence here, and a
-- revoke is its absence — there is no second grant to tell apart from the
-- first, so there is nothing for a row id to identify.
create table global_admin (
    account_id  uuid        not null references account (account_id) on delete cascade,
    -- Who appointed them. Always the Owner/CEO in this version — the column is
    -- the account that acted rather than a role, so the trail survives even if
    -- the owner designation itself ever moves. History lives in `audit_entry`
    -- (the grant and the revoke are both audited); this column answers the
    -- question a reader of the list asks next: "who put them there?".
    granted_by  uuid        not null references account (account_id),
    granted_at  timestamptz not null,
    primary key (account_id)
);

-- The management screen reads the whole registry in one go; there are meant to
-- be a handful of rows, and the primary key already serves the point lookups
-- the rooms service makes on every sanction a global admin issues.
