// @generated by tools/protocol-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: shared/protocol/schema (MWP/1).
// Regenerate with: make protocol

//! Frame flag bits, generated from `shared/protocol/schema/meta.json`.
//!
//! Reserved bits are listed explicitly and a receiver must **reject** a frame
//! that sets one. Ignoring unknown flags feels forgiving, but it would make the
//! bits unusable forever: old peers would already be accepting frames whose
//! meaning they cannot see, so a future version could never rely on them.

/// Payload is deflate-raw compressed
pub const COMPRESSED: u8 = 1 << 0;
/// 16-byte trace id + 8-byte span id precede the payload
pub const TRACED: u8 = 1 << 1;
/// Payload is varint count then count x (varint len, sub-frame)
pub const BATCH: u8 = 1 << 2;
/// Payload is Error instead of the opcode response type
pub const ERROR: u8 = 1 << 3;
/// Receiver must acknowledge by cumulative watermark
pub const ACK_REQUIRED: u8 = 1 << 4;
/// varint index, varint total follow; payload is a slice
pub const FRAGMENT: u8 = 1 << 5;
/// Reserved. MUST be zero. Reserved in MWP/1 for a future METADATA block (section 141); a frame that sets it is rejected.
pub const RESERVED_6: u8 = 1 << 6;
/// A second flags byte follows (reserved for MWP/2)
pub const FLAGS_EXT: u8 = 1 << 7;

/// Bits a MWP/1 receiver must reject.
pub const RESERVED_MASK: u8 = RESERVED_6 | FLAGS_EXT;

/// Every bit this build understands.
pub const KNOWN_MASK: u8 = COMPRESSED | TRACED | BATCH | ERROR | ACK_REQUIRED | FRAGMENT;

/// Renders the set bits as a stable, comma-separated list for logs.
#[must_use]
pub fn describe(bits: u8) -> String {
    let mut parts: Vec<&'static str> = Vec::new();
    if bits & COMPRESSED != 0 {
        parts.push("COMPRESSED");
    }
    if bits & TRACED != 0 {
        parts.push("TRACED");
    }
    if bits & BATCH != 0 {
        parts.push("BATCH");
    }
    if bits & ERROR != 0 {
        parts.push("ERROR");
    }
    if bits & ACK_REQUIRED != 0 {
        parts.push("ACK_REQUIRED");
    }
    if bits & FRAGMENT != 0 {
        parts.push("FRAGMENT");
    }
    if bits & RESERVED_6 != 0 {
        parts.push("RESERVED_6");
    }
    if bits & FLAGS_EXT != 0 {
        parts.push("FLAGS_EXT");
    }
    if parts.is_empty() {
        return "none".to_string();
    }
    parts.join(",")
}
