// @generated by tools/protocol-codegen/generate.mjs — DO NOT EDIT.
// Source of truth: shared/protocol/schema (MWP/1).
// Regenerate with: make protocol

//! Codec and session limits, generated from `shared/protocol/schema/meta.json`.
//!
//! These are enforced *before* allocation. A peer that claims a 4 GiB string
//! must be rejected while reading the length, not after reserving the buffer:
//! otherwise a 6-byte frame is a remote out-of-memory primitive.

/// Largest single frame, before compression on send and after decompression on receive.
pub const MAX_FRAME_BYTES: usize = 262144;
/// Largest UTF-8 string field.
pub const MAX_STRING_BYTES: usize = 65536;
/// Largest opaque byte field, sized for one E2E ciphertext.
pub const MAX_BYTES_LEN: usize = 131072;
/// Largest list field.
pub const MAX_LIST_ITEMS: usize = 4096;
/// Largest map field.
pub const MAX_MAP_ITEMS: usize = 1024;
/// Deepest struct nesting; bounds recursive decoding.
pub const MAX_NESTING_DEPTH: usize = 16;
/// Frames per BATCH envelope.
pub const MAX_BATCH_ITEMS: usize = 256;
/// Longest accepted varint encoding (10 bytes covers u64).
pub const MAX_VARINT_BYTES: usize = 10;
/// Payloads below this are never compressed: the header costs more than the saving.
pub const COMPRESS_MIN_BYTES: usize = 512;
/// Compression is discarded unless it saves at least this share of the payload.
pub const COMPRESS_MIN_GAIN_PERCENT: u32 = 10;
/// Topics one session may subscribe to.
pub const MAX_SUBSCRIPTIONS: usize = 512;
/// Default heartbeat interval advertised in WELCOME.
pub const DEFAULT_HEARTBEAT_MS: u32 = 30000;
/// Bounded outbound queue depth per session (ADR-0008).
pub const SESSION_QUEUE_CAPACITY: usize = 256;
/// Grace period before a session that cannot keep up is closed.
pub const LAGGING_DEADLINE_MS: u32 = 5000;
/// How long a batch stays open waiting for more events.
pub const BATCH_LINGER_MS: u32 = 15;
/// Frames retained per session for resume after a reconnect.
pub const RESUME_BUFFER_FRAMES: usize = 512;
/// How long after a disconnect a session may still be resumed.
pub const RESUME_WINDOW_MS: u32 = 120000;
